### ISSUE TITLE
Build error - open frontend\wailsjs\runtime\package.json: Access is denied.

### ISSUE THREAD

**Issue by Web3codexio** [wailsapp/wails#3148] opened 2023-12-19 11:15 UTC
### Description

it report that \frontend\wailsjs\runtime\package.json: Access is denied.

### To Reproduce

1、run wails dev

### Expected behaviour

the wails dev work well

### Screenshots

![1702984412427](https://github.com/wailsapp/wails/assets/50604703/573f7d59-75cc-493e-a9bf-49ecd5e61322)

### Attempted Fixes

i tried to update the wails to the latest version,but it still didn work

### System Details

```shell
# Wails
Version | v2.7.1

# System
┌──────────────────────────────────────────────────────────────────────────────────────┐ 
| OS           | Windows 10 Pro                                                        |
| Version      | 1809 (Build: 17763)                                                   |
| ID           |                                                                       |
| Go Version   | go1.20                                                                |
| Platform     | windows                                                               |
| Architecture | amd64                                                                 |
| CPU          | Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz                             |
| GPU 1        | NVIDIA GeForce GTX 950M (NVIDIA) - Driver: 31.0.15.3141               |
| GPU 2        | Intel(R) HD Graphics 4600 (Intel Corporation) - Driver: 20.19.15.4835 |
| Memory       | 8GB                                                                   |
└──────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 120.0.2210.77 |
| Nodejs     | N/A          | Installed | 18.14.0       |
| npm        | N/A          | Installed | 9.8.1         |
| *upx       | N/A          | Installed | upx 4.0.2     |
| *nsis      | N/A          | Installed | v3.08         |
└─────────────── * - Optional Dependency ───────────────┘

# Diagnosis
 SUCCESS  Your system is ready for Wails development!

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment] 2023-12-19 12:41
This has been covered multiple times in the issue tracker.

**Comment by PylotLight** [comment] 2023-12-19 13:01
Hey @Francisundermoon try reviewing this one in the meantime, but I imagine this will be closed for now.
https://github.com/wailsapp/wails/issues/2367

**Comment by Francisundermoon** [comment] 2023-12-19 13:55
> Has this worked previously for you, but suddenly stopped working? Obviously, I can't replicate this and will likely be something with your environment, does your D drive path have correct permissions set?
> 
> Separately, I wonder if doctor should include user level permissions on relevant folders, if that would be helpful to pickup possible access issues or something.

this error occur randomly when i tried to excute "wails dev"，only a few times  it works fine,but the command wails build always run normal

**Comment by stffabi** [comment] 2023-12-19 13:58
Thanks for using Wails and reporting this.

This seems to be a duplicate of https://github.com/wailsapp/wails/issues/2367 please feel free to join the issue over there. 

There's also a workaround mentioned over there: https://github.com/wailsapp/wails/issues/2367#issuecomment-1627866907

**Comment by stffabi** [comment] 2023-12-19 13:59
Duplicate of #2367

**Closed by stffabi** 2023-12-19 13:59 UTC
Labels: Bug, v3
