### ISSUE TITLE
 OnBeforeClose called twice when the window is about to be closed(introduced in v2.3.1)

### ISSUE THREAD

**Issue by zimolab** [wailsapp/wails#2265] opened 2022-12-31 19:00 UTC
### Description

The 'OnBeforeClose' handler will be called twice if you close the window.  This bug is introduced in v2.3.1 i think.

### To Reproduce

1. use latest wails cli to create a project
2. main.go
```go
package main

import (
	"embed"

	"github.com/wailsapp/wails/v2"
	"github.com/wailsapp/wails/v2/pkg/options"
	"github.com/wailsapp/wails/v2/pkg/options/assetserver"
)

//go:embed all:frontend/dist
var assets embed.FS

func main() {
	// Create an instance of the app structure
	app := NewApp()

	// Create application with options
	err := wails.Run(&options.App{
		Title:  "wails-2.3.1-bug",
		Width:  1024,
		Height: 768,
		AssetServer: &assetserver.Options{
			Assets: assets,
		},
		BackgroundColour: &options.RGBA{R: 27, G: 38, B: 54, A: 1},
		OnStartup:        app.startup,
		OnBeforeClose:    app.beforeClose,
		Bind: []interface{}{
			app,
		},
	})

	if err != nil {
		println("Error:", err.Error())
	}
}
```
3. app.go
```go
package main

import (
	"context"
	"fmt"
)

// App struct
type App struct {
	ctx context.Context
}

// NewApp creates a new App application struct
func NewApp() *App {
	return &App{}
}

// startup is called when the app starts. The context is saved
// so we can call the runtime methods
func (a *App) startup(ctx context.Context) {
	a.ctx = ctx
}

// this will called twice every time you close the window
func (a *App) beforeClose(context.Context) bool {
	fmt.Println("beforeClose")
	return false
}

// Greet returns a greeting for the given name
func (a *App) Greet(name string) string {
	return fmt.Sprintf("Hello %s, It's show time!", name)
}
```
4. wails dev
5. close the window
6. the output info in the console
```
......
To develop in the browser and call your bound Go methods from Javascript, navigate to: http://localhost:34115
beforeClose
beforeClose
Development mode exited
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Expected behaviour

i think the OnBeforeClose handler should be called only once.

### System Details

```shell
# System

OS           | Windows 10 Pro     
Version      | 2009 (Build: 19044)
ID           | 21H2
Go Version   | go1.19.4
Platform     | windows
Architecture | amd64

# Wails

Version | v2.3.1

# Dependencies

Dependency | Package Name | Status    | Version      
WebView2   | N/A          | Installed | 108.0.1462.54
npm        | N/A          | Installed | 8.1.0
*upx       | N/A          | Available | 
*nsis      | N/A          | Available | 
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment] 2022-12-31 21:26
Thanks for reporting this and providing such a detailed report 👍 Will investigate.

**Comment by stffabi** [comment] 2022-12-31 22:39
It's caused by the `a.Quit()` here:

https://github.com/wailsapp/wails/blob/d3b4105f7598ba51501541ebd4ee564ca75a70c6/v2/pkg/application/application.go#L80-L82

**Comment by sebastian0x62** [comment] 2023-01-24 22:06
> It's caused by the `a.Quit()` here:
> 
> https://github.com/wailsapp/wails/blob/d3b4105f7598ba51501541ebd4ee564ca75a70c6/v2/pkg/application/application.go#L80-L82

Looks like this was introduced because of the systray handling. 🤔

**Comment by sebastian0x62** [comment] 2023-01-24 22:13
```Go
// Quit will shut down the application
func (a *Application) Quit() {
	a.shutdown.Do(func() {
		for _, systray := range a.systemTrays {
			systray.Close()
		}
		a.application.Shutdown()
	})
}
```

What's about a second function `CloseSystrays()`, which will be called after application.Run() instead. Should also be save when called multiple times, without the `sync.Once`.

**Comment by leaanthony** [comment] 2023-01-25 10:04
I'm happy to remove it completely. Systrays aren't supported in v2 anyway

**Comment by sebastian0x62** [comment] 2023-01-25 10:28
😅 I actually was wondering, if there is this hidden feature already.

My PR would work at least for this issue. Whatever you prefer.

**Comment by leaanthony** [comment] 2023-01-25 19:16
I think it should be removed. I'm happy to do that though if you don't have time

**Comment by sebastian0x62** [comment] 2023-01-25 20:31
@leaanthony Removed all about systray from /v2. Hope that's not too much now. 🙈

**Comment by stffabi** [comment] 2023-02-12 10:18
This issue has been fixed on master.

Please feel free to reopen if you see any further issues with this.

**Closed by stffabi** 2023-02-12 10:18 UTC
Labels: Bug, v2
