### ISSUE TITLE
Wails dev/build very slow on Windows compared to MacOS/Linux

### ISSUE THREAD

**Issue by apressas** [wailsapp/wails#2545] opened 2023-03-31 15:55 UTC
### Description

Basically what the title says, go mod tidy takes longer, as does everything else, so the development loop is very very slow compared to Linux or MacOS.

### To Reproduce

Build your app on Windows

### Expected behaviour

Build time should be similar or at least much less than it is on Windows.

### System Details

```shell
WebView2   | N/A          | Installed | 111.0.1661.54
npm        | N/A          | Installed | 9.5.0
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/
```

**Comment by leaanthony** [comment] 2023-03-31 21:40
What have you tried so far to determine the slowness on your machine as I don't see this on mine?

**Comment by apressas** [comment] 2023-04-09 13:08
I upgraded to version 2.4.1 and the build time has dropped to 35ms from over a minute!
But I still wouldn't consider this super fast. What is a normal build time for dev/build for you gus?

**Comment by apressas** [comment] 2023-04-09 14:23
No idea why I wrote ms, I meant seconds! And that's every time, even with no changes in the Go code.

**Comment by leaanthony** [comment] 2023-05-21 08:07
Where is the time going? frontend? Go compilation. It's very fast on my Windows machine so can't reproduce.

**Comment by apressas** [comment] 2023-05-25 21:28
Well I set it up on two different machines, with a clean Go installation and the same things happens. The build on my Macbook completes in seconds and the Windows machines both take over 2 minutes. The majority of time is spent on go mod tidy, which I assume builds the front end every time? That is with no changes in the code whatsoever.

**Comment by leaanthony** [comment] 2023-05-25 22:20
That's really weird. `go mod tidy` simply ensures your local go modules are installed and up to date, a little like `npm install`. There's the potential for that to be slow the first time and fast on subsequent builds. All we can do is see if someone else can reproduce this because I can't.

**Comment by apressas** [comment] 2023-05-26 08:44
Actually the generating bindings-compiling front end steps of go mod tidy take the longest. And then compiling the application. And it happens every time, even without changing code in the front or back end. What is a range for normal build times in seconds given modern Intel processors you'ld think?

**Comment by glitchedgitz** [comment] 2023-05-26 13:54
It is slow for me too. It takes 10+ seconds each time, windows 11, 24gb ram, ryzen 5.

Even with the base project `wails init -n myproject -t svelte`

**Comment by leaanthony** [comment] 2023-05-27 02:35
The reason I'm surprised is because Windows doesn't need CGO so it's as fast as standard Go compilation (which is famously fast). Try `-skipbindings` flag. I've just realised that it was never added to the docs...

**Comment by leaanthony** [comment] 2023-05-27 02:49
Docs updated: https://wails.io/docs/next/reference/cli

**Comment by apressas** [comment] 2023-05-27 21:50
Skipbindings did nothing. -s on the other hand sped it up by a lot but even the building steps that remain take longer than the time the mac does to build the entire thing.

**Comment by glitchedgitz** [comment] 2023-05-27 22:26
For me `-skipbindings` time decrease from ~10s to ~ 6s, but no effects with `-s`. And 6 seconds is still a lot.

Btw my current approach is different to use wails because dev time was too much. As I was using pocketbase, I made all the functions to work as endpoint, so it covers the gap that wails for doing for me with obviously adding an unnecessary tasks of bindings. But this method its a lot easier to test changes and only update the frontend/backend as required.

Now when it will be time to serve the application, I will merge them together and serve it.

**Comment by apressas** [comment] 2023-05-28 10:50
I didn't quite understand your solution, seems like you're not using Wails at all now, but good to know there's another way of doing it. Also running a Linux VM and building Wails apps there is much much faster than native Windows compilation. But it seems it's just not the right time to be using it for professional-grade applications.

**Comment by roachadam** [comment] 2023-06-03 04:14
I also have this issue. Build takes forever on windows, with majority of time being go mod tidy and react compiling.
Mac it is significantly faster alltogether, at least a half or even a third of the build time (build normal and dev)

**Comment by leaanthony** [comment] 2023-06-03 05:32
How would you speed up `go mod tidy` or react compiling?

**Comment by glitchedgitz** [comment] 2023-06-03 06:31
@leaanthony Consider my partial knowledge and let's assume if you can divide the things like this.

- **Core** - The webview and other core things. (That needs to boot up mostly only at once)
- **Frontend** - React/Svelte etc
- **Backend** - Golang Functions that the frontend will use.

Now if I change the backend, it doesn't need to rebuild the core/frontend, that should save time.
it will just update the binding files and the frontend framework auto-update itself when files change.

As RPC is a REST alternative, the above solution might be possible. This is similar to my current approach. 

> Btw my current approach is different to use wails because dev time was too much. As I was using pocketbase, I made all the functions to work as endpoint, so it covers the gap that wails for doing for me with obviously adding an unnecessary tasks of bindings. But this method its a lot easier to test changes and only update the frontend/backend as required.

**Comment by leaanthony** [comment] 2023-06-03 07:17
> Now if I change the backend, it doesn't need to rebuild the core/frontend, that should save time.

How can we easily detect that? The good news is that in v3 we are utilising [Task](https://taskfile.dev) to do just this but maybe you can speed things up by doing [manual builds](https://wails.io/docs/guides/manual-builds) rather than use dev? I'm also still unclear as to why this might be slower on Windows than say mac

**Comment by glitchedgitz** [comment] 2023-06-03 09:30
> The good news is that in v3 we are utilising [Task](https://taskfile.dev/) to do just this

Awesome!

> How can we easily detect that?

You currently have that implemented I guess. If I change `/backend` directory, just rebuild the backend and analyse if binding does need to change or not.

**Comment by glitchedgitz** [comment] 2023-06-03 10:10
> maybe you can speed things up by doing [manual builds](https://wails.io/docs/guides/manual-builds) rather than use dev

Yeah! `wails build` is faster...🤔

**Comment by haroflow** [comment] 2023-06-23 22:14
I started using Wails today, and it was taking ~30s to reload changes on app.go...

Just noticed that `MsMpEng.exe` (Windows Defender) starts running when I save `app.go`... after deactivating it, went from ~30s to ~8s. Still not ideal, but it helps...

Other info:
Windows 10
Wails CLI v2.5.1
WebView2 114.0.1823.51
Nodejs 16.13.2
npm 8.1.2
Template: https://github.com/mateothegreat/wails-template-angular

**Comment by leaanthony** [comment] 2023-06-24 02:31
Ah, that may well be the issue!

**Comment by mmghv** [comment] 2023-06-24 03:45
> Just noticed that MsMpEng.exe (Windows Defender) starts running when I save app.go... after deactivating it, went from ~30s to ~8s. Still not ideal, but it helps...

I can confirm, `build` went down from ~60s to 10s, and `dev` from 33s to to 22s

Although I didn't disabled Windows Defender, I just added `go` process to the exclusion list :
`Windows Defender` > `Exclusions` > `Add an exclusion` > `Process` > `C:\Program Files\Go\bin\go.exe`
And while I'm at it I added VSCode and Node.

Note : It's important to add the exclusion as a `Process` and not a `File` so it excludes any child process that Go spawns, adding it as a file/folder exclusion didn't give the same results.

_DISCLAIMER : DO IT AT YOUR OWN RISK_

**Comment by leaanthony** [comment] 2024-11-23 11:50
This issue is due to Windows defender and there are workarounds in the issue thread. Closing.

**Closed by leaanthony** 2024-11-23 11:50 UTC
Labels: Bug, cannot reproduce, v3
