### ISSUE TITLE
Linux Wails app exits if $DISPLAY not set or valid instead of returning error.

### ISSUE THREAD

**Issue by steely-glint** [wailsapp/wails#2628] opened 2023-04-27 09:28 UTC
### Description

Wails on Linux quits if $DISPLAY is not set before running the first line of main()

We'd like to be able to take a fallback action (e.g. offer a cli with prompt - or just a customised warning )

### To Reproduce

1. wails init -n nodisplay -t vanilla
2.  cd nodisplay/
3. wails build
4. unset DISPLAY
5. ./build/bin/nodisplay 

### Expected behaviour

I expected 
                println("Error:", err.Error())
to be reached.

### Screenshots

nodisplay$ ./build/bin/nodisplay 
Unable to init server: Could not connect: Connection refused

(nodisplay:43810): Gtk-WARNING **: 10:16:58.531: cannot open display: 

### Attempted Fixes

I added a fmt.print() to the first line of main() - it is never called.
I tried to find where 
`Unable to init server: Could not connect: Connection refused`
is printed - I failed to find it.
We asked for advice on Discord.

### System Details

```shell
nodisplay$ wails doctor
Wails CLI v2.4.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Debian GNU/Linux
Version      | 11              
ID           | debian          
Go Version   | go1.19.1        
Platform     | linux           
Architecture | amd64           

# Wails

Version         | v2.4.1
Package Manager | apt   

# Dependencies

Dependency | Package Name          | Status    | Version                
*docker    | docker.io             | Available | 20.10.5+dfsg1-1+deb11u2
gcc        | build-essential       | Installed | 10.2.1                 
libgtk-3   | libgtk-3-dev          | Installed | 3.24.24-4+deb11u2      
libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.38.5-1~deb11u1       
npm        | npm                   | Installed | 9.5.1                  
*nsis      | nsis                  | Available | 3.06.1-1               
pkg-config | pkg-config            | Installed | 0.29.2                 
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details: 
  - docker: sudo apt install docker.io
  - nsis: sudo apt install nsis

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

I understand that without a display wails can't function - but I do feel that an app should be given a chance to report, log, perhaps even fix or work around the error itself rather than the whole app bailing.

Our app is a service with status display - the display is the least important part!

**Comment by stffabi** [comment] 2023-04-27 09:59
Thanks for using Wails and reporting this issue.

I suspect it's caused by the `gtk_init` in a `init()` here:
https://github.com/wailsapp/wails/blob/d249c2207bc7ab302c8f6d4a5941795d69ae39dd/v2/internal/frontend/desktop/linux/frontend.go#L127-L136

This was more of a mistake to have this moved into `init()` we should really not require this until we really need gtk to be initialised.
Would it be possible for you to test moving this, e.g. into `NewFrontend` and possibly provide a PR for that?

**Comment by steely-glint** [comment] 2023-04-27 14:30
PR added  https://github.com/wailsapp/wails/pull/2629

**Comment by phildrip** [comment] 2023-08-23 11:28
> Thanks for using Wails and reporting this issue.
> 
> I suspect it's caused by the `gtk_init` in a `init()` here:
> 
> https://github.com/wailsapp/wails/blob/d249c2207bc7ab302c8f6d4a5941795d69ae39dd/v2/internal/frontend/desktop/linux/frontend.go#L127-L136
> 
> This was more of a mistake to have this moved into `init()` we should really not require this until we really need gtk to be initialised. Would it be possible for you to test moving this, e.g. into `NewFrontend` and possibly provide a PR for that?

Thanks to @steely-glint for the original change - I've made another PR with your suggestion @stffabi. #2841

**Closed** 2023-08-25 20:41 UTC
Labels: Bug, v2
