### ISSUE TITLE
Flag redefinition in dev mode

### ISSUE THREAD

**Issue by NanoNik** [wailsapp/wails#1502] opened 2022-06-27 22:36 UTC
### Description

After closing wails window, if you try to launch it a second time in the same process,  it will panic with `flag redefined: assetdir`.
This happens only in dev mode here:

https://github.com/wailsapp/wails/blob/95082336cda006652ca63156275109987acdfb10/v2/internal/appng/app_dev.go#L76-L92

### To Reproduce

1. Launch a wails app in wails dev
2. Shutdown app using `runtime.Quit`
3. Call wails.Run again in the same process

### Expected behaviour

Application should check if flag already assigned using `flag.Lookup` and not reassign it.

### System Details

```shell
System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 22000)
ID:             21H2
Go Version:     go1.19beta1
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.37
Revision:       119e6571755b6cb8980838671729f7bb7f5127be
Modified:       true

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       103.0.1264.37
npm             N/A             Installed       8.11.0
*upx            N/A             Available
*nsis           N/A             Available
```

**Comment by leaanthony** [comment] 2022-06-28 22:05
When you call the runtime `Quit` method, Wails will start shutting down and cleaning up resources so this doesn't surprise me. What's the use case for calling `Quit` then `Run`? This is not really a bug and expected behaviour?

**Comment by NanoNik** [comment] 2022-06-28 22:27
> What's the use case for calling `Quit` then `Run`?

In my case, after some actions UI process will die and application will work in the background, after clicking tray icon - UI starts again. Most of the consumed RAM goes to WebView2, so I want to shut it down when the application does background work.

**Comment by NanoNik** [comment] 2022-06-28 23:39
I search through documentation, I think it is possible to use (TrySuspend)[https://docs.microsoft.com/ru-ru/microsoft-edge/webview2/reference/win32/icorewebview2_3?view=webview2-1.0.864.35#trysuspend] API to achieve somehow similar result. It will lower CPU & RAM usage for invisible window. Is it possible to expose this API or invoke it inside `WindowHide`

**Comment by leaanthony** [comment] 2022-06-29 08:16
It sounds like you need to use `WindowHide`. We might look at TrySuspend after v2

**Comment by leaanthony** [comment] 2022-06-29 09:22
If you think `TrySuspend` is worth adding, let's open a different ticket for that and close this. This ticket is not a bug so should be closed 👍

**Closed** 2022-07-08 06:10 UTC
Labels: Bug, awaiting feedback, v2
