### ISSUE TITLE
cc1.exe: 64-bit mode not compiled in (what?)

### ISSUE THREAD

**Issue by pedzed** [wailsapp/wails#168] opened 2019-07-24 08:32 UTC
**Description**
```bash
$ wails build
Wails v0.17.0 - Building Application

> Skipped frontend dependencies (-f to force rebuild)
> Building frontend...
\ Ensuring Dependencies are up to date...# github.com/wailsapp/webview
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

! Ensuring Dependencies are up to date...
Error: exit status 2
```

```bash
$ wails serve
Wails v0.17.0 - Serving Application

> Installing Mewn asset packer...
\ Ensuring Dependencies are up to date...# github.com/wailsapp/webview
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

! Ensuring Dependencies are up to date...
Error: exit status 2
```

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.0 |
| Go Version    | go1.12.7 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |

**Comment by leaanthony** [comment] 2019-07-24 08:35
This will depend on what version of GCC you installed

**Comment by pedzed** [comment] 2019-07-24 08:38
What should I be looking for?

```bash
$ gcc --version
gcc.exe (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

If it is an option, I prefer using clang.
```bash
$ clang --version
clang version 8.0.0 (tags/RELEASE_800/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

**Comment by leaanthony** [comment] 2019-07-24 08:54
Looks like it's calling the MSC compiler? Isn't that CC1?

**Comment by pedzed** [comment] 2019-07-24 14:05
```bash
$ gcc -print-prog-name=cc1
C:/mingw32/bin/../libexec/gcc/i686-w64-mingw32/7.3.0/cc1.exe
```
There seems to be a problem with it being 32-bit (based on the error "cc1.exe: sorry, unimplemented: 64-bit mode not compiled").

Perhaps I need to install MinGW64, but if I do that, where do I need to configure it that it will be used (while preferably keeping MinGW32)? It seems odd to me that Wails expects a 64-bit version.

Perhaps a bit related: https://unix.stackexchange.com/questions/77779/relationship-between-cc1-and-gcc

**Comment by leaanthony** [comment] 2019-07-25 11:05
I use the one in the doves and it worked well: https://wails.app/quick_start.html#windows

**Comment by leaanthony** [comment] 2019-08-18 23:03
@pedzed is this still an issue for you?

**Comment by pedzed** [comment] 2019-08-19 04:45
Yes, actually it is. I haven't really used Wails since, but I'm still interested.

**Comment by leaanthony** [comment] 2019-08-31 01:39
Thanks for the update. As I'm unable to reproduce this, I'm closing it as it seems it could be a local environment issue. If you feel.it needs to be reopened,  please do so. Thanks.

**Closed by leaanthony** 2019-08-31 01:39 UTC
Labels: Enhancement, awaiting feedback, v3
