### ISSUE TITLE
linux getting started wails build style.css problem

### ISSUE THREAD

**Issue by march1993** [wailsapp/wails#2825] opened 2023-08-16 10:33 UTC
### Description

/src/style.css is not handled correctly.
system: latest debian12
wails: latest

![image](https://github.com/wailsapp/wails/assets/5122675/101940e5-4d21-4d11-ae0e-b60135227bb8)

### To Reproduce

Run the commands in the getting started documentation.

### Expected behaviour

UI elements should in window center.

### System Details

```shell
$ wails doctor
Wails CLI v2.5.1

 SUCCESS  Done.                                                                 

# System

OS           | Debian GNU/Linux
Version      | 12              
ID           | debian          
Go Version   | go1.21.0        
Platform     | linux           
Architecture | amd64           

# Wails

Version         | v2.5.1
Package Manager | apt   

# Dependencies

Dependency | Package Name          | Status    | Version            
*docker    | docker.io             | Installed | 20.10.24+dfsg1-1+b3
gcc        | build-essential       | Installed | 12.9               
libgtk-3   | libgtk-3-dev          | Installed | 3.24.37-2          
libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.40.5-1~deb12u1   
npm        | npm                   | Installed | 9.2.0~ds1-1        
*nsis      | nsis                  | Available | 3.08-3             
pkg-config | pkg-config            | Installed | 1.8.1              
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details: 
  - nsis: sudo apt install nsis

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by stffabi** [comment] 2023-08-21 05:47
Thanks for using Wails and opening this.

This is a duplicate of #2705 and is already fixed on master.

**Comment by stffabi** [comment] 2023-08-21 05:47
Dupliate of #2705

**Closed by stffabi** 2023-08-21 05:47 UTC
Labels: Bug, v2
