### ISSUE TITLE
Wails with plain HTML/CSS/Js

### ISSUE THREAD

**Issue by bugdiver** [wailsapp/wails#170] opened 2019-07-26 08:24 UTC
Can we use wails with plain HTML CSS and js without using any framework?
We have a requirement where we want to create a small GUI app in golang but we do not want to use any framework like (Vue or React).
Most of the frameworks build static files which get used by wails so I think it should be possible.
Have anyone tried this sort of thing?
Any help would be appreciated

**Comment by bh90210** [comment] 2019-07-26 11:42
yes it is 100% possible! 
for now I am not aware of any implementation being done this way to direct you I'm afraid. 

but maybe it is worth writing a small tutorial around this method @leaanthony ? seems arbitrarily easy..

**Comment by leaanthony** [comment] 2019-07-26 12:37
We used to support this but dropped it. Wails supports anything that essentially builds to a single CSS and js file. The default HTML has a single div with an ID of app. The only thing wails does is call an install script and a build script, eg npm install and npm run build.
If you give us an example HTML file and js/js, we can look at what a base template looks like.

**Comment by leaanthony** [comment] 2019-07-26 22:44
What we could do is a basic HTML/CSS webpack template. That shouldn't be a problem at all.

**Comment by leaanthony** [comment] 2019-07-30 22:51
I've looked at this in depth and it *is* possible, but it's wildly different depending on how you want to do it. Essentially wails needs a js + css bundle. Generally, the JS will deal with mounting components, dom updates, scoping of javascript functions and CSS. Doing that manually is pretty difficult. 

So yes, it *is* possible, but it's very subjective on how you want to do it. The only thing you need to know from a Wails perspective is this:

- The default HTML has a single div with an id of `app`. Ensure your html hangs off this. If you replace the whole document, I can't guarantee the runtime will still function correctly - YMMV.
- Make sure your bundles are completely standalone - no external references (unless you don't mind it trying to retrieve them at runtime). This means images, fonts, etc should be inlined with datauris. Webpack does this for you with the right loaders. Check the other template configurations.
- CSS should be bundled in the same way into its own file

If you can provide more information on your specific needs, then I'll keep this ticket open.

**Comment by BugDiver** [comment] 2019-07-31 05:00
@leaanthony Thanks for giving the pointers. I think it would help me a lot to get started.

> If you can provide more information on your specific needs, 

We do not have specific needs. We just wanted to create a GUI with Golang (let's say a POC), and not to use React or Vue for starting.

I think if there is a template (same as react and vue) for plain HTML (with webpack), it would help others if they do not want to use any web frameworks.

Thanks again for all the efforts.

**Comment by leaanthony** [comment] 2019-07-31 11:24
So, then that depends on how you want to write your apps. I can get an example working where you have a global object on window which had your app logic and HTML calls those... I will make a branch. If you are a webpacker then I could do with your help.

**Comment by Vaelatern** [comment] 2019-08-25 12:44
I want to say this is also something I want to do. No tools, just give wails css, html, and javascript.

**Comment by bh90210** [comment] 2019-08-25 13:11
actually @leaanthony was working on something and I have plans to work on a different solution. ATM I am working on getting [nuxt](https://github.com/bh90210/nuxt) working, and I need some help as I am stuck, but if you are interested we could start an open collab on getting this done (or if you have an idea you can implement alone open a solo PR..)

**Comment by leaanthony** [comment] 2019-09-03 22:52
@BugDiver I've not forgotten about this. The issue is, most frameworks have a start point where you mount the app. In plain html/js/css you don't get this by default. Why does that matter? Because you need to wait until Wails runtime loads to be able to do any of the things you may want to do. You would still need to adhere to that for it to work. I have an idea on a way that may work and am looking to get that into v1.0.0.

**Comment by leaanthony** [comment] 2019-10-02 06:58
This has not had the attention it deserves so I'm pushing it post V1. Closing for now and listing on the https://github.com/wailsapp/wails/wiki/Post-V1-Enhancements page

**Closed by leaanthony** 2019-10-02 06:58 UTC
Labels: Enhancement, v3
