### ISSUE TITLE
wailsbindings.exe: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by dingdinglz** [wailsapp/wails#2679] opened 2023-05-20 12:47 UTC
### Description

When I want to use `wails dev` , a error fork/exec C:\Users\dlz\AppData\Local\Temp\wailsbindings.exe: %1 is not a valid Win32 application.

### To Reproduce

1.open CMD
2.wails dev
3.this error open

### Expected behaviour

Can not continue to Generating bindings and next step.

### Attempted Fixes

I clean the cache ,  uninstall and install again. But not work.

### System Details

```shell
# System

OS           | Windows 10 Home China
Version      | 2009 (Build: 25336)
ID           | 22H2
Go Version   | go1.19
Platform     | windows
Architecture | amd64
```
# Wails

Version | v2.4.1

**Comment by stffabi** [comment] 2023-07-10 20:41
Thanks for opening this.

This seems like a duplicate of https://github.com/wailsapp/wails/issues/2277 the OP there did upgrade go to 1.19.4 and the problem got resolved.

**Comment by leaanthony** [comment] 2023-07-10 20:56
I think we can add this to the troubleshooting guide.

**Comment by xiaotushaoxia** [comment] 2024-07-05 10:56
I locate the problem.  Before run `wails dev`, user should set GOOS and GOARCH right.  
For me, I develop using Windows, but I often change GOOS to build different binary files. When I set GOOS=linux and run `wails dev`, I get this error.
![image](https://github.com/wailsapp/wails/assets/34184824/a9b096b7-660b-4900-926e-865829bfc594)

By reading the source code, I think there's a better approach. I'll submit a PR.

@leaanthony @dingdinglz

**Comment by dingdinglz** [comment] 2024-07-05 14:07
> I locate the problem. Before run `wails dev`, user should set GOOS and GOARCH right.我找到了问题所在。在运行 `wails dev` 之前，用户应该设置GOOS和GOARCH的权限。 For me, I develop using Windows, but I often change GOOS to build different binary files. When I set GOOS=linux and run `wails dev`, I get this error.对我来说，我使用 Windows 进行开发，但我经常更改 GOOS 来构建不同的二进制文件。当我设置 GOOS=linux 并运行 `wails dev` 时，我收到此错误。 ![image](https://private-user-images.githubusercontent.com/34184824/346101293-a9b096b7-660b-4900-926e-865829bfc594.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxODg2OTUsIm5iZiI6MTcyMDE4ODM5NSwicGF0aCI6Ii8zNDE4NDgyNC8zNDYxMDEyOTMtYTliMDk2YjctNjYwYi00OTAwLTkyNmUtODY1ODI5YmZjNTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDE0MDYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZTRiNTBiYWQzNWUxMTM2YzMyYzBhNDkzY2YyNDc3OWIxM2RmODY1MzI1M2ExYWE0NmNmZDY1OTFkMGViMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MTNYDx87642uZXTz7okiXk5ouWDmZq5qpXqzNDtp7kM)
> 
> Although we can avoid errors by setting the correct GOOS and GOARCH before running wails dev,but I think there's a better approach. I'll submit a PR.虽然我们可以通过在运行 wails dev 之前设置正确的 GOOS 和 GOARCH 来避免错误，但我认为有更好的方法。我会提交一个 PR。
> 
> @leaanthony @dingdinglz

Thank you for your help!

**Closed** 2024-07-05 14:07 UTC
Labels: Bug, Workaround Available, Add to Documentation, v2
