### ISSUE TITLE
Add the ability to define a prefix/suffix to the generated class models

### ISSUE THREAD

**Issue by Goncalo-Marques** [wailsapp/wails#2058] opened 2022-11-06 21:19 UTC
### Is your feature request related to a problem? Please describe.

I am having some problems with my generated models.

Basically, I have a Go method that should return a slice of a structure named `Object`:
```go
type Object struct {}

type App struct {
	ctx context.Context
}

func (a *App) MyMethod() []Object {
	return nil
}
```

Then, after running `wails generate module`, I get the error (`wailsjs/go/models.ts`): `error TS2339: Property 'keys' does not exist on type 'typeof Object'`.

Generated code for context (focus on line 9):
```typescript
convertValues(a: any, classs: any, asMap: boolean = false): any {
	if (!a) {
		return a;
	}
	if (a.slice) {
		return (a as any[]).map(elem => this.convertValues(elem, classs));
	} else if ("object" === typeof a) {
		if (asMap) {
		     for (const key of Object.keys(a)) {
		         a[key] = new classs(a[key]);
		      }
		      return a;
		  }
		  return new classs(a);
	}
	return a;
}
```

This is happening because the JavaScript [Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object) is being "confused" with my generated class also named `Object`.
It is possible that this could happen to every Go structure that as a similar name to the [built-in objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects) in JavaScript.

### Describe the solution you'd like

Instead of restricting the names we give to Go structures, we can solve this problem by:
- Adding two new flags to `wails generate module` 
   - `-prefix` (Prefix added to the generated class models)
   - `-suffix` (Suffix added to the generated class models)
- The zero values of `-prefix` and `-suffix` should work like the zero value of the string in Go
- The Pascal Case should be considered to keep consistency

#### Notes:
- We shouldn't forget to update [docs](https://wails.io/docs/reference/cli#module)
- The flags could be renamed to make them clearer

### Example

Generating wailsjs:
```bash
wails generate module -prefix myPrefixwithmultiplewords
```

"Pseudocode" to generate the class name:
```go
func generateClassName(prefix, suffix string) string {
   structNameGo := "Object"

   if len(prefix) != 0 {
      prefix = strings.Title(prefix)
   }
   if len(suffix) != 0 {
      suffix = strings.Title(suffix)
   }

   return prefix + structNameGo + suffix 
}
```

Result:
```javascript
class MyPrefixwithmultiplewordsObject {
}
```

### Describe alternatives you've considered

An alternative would be to rename my Go structures in order to avoid conflicts with the generated code.
However, this solution becomes unfeasible when using third-party code where we do not control the name of the defined structures.

### Additional context

Check this discussion for additional information: https://github.com/wailsapp/wails/discussions/1982

**Comment by OlegGulevskyy** [comment] 2022-11-12 22:20
Did you plan to implement a PR for this issue @Goncalo-Marques ? If not, I'd like to take a crack at this one to get some intro to the codebase

**Comment by Goncalo-Marques** [comment] 2022-11-12 23:50
@OlegGulevskyy, feel free to create a PR for this issue 👍

**Comment by OlegGulevskyy** [comment] 2022-11-13 13:23
I took a look at this today and here is my process of thinking:
- first of and that's more of a note for me as newbie here, I can't reproduce the issue if I follow directly the code snippet, because `wails generate module` [does not do anything if structs fields are not annotated](https://github.com/wailsapp/wails/issues/1365). But this is not really relevant, just clarifying.
- I've read the [discussion](https://github.com/wailsapp/wails/discussions/1982) and saw that there were 2 main ways to fix this suggested
1. Avoid conflicts in naming.
2. Generate alternate names at runtime

As @leaanthony  said, point 1 would be easier to deal with but we need to update the tooling to warn, and point 2 adds confusion, hence it was suggested to add prefixes / postfixes.
My main concern with adding postfixes and prefixes is that to a new developer out of the context, it is not obvious what those prefixes and postfixes are and why'd they use them, unless they see weird broken `models` file and dig a little.

It is possible to easily avoid the naming clash by wrapping your return response into something. Please consider this:
```go
type Response struct {
	Object
}
type Object struct{
	id string `json:"id"`
}

// Greet returns a greeting for the given name
func (a *App) Greet(name string) []Response {
	return nil
}
```

Which results in a perfectly normal model:
```ts
export namespace main {
	
	export class Response {
	    id: string;
	
	    static createFrom(source: any = {}) {
	        return new Response(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.id = source["id"];
	    }
	}

}
```
![image](https://user-images.githubusercontent.com/43781031/201517108-306194d0-b5fb-4035-bc0a-5cece910624d.png)

With this in mind, what if instead we consider another 3rd path - have a list of predefined object names, update the tooling, whenever `wails generate models` is run, if such name is detected in use, warn the user in the output and recommend wrapping them in a struct like showed above.
Some thing like that? (minus debug logs)
<img width="829" alt="image" src="https://user-images.githubusercontent.com/43781031/201523908-f4038e8e-4287-4e9b-8f52-10922c4743fb.png">


I think it's less intrusive in regards to the final output + more instant feedback with a suggested way to fix.

I am still happy to implement said request, just wanna hear your thoughts on this.

**Comment by Goncalo-Marques** [comment] 2022-11-13 15:17
> My main concern with adding postfixes and prefixes is that to a new developer out of the context, it is not obvious what those prefixes and postfixes are and why'd they use them, unless they see weird broken models file and dig a little.

I do not agree with this statement because the default behavior would not affect any developer. To affect your generated code, you need to explicitly define a prefix/suffix. 
In this case, we are just adding the option/ability to generate code with a custom pattern. And this do not even need to be related with the issue itself. The developer could simply want to have a custom format to the generated code.
I don't see this being intrusive at all.

I do not think that prefixes/suffixes are that uncommon in generated code and the documentation would clarify any doubts.
Anyway, I think that the warning is a **must**, regardless of the outcome of our discussion.

> It is possible to easily avoid the naming clash by wrapping your return response into something.

I do not find that solution as straightforward as it sounds.
Imagine this scenario, there is no way to rename conflicting structures because you are using third party code to build your application. Considering the code below, how would you wrap `MyStruct`? The "keyword" Object would still be a problem here.

```go
package thirdParty

type Object struct {}

type MyStruct struct{
   id  string
   obj Object
}
```

@leaanthony, any thoughts on our discussion?

_ps: English is not my mother tongue, I really do not want to sound rude at all 😅_

**Comment by leaanthony** [comment] 2022-11-13 19:13
Thanks for looking at this @OlegGulevskyy! I think a great test case would be:

```
type MyStruct struct {
   Class string `json:"class"`
}
```

In this scenario the generated code will be invalid. I guess the expected behaviour would be that it fails to generate code with an error stating that the use of reserved keywords is unsupported and to set a prefix using `-,tsprefix` flag or rename the variable.

**Comment by OlegGulevskyy** [comment] 2022-11-14 09:09
This makes sense, thanks to both of you @leaanthony @Goncalo-Marques 
I will focus on it then

**Comment by stffabi** [comment] 2022-11-24 11:48
PR has been merged.

**Comment by Goncalo-Marques** [comment] 2022-12-03 20:35
Hey 👋 (@leaanthony, @OlegGulevskyy, @stffabi)

First of all, thank you for adding this feature and solving my issue. 🙏 
Also, sorry for the late feedback, I have been a bit busy.

I was going to get back to my project (using wails) and "play" with the `ts_generation`, but I run into an issue that happens when I have a generated model that references another generated model.

## To make it clearer, I will try to reproduce my scenario here

Go structures to generate:
```go
type MyStruct struct {
  id string
  ref MyOtherStruct
}

type MyOtherStruct struct{
   id string
}
```

Wails.json:
```json
{
 "bindings": {
    "ts_generation": {
      "suffix": "Model"
    }
  }
}
```


### Expected generated models

```typescript
class MyStructModel {
   id: string;
   ref: MyOtherStructModel;
}

class MyOtherStruct Model {
   id: string;
}
```

### Actual generated models

```typescript
class MyStructModel {
   id: string;
   ref: MyOtherStruct;
}

class MyOtherStruct Model {
   id: string;
}
```

Note that the reference class in `MyStructModel` is not the one containing the configured suffix. And, because of that, this leads to unknown types.
Should we reopen this issue?

Also, because I faced this problem, I thought: Do you think there are similar issues that could happen related to models generated with prefixes/sufixes?

**Comment by OlegGulevskyy** [comment] 2022-12-10 18:21
Nice one, thanks for catching this @Goncalo-Marques !
The PR for this specific case is ready, but it's in draft stage as I wanna spend a bit more time to test it in some other cases.
If you have any ideas about test cases, please do let me know :)

**Comment by Goncalo-Marques** [comment] 2022-12-10 19:00
Once again, thank you for your help.
I have another scenario where we need to add the prefix/suffix. I will mention it in your PR.

>If you have any ideas about test cases, please do let me know
I am really new to Wails so I can not really help much at the moment.
For now, it looks like a big black box to me 😅

**Comment by leaanthony** [comment] 2022-12-14 12:09
@Goncalo-Marques could you please test the linked PR and let us know how you get on? Thanks!

**Comment by Goncalo-Marques** [comment] 2022-12-14 18:29
@leaanthony @OlegGulevskyy I just tested the PR with my initial scenario and everything seems to be fine, both the generation of the models and the data passing from Golang to JavaScript 😄 
Amazing work!

**Comment by stffabi** [comment] 2022-12-30 19:25
I think we have finished all the work on this issue and it's released with `v2.3.0`. So I'm going to close this issue. Please feel free to reopen if there's anything that should pop up regarding this.

**Comment by Goncalo-Marques** [comment] 2022-12-30 19:28
@stffabi I do not think so 😅 
This PR stills open: https://github.com/wailsapp/wails/pull/2227

**Comment by stffabi** [comment] 2022-12-30 19:35
Oh sorry, thought that one has been merged. Then let's reopen it 😄

**Comment by sbshah97** [comment] 2024-01-06 16:26
Is this issue closed now since the PR is merged?

**Comment by Goncalo-Marques** [comment] 2024-01-12 19:27
I also think that this issue can be closed.

**Closed** 2024-01-12 20:31 UTC
Labels: Enhancement, TODO, Good First Issue, v3
