### ISSUE TITLE
How to create a transparent window

### ISSUE THREAD

**Issue by idun886** [wailsapp/wails#1952] opened 2022-10-10 09:19 UTC
i want create a transparent window wails,but I only implemented translucent 
![image](https://user-images.githubusercontent.com/85549893/194834488-3e408c1c-152e-43a1-b576-4a227d2abca8.png)

How to create a transparent window

this is my wails doctor
![image](https://user-images.githubusercontent.com/85549893/194834907-6e1a2021-025d-4114-838a-21a4d4a80c27.png)

**Comment by stffabi** [comment] 2022-10-10 09:49
Thanks for using Wails and creating this issue.

This is currently not possible, but there's already an issue for this #1296 and it's planned for v2.2. Closing this in favour of the existing issue.

Duplicate of #1296

**Comment by stffabi** [comment] 2022-10-10 09:50
Duplicate of #1296

**Closed** 2022-10-10 09:50 UTC
Labels: Enhancement, v3
