### ISSUE TITLE
wails dev -race -v 2 create (very deep) nested dir in build/bin

### ISSUE THREAD

**Issue by bokunodev** [wailsapp/wails#2100] opened 2022-11-16 10:57 UTC
### Description

wails dev -race -v 2 create (very deep) nested dir in build/bin

### To Reproduce

1. create wails project with `svelte+ts` template
2. run `wails dev -race -v 2`
3. change some go code to trigger wails to recompile the project
4. repeat step 3 few times

### Expected behaviour

only create one binary file in `build/bin`

### Screenshots

![image](https://user-images.githubusercontent.com/54968427/202053566-4182ffdd-638d-4e38-bec8-0e30cab78754.png)

### Attempted Fixes

i believe it have something todo with this line
https://github.com/wailsapp/wails/blob/18b2d315dda8f4abe6681b399479315f5092fc33/v2/pkg/commands/build/base.go#L276

### System Details

```shell
wails doctor output


System
------
OS:		Artix Linux
Version: 	Unknown
ID:		artix
Go Version:	go1.19.3
Platform:	linux
Architecture:	amd64

Wails
------
Version: 		v2.2.0
Package Manager: 	pacman

Dependency	Package Name	Status		Version
----------	------------	------		-------
*docker 	docker 		Available 	1:20.10.21-1
gcc 		gcc 		Installed 	12.2.0-1
libgtk-3 	gtk3 		Installed 	1:3.24.34+r156+g812b3930d0-1
libwebkit 	webkit2gtk 	Installed 	2.38.2-1
npm 		npm 		Installed 	8.19.3
pkg-config 	pkgconf 	Installed 	1.8.0-1
```

**Comment by OlegGulevskyy** [comment] 2022-11-16 19:03
I had the same issue once but didn't have time to repro it, nice catch!

**Comment by leaanthony** [comment] 2022-11-16 21:16
I wonder if this is a regression from the recent modularisation changes.

**Comment by OlegGulevskyy** [comment] 2022-11-16 21:23
I was checking this right now, and the results are weird
@bokunodev  is right, `compiledBinary` has this incorrect path when saving couple of times on `dev` mode.
But what's weird to me is that I don't see why it duplicates itself like this.

Here is me reproducing it and keeping track of those lines below
```go
	outputFile := b.OutputFilename(options)
	options.Logger.Println("APPDIR", appDir)
	options.Logger.Println("OUTPUTFILE", outputFile)

	compiledBinary := filepath.Join(appDir, outputFile)
	options.Logger.Println("COMPILED BINARY", compiledBinary)

```
initial `wails dev` logs
```
APPDIR !(EXTRA string=/Users/oleggulevskyy/Documents/dev/Wails-Svelte-TS/build/bin)
OUTPUTFILE !(EXTRA string=Wails-Svelte-TS-dev-darwin-arm64)
COMPILED BINARY !(EXTRA string=/Users/oleggulevskyy/Documents/dev/Wails-Svelte-TS/build/bin/Wails-Svelte-TS-dev-darwin-arm64)
Done.
```

Second save, triggers re-build
```
APPDIR !(EXTRA string=/Users/oleggulevskyy/Documents/dev/Wails-Svelte-TS/build/bin)
OUTPUTFILE !(EXTRA string=/build/bin/Wails-Svelte-TS-dev-darwin-arm64-dev-darwin-arm64)
COMPILED BINARY !(EXTRA string=/Users/oleggulevskyy/Documents/dev/Wails-Svelte-TS/build/bin/build/bin/Wails-Svelte-TS-dev-darwin-arm64-dev-darwin-arm64)
```
You can already see that log `COMPILED BINARY` has `buil/bin/build/bin` but, the 2 components used to compose this path are completely normal - `APPDIR` and `OUTPUTFILE` logs respectively. 
If I continue saving, it will stack on top of each other, but variables `appDir` and `outputFile` will remain ok

**Comment by stffabi** [comment] 2022-11-16 21:52
I think the culprit might be line 280 here, the prefix stripped there is wrong.

https://github.com/wailsapp/wails/blob/ec82739df1f461890aaa478d8eb84517a911546a/v2/pkg/commands/build/base.go#L275-L281

I think it should be.
```go
b.projectData.OutputFilename = outputFile
```

But I'm not sure we even need that line, maybe it can be removed altogether.

**Comment by OlegGulevskyy** [comment] 2022-11-16 21:58
> I think the culprit might be line 280 here, the prefix stripped there is wrong.
> 
> https://github.com/wailsapp/wails/blob/ec82739df1f461890aaa478d8eb84517a911546a/v2/pkg/commands/build/base.go#L275-L281
> 
> I think it should be.
> 
> ```go
> b.projectData.OutputFilename = outputFile
> ```
> 
> But I'm not sure we even need that line, maybe it can be removed altogether.

The issue is incoming from line 275, `outputFile` is prefixed with `/build/bin`, and then `/build/bin/build*`.
```go
 outputFile := b.OutputFilename(options) 
```
I noticed it on my logs after I pasted them here in the thread.
I am trying to track it down where it went wrong.
Essentiall here
```go
func (b *BaseBuilder) OutputFilename(options *Options) string {
...
		target := strings.TrimSuffix(b.projectData.OutputFilename, ".exe")
```

`b.projectData.OutputFilename` already receives wrong name with `build` prefixed
I was just curious to see where it's going wrong from, as it's somewhere early, when OutputFilename is defined in options

**Comment by stffabi** [comment] 2022-11-16 22:21
Yeah that's exactly whats happening due to line 280.

> b.projectData.OutputFilename already receives wrong name with build prefixed
 
Since `b.projectData` is used across several rebuilds, line 280 changes the value of `b.projectData.OutputFilename` to project path trimmed  `compiledBinary`. `compiledBinary` after trimming the project path, still contains `build/bin/mybinary`. So for the next build run `func (b *BaseBuilder) OutputFilename(options *Options) string {` will use `b.projectData.OutputFilename` which already has the `build/bin` prefix from the previous run.

**Comment by stffabi** [comment] 2022-11-16 22:23
So line 280 changes the state of `b.projectData` so that in the next build run line 275 will return an already prefixed name.

**Comment by OlegGulevskyy** [comment] 2022-11-16 22:30
> So line 280 changes the state of `b.projectData` so that in the next build run line 275 will return an already prefixed name.

Ah yes, you are totally right, I see! Makes me feel like a doggo chasing his own tail :D 
You are right, removing this line does not re-create folder anymore and seems like not bringing any issues with build / dev

I can create a PR if you need

**Comment by stffabi** [comment] 2022-11-16 22:34
Would be awesome if you could create a PR. And thanks so much for taking your time looking into this and investigating the issue 🙏

**Comment by stffabi** [comment] 2022-11-19 19:28
A fix for this has been merged. Thanks @OlegGulevskyy for working on the fix.

**Closed** 2022-11-19 19:28 UTC
Labels: Bug, v2
