### ISSUE TITLE
Screen goes blank and minimize and maximize on Windows

### ISSUE THREAD

**Issue by glitchedgitz** [wailsapp/wails#1941] opened 2022-10-07 07:47 UTC
### Description

The screen goes blank on minimizing and maximizing. I face this after updating to v2.

OS: Windows
UI: Svelte

### To Reproduce

Just minimize the screen from anywhere.

### Expected behaviour

Should not disappear.

### Screenshots

https://user-images.githubusercontent.com/58145476/194499940-db70f497-fd9f-4d7a-a123-d2ef2a8d7b56.mp4

### System Details

```shell
Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Home
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.19.1
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       106.0.1370.34
npm             N/A             Installed       8.11.0
*upx            N/A             Available
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Comment by stffabi** [comment] 2022-10-07 07:58
Thanks for using Wails and reporting this.

Unfortunately I'm unable to reproduce this with a new `wails init` project. Some questions to hopefully track this down.
- From what version did you upgrade?
- Can you try to upgrade one version after the other to see in which version this has been introduced?

**Comment by giteshnxtlvl** [comment] 2022-10-07 16:57
Thanks, @stffabi for the fast reply.
It doesn't happen every time. So it's hard to reproduce.
I upgraded to v2.0.0, from the previous 3 consecutive updates. So I am not sure where this begins.

**Comment by leaanthony** [comment] 2022-10-07 20:03
If you have any more information, please feel free to add it to this ticket. Without steps to reproduce, we can't really help you.

**Comment by stffabi** [comment] 2022-11-03 05:16
@glitchedgitz it seems like there's a possible fix for this, where this might happen in a multi monitor setup, see also #2042.

I've put up PR https://github.com/wailsapp/wails/pull/2043 with that fix, would it be possible for you to give it a try?

You can use [this guide](https://wails.io/docs/next/guides/bleeding-edge#testing-a-pr) to test the PR.

**Comment by leaanthony** [comment] 2022-11-03 08:14
Master now has the fixes for this. Please test using [this guide](https://wails.io/docs/guides/bleeding-edge). If it doesn't work as expected, please reopen 👍

**Closed** 2022-11-03 08:14 UTC
Labels: Bug, awaiting feedback, Ready For Testing, v2
