### ISSUE TITLE
Output file name ignored for darwin builds

### ISSUE THREAD

**Issue by kkrypt0nn** [wailsapp/wails#2608] opened 2023-04-17 13:58 UTC
### Description

When building a project for darwin and specifying the output file name with `-o something` the built file name will not be correctly named.

### To Reproduce

1. Create a project with `wails init -n myproject -t react-ts`
2. Execute `wails build --platform darwin/amd64 -webview2 download -o something`

### Expected behaviour

The final built file name should be named `something.app`

### System Details

```shell
Wails CLI v2.4.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | MacOS   
Version      | 13.3.1  
ID           | 22E261  
Go Version   | go1.20.3
Platform     | darwin  
Architecture | arm64   

# Wails

Version | v2.4.1

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2397   
npm                       | N/A          | Installed | 9.6.3  
*Xcode                    | N/A          | Available |        
*upx                      | N/A          | Available |        
*nsis                     | N/A          | Available |        
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details: 
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/
```

### Additional context

The CLI recognizes the output file name correctly:
```
Output File        | something
```

 Though built it under the name `myproject`:
```
Built '[...]/myproject/build/bin/myproject.app/Contents/MacOS/myproject' in 3.631s.
```

**Comment by stffabi** [comment] 2023-04-18 05:50
Thanks for reporting this. There's already an issue which covers this problem #2290.

We would love to see you over there and join the discussion on that issue 🙏

**Comment by stffabi** [comment] 2023-04-18 05:50
Duplicate of #2290

**Closed** 2023-04-18 05:50 UTC
Labels: Bug, v2
