### ISSUE TITLE
Repeatedly generate the build directory

### ISSUE THREAD

**Issue by 107295472** [wailsapp/wails#2204] opened 2022-12-14 03:51 UTC
### Description

![2CK1 ~5C3X1TNZUXXH795QL](https://user-images.githubusercontent.com/6436116/207501004-24907443-04c3-45b7-b2c5-e69ebc3e4c58.png)

### To Reproduce

After changing the go file

### Expected behaviour

after wails dev

### System Details

```shell
Wails CLI v2.2.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Enterprise LTSC 2019
Version:        1809 (Build: 17763)
ID:
Go Version:     go1.19.3
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.2.0

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       108.0.1462.46
npm             N/A             Installed       8.19.2
*upx            N/A             Installed       upx 3.96
*nsis           N/A             Available

* - Optional Dependency
```

**Comment by stffabi** [comment] 2022-12-14 07:13
Thanks for using Wails and reporting this issue.

This issue has already been fixed on master and will be in the next release.

**Comment by stffabi** [comment] 2022-12-14 07:14
Duplicate of #2100

**Closed** 2022-12-14 07:14 UTC
Labels: Bug, v2
