### ISSUE TITLE
Wails init failing

### ISSUE THREAD

**Issue by ghost** [wailsapp/wails#368] opened 2020-03-21 00:04 UTC
**Description**

Wails init command failing when building the frontend of the project

**To Reproduce**
Steps to reproduce the behaviour:
1. Type wails init
2. type any type of project name in any folder of you computer
3. type any output binary name
4. type any project directory
5. Choose ReactJS template
6. let wails create the project

**Expected behaviour**
Wails creating my project successfully without any error (and have it working when trying to launch it)

**Screenshots**
https://imgur.com/a/PphLId1

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v1.0.2 |
| Go Version    | go1.14 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 5.1.0 |
| Npm           | 6.14.3 |
| Node          | v12.16.1
 |

**Comment by leaanthony** [comment] 2020-03-21 02:50
Thanks for reporting this. Will check today.

**Comment by leaanthony** [comment] 2020-03-21 03:05
Cannot reproduce:

![image](https://user-images.githubusercontent.com/1943904/77218199-e75d7580-6b7c-11ea-9388-0b6ed1900d77.png)

Runs fine too:

![image](https://user-images.githubusercontent.com/1943904/77218203-fe03cc80-6b7c-11ea-8751-a69710d8e118.png)

**Comment by InfRandomness** [comment] 2020-03-21 14:52
I think windows is screwing around, checked on my Linux dual boot and working good. Closing.

**Closed by InfRandomness** 2020-03-21 14:52 UTC
Labels: Enhancement, cannot reproduce, v3
