### ISSUE TITLE
Crash when call runtime.OpenFileDialog on Windows 10/11

### ISSUE THREAD

**Issue by taliove** [wailsapp/wails#1648] opened 2022-07-25 09:54 UTC
### Description

When call runtime.OpenFileDialog on Windows, the program crashed! But it works on macOS.

### To Reproduce

```golang
opt := runtime.OpenDialogOptions{
    DefaultDirectory:           ".",
    DefaultFilename:            "filename",
    Title:                                "title",
    CanCreateDirectories:       true,
    TreatPackagesAsDirectories: false,
}
```
1. runtime.OpenFileDialog(ctx, opt)
2. build args:  wails build -platform=windows/amd64
3. run on windows 11
4. call function to trigger OpenFileDialog
5. the program crashed

### Expected behaviour

The selection file dialog box opens normally.

### Attempted Fixes

1. compile without upx. Not working.
2. change opt, delete DefaultDirectory property. it's work!  😄 

### System Details

```shell
Crash System:
windows 10 amd
windows 11 arm

Normal System:
macOS Monterey 12.4

wails version:
github.com/wailsapp/wails/v2 v2.0.0-beta.40
```

**Comment by leaanthony** [comment] 2022-07-25 10:37
Thanks for reporting this. Please try leaving the default directory blank. There's a [known issue](https://github.com/wailsapp/wails/issues/1381) with windows paths. If you believe it's the same problem, please close this and we'll track progress there. Thanks 👍

**Comment by leaanthony** [comment] 2022-08-09 20:41
Thanks for reporting 🙏

**Comment by leaanthony** [comment] 2022-08-13 06:53
@dsieradzki - Please open a new ticket as I cannot reproduce this.

**Closed by leaanthony** 2022-08-13 06:53 UTC
Labels: Bug, investigating, v2
