### ISSUE TITLE
[Error] WebSocket connection to 'ws://wails.localhost:34115/' failed: A server with the specified hostname could not be found.

### ISSUE THREAD

**Issue by zxdstyle** [wailsapp/wails#3057] opened 2023-11-15 15:09 UTC
### Description

[Error] WebSocket connection to 'ws://wails.localhost:34115/' failed: A server with the specified hostname could not be found.
[Error] Invalid url for WebSocket ws://localhost:undefined/
[Error] Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern.

**The page can be displayed normally, but the HMR in vite development mode fails due to Websocket connection failure.**

### To Reproduce

```
wails init demo -t react-ts
```

package.json
```json

{
  "name": "frontend",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/node": "^20.9.0",
    "@types/react": "^18.2.37",
    "@types/react-dom": "^18.2.15",
    "@vitejs/plugin-react": "^4.1.1",
    "typescript": "^5.2.2",
    "vite": "^4.5.0"
  }
}

```

### Expected behaviour

Hope HMR in vite development mode in works

### Screenshots

<img width="723" alt="image" src="https://github.com/wailsapp/wails/assets/38398954/ec09a221-6b30-40e8-bcef-c7ec062edaa5">

### System Details

```shell
# Wails
Version | v2.6.0

# System
┌─────────────────────────┐
| OS           | MacOS    |
| Version      | 13.3.1   |
| ID           | 22E261   |
| Go Version   | go1.20.3 |
| Platform     | darwin   |
| Architecture | amd64    |
└─────────────────────────┘

# Dependencies
┌────────────────────────────────────────────────────────────────┐
| Dependency                | Package Name | Status    | Version |
| Xcode command line tools  | N/A          | Installed | 2397    |
| Nodejs                    | N/A          | Installed | 20.0.0  |
| npm                       | N/A          | Installed | 9.6.4   |
| *Xcode                    | N/A          | Available |         |
| *upx                      | N/A          | Available |         |
| *nsis                     | N/A          | Available |         |
└─────────────────── * - Optional Dependency ────────────────────┘

# Diagnosis
Optional package(s) installation details:
  - Xcode: Available at https://apps.apple.com/us/app/xcode/id497799835
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 SUCCESS  Your system is ready for Wails development!

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by zxdstyle** [comment] 2023-11-15 15:14
By the way, works fine in chrome browser

**Comment by stffabi** [comment] 2023-11-20 08:23
Thanks for using Wails and reporting this issue.

This is a duplicate of #3064, I'm going to close this issue and would welcome you over at #3064

**Comment by stffabi** [comment] 2023-11-20 08:23
Duplicate of #3064

**Closed by stffabi** 2023-11-20 08:23 UTC
Labels: Bug, v2
