### ISSUE TITLE
[V2] SIGSEV Gorilla Websocket on linux amd64 - works on windows.

### ISSUE THREAD

**Issue by efitzkiwi** [wailsapp/wails#1321] opened 2022-04-09 00:30 UTC
### Description

Gorilla websocket causes SIGSEV on application start in Ubuntu 20.04 (amd64 binary). This error does not happen on windows .exe files built by wails. Tested on both bleeding edge and latest stable beta.

There are two other test functions that can be tested to prove the websocket is the problem

### To Reproduce

clone https://github.com/KillerKiwiJuice/wailstestbug
cd into frontend, `npm i`
ensure code in `recv_poly_data2` is not commented out (or to make the app run, comment it out)
`wails build -platform linux/amd64`
`./build/bin/databridge`

### Expected behaviour

App should run without SIGSEV

### Screenshots

![image](https://user-images.githubusercontent.com/9599423/162548925-ac755696-bba9-4c98-a5d9-ce2e35f9ae9b.png)

### Attempted Fixes

Tried arm64 build

### System Details

```shell
System
------
OS:             Ubuntu
Version:        20.04
ID:             ubuntu
Go Version:     go1.17.1
Platform:       linux
Architecture:   amd64

Wails
------
Version:                v2.0.0-beta.34
Package Manager:        apt

Dependency      Package Name            Status          Version
----------      ------------            ------          -------
*docker         docker.io               Installed       20.10.14
gcc             build-essential         Installed       12.8ubuntu1.1
libgtk-3        libgtk-3-dev            Installed       3.24.20-0ubuntu1.1
libwebkit       libwebkit2gtk-4.0-dev   Installed       2.34.6-0ubuntu0.20.04.1
npm             npm                     Installed       6.14.4+ds-1ubuntu2
*nsis           nsis                    Available       3.05-2
pkg-config      pkg-config              Installed       0.29.1

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - nsis: sudo apt install nsis
```

### Additional context

Full error stack
```
2022/04/08 20:19:11 connecting to wss://testnet-explorer.binance.org/ws/block
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100000200 pc=0x7f45228b57fa]

runtime stack:
runtime.throw({0x7649e7, 0x5e33cf5ed123d300})
        /usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x6cb550, 0xc000159e58)
        /usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0xc000159e30 sp=0xc000159df8 pc=0x409f7c
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux._Cfunc_gtk_main()
        _cgo_gotypes.go:975 +0x45 fp=0xc000159e58 sp=0xc000159e30 pc=0x6b6d05
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Window).Run(0xc00014a2a0, {0x756932, 0xe})
        /home/ubuntu/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.34/internal/frontend/desktop/linux/window.go:814 +0xd3 fp=0xc000159e90 sp=0xc000159e58 pc=0x6bf013
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).Run(0xc00014a230, {0x7f50c0, 0xc00014e870})
        /home/ubuntu/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.34/internal/frontend/desktop/linux/frontend.go:144 +0xc5 fp=0xc000159ed0 sp=0xc000159e90 pc=0x6b9405
github.com/wailsapp/wails/v2/internal/appng.(*App).Run(0xc000080410)
        /home/ubuntu/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.34/internal/appng/app_production.go:38 +0x31 fp=0xc000159f08 sp=0xc000159ed0 pc=0x6c7311
github.com/wailsapp/wails/v2.Run(0x200000003)
        /home/ubuntu/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.34/wails.go:24 +0x33 fp=0xc000159f20 sp=0xc000159f08 pc=0x6c7ad3
main.main()
        /home/ubuntu/tests/test/main.go:26 +0x39b fp=0xc000159f80 sp=0xc000159f20 pc=0x6c843b
runtime.main()
        /usr/local/go/src/runtime/proc.go:255 +0x227 fp=0xc000159fe0 sp=0xc000159f80 pc=0x43c027
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000159fe8 sp=0xc000159fe0 pc=0x468e81

goroutine 19 [chan receive]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).startRequestProcessor(0x0)
        /home/ubuntu/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.34/internal/frontend/desktop/linux/frontend.go:301 +0x5a
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend
        /home/ubuntu/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.34/internal/frontend/desktop/linux/frontend.go:96 +0x305

goroutine 20 [chan receive]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).startMessageProcessor(0x0)
        /home/ubuntu/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.34/internal/frontend/desktop/linux/frontend.go:113 +0x59
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend
        /home/ubuntu/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.34/internal/frontend/desktop/linux/frontend.go:99 +0x347

goroutine 6 [select]:
main.(*NonBlockingChan).run(0xc00005c020, 0x7f50c0, 0xc000026180)
        /home/ubuntu/tests/test/non-blocking-channel.go:38 +0xf2
created by main.NewNonBlockingChannel
        /home/ubuntu/tests/test/non-blocking-channel.go:66 +0x156

goroutine 5 [IO wait]:
internal/poll.runtime_pollWait(0x7f44f4521e88, 0x72)
        /usr/local/go/src/runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc00007c100, 0xc000161980, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00007c100, {0xc000161980, 0x183e, 0x183e})
        /usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00007c100, {0xc000161980, 0xb8c12f4f31875e62, 0xc1d57fac2e0ca60e})
        /usr/local/go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc0000b01c0, {0xc000161980, 0x84ec9c73ab638974, 0xc000155400})
        /usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0000ad278, {0xc000161980, 0x0, 0x41060d})
        /usr/local/go/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc0000a5e78, {0x7ed9e0, 0xc0000ad278})
        /usr/local/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0000a5c00, {0x7ede80, 0xc0000b01c0}, 0x4000)
        /usr/local/go/src/crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0000a5c00, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc0000a5c00, {0xc00006c000, 0x1000, 0x0})
        /usr/local/go/src/crypto/tls/conn.go:1277 +0x16f
bufio.(*Reader).fill(0xc000456480)
        /usr/local/go/src/bufio/bufio.go:101 +0x103
bufio.(*Reader).ReadSlice(0xc000456480, 0xe5)
        /usr/local/go/src/bufio/bufio.go:360 +0x2f
bufio.(*Reader).ReadLine(0xc000456480)
        /usr/local/go/src/bufio/bufio.go:389 +0x27
net/textproto.(*Reader).readLineSlice(0xc000155b10)
        /usr/local/go/src/net/textproto/reader.go:57 +0x99
net/textproto.(*Reader).ReadLine(...)
        /usr/local/go/src/net/textproto/reader.go:38
net/http.ReadResponse(0xc000456480, 0xc000076100)
        /usr/local/go/src/net/http/response.go:161 +0xd8
github.com/gorilla/websocket.(*Dialer).DialContext(0x4e5a9f, {0x7f5050, 0xc0000a2000}, {0x764f6d, 0x2b}, 0x1)
        /home/ubuntu/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/client.go:339 +0x1698
github.com/gorilla/websocket.(*Dialer).Dial(0x7576c8, {0x764f6d, 0xc0000f7f38}, 0x466cae)
        /home/ubuntu/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/client.go:106 +0x38
main.recv_poly_data2(0xc00003a7a8, 0xc00000e018)
        /home/ubuntu/tests/test/databridge.go:95 +0x6e
main.AllDownhillFromHere(0x0)
        /home/ubuntu/tests/test/databridge.go:137 +0xd4
created by main.(*App).startup
        /home/ubuntu/tests/test/app.go:30 +0xe9

goroutine 7 [chan receive]:
main.process_poly_json2(0xc00005c020, 0x0)
        /home/ubuntu/tests/test/databridge.go:79 +0x37
created by main.AllDownhillFromHere
        /home/ubuntu/tests/test/databridge.go:136 +0xc5
```

Thank you for the package

**Comment by leaanthony** [comment] 2022-04-09 02:07
Almost certainly a duplicate of #1268 
A fix has been pushed to `master`. If you would like to use it before the next release, please follow the [Bleeding Edge Guide](https://wails.io/docs/guides/bleeding-edge).

**Comment by KillerKiwiJuice** [comment] 2022-04-09 06:47
It is not the same error unfortunately. I am using the Bleeding Edge version and the SIGSEV occurs as some kind of race condition. I am able to get code to execute directly after the Gorilla Websocket dial function but only a couple lines print before it breaks...

The minimum reproduceable example is in the above git in OP. Maybe my bleeding edge install is incorrect, but I don't think so. It includes the `runtime.LockOSThread()` call.

**Comment by leaanthony** [comment] 2022-04-09 07:16
The original stack trace looks like it was from `beta.34`. Could you print out a stacktrace from when you use master please? Thanks.

**Comment by KillerKiwiJuice** [comment] 2022-04-09 07:51
That is the version for bleeding edge, no? I deleted and reinstalled my entire go folder, then cloned this git, and installed the local wails source in `wails/v2/cmd/wails` , `go install` -> `wails version` -> `v2.0.0-beta.34`. 🤔

**Comment by leaanthony** [comment] 2022-04-09 08:29
you need to use `replace` in your `go.mod` as per the [guide](https://wails.io/docs/guides/bleeding-edge)

**Comment by KillerKiwiJuice** [comment] 2022-04-09 18:03
> you need to use `replace` in your `go.mod` as per the [guide](https://wails.io/docs/guides/bleeding-edge)

I've done that as well. I am even looking at the github, in this master branch, `version.go` says `var Version = "v2.0.0-beta.34"`.

**Comment by KillerKiwiJuice** [comment] 2022-04-09 18:48
I was able to temporarily get it to work by moving the Websocket defaultdialer to the main.go `main` function, then pass a pointer to the websocket connection to the app. Then the pointer to the websocket could be used throughout any goroutine without SIGSEV. 

I wouldn't necessarily call it solved now, but this is a workaround for those using Gorilla websocket inside the app. Move it to the main function!

**Comment by leaanthony** [comment] 2022-04-09 22:25
I'm not 100% convinced this is a Wails issue, more a goroutine/memory management issue. Have you run the app in gdb then done a bit to find out exactly where the issue is

**Comment by napalu** [comment] 2022-04-10 10:24
@KillerKiwiJuice I cloned your repo and pulled the latest wails from master, went to wails/v2/cmd/wails, built wails and installed it. I then `replaced` wails in your `go.mod` with the current bleeding edge (on my ubuntu 20.04 it looks like this `replace github.com/wailsapp/wails/v2 => ../wails/v2`,  built your repo and ran it.

I haven't been able to reproduce the SIGSEGV you mention - which from your report does look very much like what was reported in #1268 and #1316. 

```
Wails CLI v2.0.0-beta.34


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		Ubuntu
Version: 	20.04
ID:		ubuntu
Go Version:	go1.18
Platform:	linux
Architecture:	amd64

Wails
------
Version: 		v2.0.0-beta.34
--> Revision:		c70d93b482be1d1f40c110c16d7ea0db218c4250
--> Modified:		false
Package Manager: 	apt

Dependency	Package Name		Status		Version
----------	------------		------		-------
*docker		docker.io		Available	20.10.7-0ubuntu5~20.04.2
gcc		build-essential		Installed	12.8ubuntu1.1
libgtk-3	libgtk-3-dev		Installed	3.24.20-0ubuntu1.1
libwebkit	libwebkit2gtk-4.0-dev	Installed	2.34.6-0ubuntu0.20.04.1
npm		npm			Installed	6.14.16
*nsis		nsis			Available	3.05-2
pkg-config	pkg-config		Installed	0.29.1-0ubuntu4

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - docker: sudo apt install docker.io
  - nsis: sudo apt install nsis

```
I notice that your wails doctor output does not show the `Revision` and `Modified` fields mine does (check the arrows in the `wails doctor` output above) - can you fetch the latest master, check your replace, rebuild and post your wails doctor output again (as well as check if you still get the crash)?  
Thanks!

**Comment by KillerKiwiJuice** [comment] 2022-04-10 17:37
@napalu I have been running on an EC2 instance if it makes a difference. And I am 100% sure I was running the latest master branch. I will try a fresh VM test when I get the chance and report back. If it really is a race condition and not related to [#1268](https://github.com/wailsapp/wails/issues/1268) then I expect inconsistent results.

**Comment by napalu** [comment] 2022-04-11 10:45
@KillerKiwiJuice I was able to reproduce the error - it's just hard to reproduce on my system. I get a rare `segmentation violation code=0x1` on startup - this looks different from the error in #1268 - I'm looking through the stack trace,

**Comment by stffabi** [comment] 2022-04-11 16:19
IIRC there are some code paths in linux platform code, where a pointer to go structs that might be on the stack are handed over to ExecuteOnMainThread.
Depending on execution, reusage of the stack and growing of the stack there might be the wrong data in there.
Maybe it's worth to take a deeper look into that direction. Nevertheless it would be good to remove that pointers to the stack.

**Comment by stffabi** [comment] 2022-05-11 08:14
I have pushed the draft PR #1392 which makes sure the pointer to the stack won't be invalid during the callback.

@KillerKiwiJuice would it be possible for you to test the PR and see if that helps in your case?

**Comment by stffabi** [comment] 2022-06-28 12:47
Wails Release [v2.0.0-beta.38](https://github.com/wailsapp/wails/releases/tag/v2.0.0-beta.38) contains a possible fix for this. Would it be possible for you @KillerKiwiJuice to give that release a try?

**Comment by KillerKiwiJuice** [comment] 2022-07-19 20:58
Apologies for late reply. After updating to beta .39 and Golang 18, I am unable to reproduce this bug using https://github.com/KillerKiwiJuice/wailstestbug

It's hard for me to say for sure if it is fixed forever since I believe it was a race condition.

**Comment by leaanthony** [comment] 2022-07-19 21:09
Glad you got it fixed @KillerKiwiJuice - Feel free to reopen if it happens again 👍

**Closed by leaanthony** 2022-07-19 21:09 UTC
Labels: Bug, awaiting feedback, v2
