### ISSUE TITLE
Resizing window causes flickering in wails apps in Linux/Kwin

### ISSUE THREAD

**Issue by kelvie** [wailsapp/wails#1655] opened 2022-07-26 00:24 UTC
### Description

This happens in the svelte demo app, but it also happens with wombat 0.5.0 downloaded from their site: https://github.com/rogchap/wombat/releases/tag/v0.5.0

### To Reproduce

1. Start wombat, or `wails dev` in Linux
2. resize the window

### Expected behaviour

That it resizes smoothly, like on Mac, for example.

### Screenshots

https://user-images.githubusercontent.com/5893/180896667-bace77f3-f1b2-4ee8-ba65-e310e0091d4c.mp4

### System Details

```shell
Wails CLI v2.0.0-beta.42

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Arch Linux
Version:        Unknown
ID:             arch
Go Version:     go1.18.4
Platform:       linux
Architecture:   amd64

Wails
------
Version:                v2.0.0-beta.42
Package Manager:        pacman

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
*docker         docker          Installed       1:20.10.17-1
gcc             gcc             Installed       12.1.0-3
libgtk-3        gtk3            Installed       1:3.24.34-1
libwebkit       webkit2gtk      Installed       2.36.4-2
npm             npm             Installed       8.15.0-1
pkg-config      pkgconf         Installed       1.8.0-1

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!


If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```
```


### Additional context

I use a nvidia graphics card, and KDE plasma 5.96.0 on X11.

I have tried turning the compositor both on and off on kwin.

**Comment by leaanthony** [comment] 2022-07-26 10:42
Hi. I believe this is a local issue, potentially related to gtk/kde integration WRT transparency on your system, and not a Wails bug, for the following reasons:
  - These 2 programs are built with totally different C codebases
  - Nobody else is reporting this
  - I can't reproduce it

Closing this for now but of someone else can reproduce we will reopen it 👍

**Closed by leaanthony** 2022-07-26 10:42 UTC
Labels: Bug, cannot reproduce, v2

**Comment by kelvie** [comment] 2022-07-27 05:27
It looks like I reproduced it using a webkit2gtk example program, so it's probably there. I'll do some more digging.

**Comment by leaanthony** [comment] 2022-07-27 08:55
Nice find 👍 Perhaps try a non WebKit program too. I suspect there's some clash with your transparency plugin that triggers based on a repaint or something. Perhaps WebKit is issuing a crazy amount of repaints.

**Comment by kelvie** [comment] 2022-07-27 22:52
This definitely doesn't happen on any other GUI app I use (including chrome, but that uses its own bundled webkit). I also tried it with compositing off, which disables any effects like transparency, so I don't think it's that, but it still might be the window manager.

I'll try this on sway/wayland and perhaps another lightweight X11 window manager. Either way it's not a wails bug (directly).

**Comment by leaanthony** [comment] 2022-07-31 11:42
There's a *lot* of hits when you google "gtk window flickering when resizing". I've reproduced it on my re-installed laptop. Do you see this issue @ianmjones ?

**Comment by ianmjones** [comment] 2022-07-31 13:05
I don't see this issue with b42 and the example app on NixOS unstable using i3-gaps and picom with Nvidia hardware. :shrug: 

I listed all those things because I agree that it's very likely an issue fixed by some config or video driver change, and not something that can be fixed in wails.
