### ISSUE TITLE
Deep Links / Custom protocol association

### ISSUE THREAD

**Issue by jakekimjy** [wailsapp/wails#3362] opened 2024-04-01 05:34 UTC
### Description

**Potential Bug for Custom Protocol Schemes Feature**
[Documentation on Custom Protocol Schemes](https://wails.io/docs/guides/custom-protocol-schemes/) suggests we're able to associate custom protocol schemes e.g. myapp://.
```
    "protocols": [
        {
          "scheme": "myapp",
          "description": "My App Protocol",
          "role": "Editor"
        }
    ]
```
This great feature by @APshenkin would allow deeplinking; and deeplinking enables functionalities like magic/enchanted links authentication, where users can click on a link in email to sign into their applications.  [first link I found on deep linking](https://www.adjust.com/glossary/deep-linking/)

**Issue**
Does not work as demonstrated on mac as demonstrated in the initial [pull request ](https://github.com/wailsapp/wails/pull/3000#issuecomment-2026248981).

I tried on both most recent version as well as the initial pr but maybe I'm doing something wrong

### To Reproduce

Assumed workspace:
/new_workspace_for_test

Download the pr from v2
1. git clone git@github.com:APshenkin/wails.git /new_workspace_for_test/wails
2. cd /new_workspace_for_test/wails
3. git checkout feature/deeplinks

Also download example provided
1. cd /new_workspace_for_test
2. git clone https://github.com/APshenkin/wails-open-file.git /new_workspace_for_test/example
3. cd /new_workspace_for_test/example
4. git checkout feature/deeplinks
5. open go.mod and modify the last line of go.mod
`replace github.com/wailsapp/wails/v2 v2.8.0 => /Users/jakekim/Desktop/Work/ByTeams/Code/wails/APshenkin/v2`
6. update wails.json
`
"protocols": [
      {
        "scheme": "myapp",
        "description": "My App Protocol",
        "role": "Editor"
      }
]
`
6. wails dev

Go into the browser and open up the console
1. In the console run 
`open("myapp://hello")
<img width="771" alt="Screenshot 2024-03-31 at 10 27 25 PM" src="https://github.com/wailsapp/wails/assets/137327995/6b6d3e0d-9d55-49be-a755-d5922607e633">

### Expected behaviour

From the original PR:
> You can see how it works here.
>
> [Windows](https://github.com/wailsapp/wails/assets/14344430/5f43c370-c782-4711-a50d-d19c2db563fd)
>  [MacOs](https://github.com/wailsapp/wails/assets/14344430/a0b745e7-95cc-401b-b9bf-79b35b3cb271)
>  [Linux](https://github.com/wailsapp/wails/assets/14344430/8cabebab-f8d4-4330-beae-c7a45d7f1854) – NOTE THIS IS NOT PART OF PR AS WAILS DOESN'T SUPPORT BUNDLING FOR LINUX. But it can be done manually using bundling (docs added for this)

### Attempted Fixes

Haven't tried to fix it yet but I did test it with the most recent code as well as the original PR. 

Not an expert but I could try to take a look if @APshenkin is no longer around.

### System Details

```shell
# Wails
Version | v2.8.0

# System
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | MacOS                                                                                                                       |
| Version      | 14.3.1                                                                                                                      |
| ID           | 23D60                                                                                                                       |
| Go Version   | go1.22.1                                                                                                                    |
| Platform     | darwin                                                                                                                      |
| Architecture | arm64                                                                                                                       |
| CPU          | Apple M2 Max                                                                                                                |
| GPU          | Chipset Model: Apple M2 Max Type: GPU Bus: Built-In Total Number of Cores: 30 Vendor: Apple (0x106b) Metal Support: Metal 3 |
| Memory       | 32GB                                                                                                                        |
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌─────────────────────────────────────────────────────────────────────────┐
| Dependency                | Package Name | Status    | Version          |
| Xcode command line tools  | N/A          | Installed | 2405             |
| Nodejs                    | N/A          | Installed | 18.17.1          |
| npm                       | N/A          | Installed | 9.6.7            |
| *Xcode                    | N/A          | Installed | 14.3.1 (14E300c) |
| *upx                      | N/A          | Available |                  |
| *nsis                     | N/A          | Available |                  |
└──────────────────────── * - Optional Dependency ────────────────────────┘
```

### Additional context

[Original PR here](https://github.com/wailsapp/wails/pull/3000)

**Comment by APshenkin** [comment] 2024-04-01 10:36
@byteams Just tried it right now and it's working to me.. I updated example branch and put exactly same  config and switched to latest wails version.

However I also had some glitches in `DEV` mode if for example you try to open deeplink, when app is not opened. Did you tried to build production build and check if it works?

**Comment by byteams** [comment] 2024-04-02 04:02
Gotcha - yepp I see that it works with the production build. 
Additional findings with dev:

For dev, now I'm seeing this error:
<img width="427" alt="Screenshot 2024-04-01 at 8 52 05 PM" src="https://github.com/wailsapp/wails/assets/137327995/3e3127c2-0ff7-4638-b404-821408a64b1d">
and am able to get around it by prompting for input like t
<img width="364" alt="Screenshot 2024-04-01 at 8 53 58 PM" src="https://github.com/wailsapp/wails/assets/137327995/8560570a-9dec-4f4c-889e-201b83488db4">

Do you have any ideas why it's not working with dev? and do you have any future plans to fix this?

Thanks for this implementation and answer

**Comment by APshenkin** [comment] 2024-04-14 10:02
It's actually works for me, for dev build. Just the app should be launched, you can't open it if dev app is not launched.

this is because you can't launch the app in dev mode without wails.

if you see this issue in case, when dev mode is launched, then we need some more details about how to reproduce. As I don't have same issue unfortunately:(

**Comment by byteams** [comment] 2024-04-22 12:06
Gotcha. Closing since production works and there's a workaround in dev. Thanks @APshenkin.

**Closed by byteams** 2024-04-22 12:06 UTC
Labels: Bug, v3
