### ISSUE TITLE
Wails runtime object exists only on "/" path url

### ISSUE THREAD

**Issue by ramory-l** [wailsapp/wails#2741] opened 2023-06-22 15:37 UTC
### Description

Wails runtime object exists only on "/" url

### To Reproduce

Trying to use console.log('runtime', (window as any).runtime) on a different router path will show undefined.

### Expected behaviour

Expected that runtime object exists on every page

### System Details

```shell
Mac Os Ventura 13.4 M1 Max
```

### Additional context
I'm using Vue3 with Vue Router
_No response_

**Comment by stffabi** [comment] 2023-06-29 12:56
Thanks for reporting this and using Wails.

We already have a tracking issue for this #2047 and #2262. So I'm going to close this in favour of those two issues. Please feel free to participate in the discussions over there.

**Comment by stffabi** [comment] 2023-06-29 12:56
Duplicate of #2047

**Closed by stffabi** 2023-06-29 12:56 UTC
Labels: Bug, v3
