### ISSUE TITLE
how to upgrade wails app online!

### ISSUE THREAD

**Issue by wangxing218** [wailsapp/wails#1883] opened 2022-09-23 08:37 UTC
### Describe the solution you'd like

Hope that the official can provide a solution for self upgrading of applications
Like electric updater
This is just a need

**Comment by stffabi** [comment] 2022-09-23 09:02
Thanks for reporting this enhancement request and using Wails

We already have a tracking issue for self-updating #1178. We welcome you being part of the discussion over there.

Closing as duplicate of #1178

**Comment by stffabi** [comment] 2022-09-23 09:04
Duplicate of #1178

**Closed** 2022-09-23 09:03 UTC
Labels: Enhancement, v3
