### ISSUE TITLE
DevWatcher signal killed

### ISSUE THREAD

**Issue by madebywelch** [wailsapp/wails#1649] opened 2022-07-25 10:36 UTC
### Description

I just created a new project `wails init` and am unable to run `wails dev` successfully. The error `Error from DevWatcher 'npm run dev': signal: killed` kills the process. This is a vanilla wails project, no edits on my end.

```
robert@Roberts-Mac-mini ok % wails dev
Wails CLI v2.0.0-beta.40

Executing: go mod tidy -compat=1.17
Executing: wails generate module
Installing frontend dependencies...

> frontend@0.0.0 dev
> vite


  vite v2.9.14 dev server running at:

Vite Server URL: http://localhost:3000/
  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 147ms.

Running frontend DevWatcher command: 'npm run dev'
Building application for development...
  - Compiling application: Done.
  - Packaging application: Done.

Watching (sub)/directory: /Users/robert/Development/wails-test/ok
Using DevServer URL: http://localhost:34115
Using Frontend DevServer URL: http://localhost:3000/
Using reload debounce setting of 100 milliseconds
Error: (0x458aae0,0xc0001216f0)
Development mode exited
DevWatcher command killed!
Error from DevWatcher 'npm run dev': signal: killed
DevWatcher command exited!

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### To Reproduce

1. `wails init -n ok`
2. `cd ok`
3. `wails dev`

### Expected behaviour

The app to run as outlined in the docs.

### System Details

```shell
robert@Roberts-Mac-mini wails-test % wails doctor
Wails CLI v2.0.0-beta.40

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	12.4
ID:		199506
Go Version:	go1.18.4
Platform:	darwin
Architecture:	amd64

Wails
------
Version: 	v2.0.0-beta.40

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2395
npm 				N/A		Installed	8.11.0
*upx 				N/A		Available	
*nsis 				N/A		Available	

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

Any help would be much appreciated.

**Comment by bits0rcerer** [comment] 2022-07-25 10:47
Same here :(

```
Wails CLI v2.0.0-beta.40

Executing: go mod tidy -compat=1.17
Executing: wails generate module
Installing frontend dependencies...

> frontend@0.0.0 dev
> vite


  VITE v3.0.3  ready in 160 ms

Vite Server URL: http://localhost:5173/
  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
Running frontend DevWatcher command: 'npm run dev'
Building application for development...
  - Compiling application: Done.
  - Packaging application: Done.

Watching (sub)/directory: /home/user/project/wails-project
Using DevServer URL: http://localhost:34115
Using Frontend DevServer URL: http://localhost:5173/
Using reload debounce setting of 100 milliseconds
Error: (0x97f8a0,0xc000021640)
Development mode exited
DevWatcher command killed!
Error from DevWatcher 'npm run dev': signal: killed
DevWatcher command exited!

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

## To Reproduce

1. `wails init -d . -g -ide goland -n wails-project -t svelte`
2. `wails dev`

## System Details

```
Wails CLI v2.0.0-beta.40

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Arch Linux
Version:        Unknown
ID:             arch
Go Version:     go1.18.4
Platform:       linux
Architecture:   amd64

Wails
------
Version:                v2.0.0-beta.40
Package Manager:        pacman

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
*docker         docker          Installed       1:20.10.17-1
gcc             gcc             Installed       12.1.0-2
libgtk-3        gtk3            Installed       1:3.24.34-1
libwebkit       webkit2gtk      Installed       2.36.4-2
npm             npm             Installed       8.14.0-1
pkg-config      pkgconf         Installed       1.8.0-1

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!


If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment] 2022-07-25 11:24
Thanks for reporting this! From my initial testing it looks like something is borked with the templates. If you build first, then run dev, it appears to work. Still investigating 👍

**Comment by leaanthony** [comment] 2022-07-25 11:34
Issue found. Creating Fix.

**Comment by leaanthony** [comment] 2022-07-25 11:45
Please try the above PR to see if this fixes your problem. If you are unsure how to do this, please follow [this guide](https://wails.io/docs/guides/bleeding-edge#testing-a-pr). Let us know how you get on 👍

**Comment by leaanthony** [comment] 2022-07-25 11:47
Actually, I'm pretty confident this is ok and I need to get this out. Will merge, release, and then you can get the fix via `wails update -pre`

**Comment by leaanthony** [comment] 2022-07-25 12:10
Merging the PR auto closed this. The fix is now in `v2.0.0-beta.40.2`. Please try with `wails update -pre`

**Comment by bits0rcerer** [comment] 2022-07-25 13:08
It works on my machine :tada:

**Comment by leaanthony** [comment] 2022-07-26 10:45
Closing as fixed in latest release. Thanks for your testing 🙏

**Closed by leaanthony** 2022-07-26 10:45 UTC
Labels: Bug, v2
