### ISSUE TITLE
[v2 Linux] Data race on application start

### ISSUE THREAD

**Issue by lyimmi** [wailsapp/wails#2061] opened 2022-11-07 22:36 UTC
### Description

There is a data race when app.go's startup function only consists of `a.ctx = ctx` and I call a runtime function after starting the application. (I can wait more than 30s before calling the runtime functions and a race still pops up.)
But if I put a `log.Println("hello")` in startup there is no data race.

Bad: It looks like startup() still writing to *App.
```golang
func (a *App) startup(ctx context.Context) {
	a.ctx = ctx
}
```

Good: But if I put a log there it is okay.
```golang
func (a *App) startup(ctx context.Context) {
	a.ctx = ctx
        log.Println("hello")
}
```

```diff
==================
WARNING: DATA RACE
Read at 0x00c0000255a0 by goroutine 99:
  main.(*App).Greet()
-     /home/lyimmi/projects/wailst/app.go:30 +0x75    <-- runtime.MessageDialog(a.ctx, runtime.MessageDialogOptions{}
  runtime.call32()
      /usr/local/go/src/runtime/asm_amd64.s:725 +0x48
  reflect.Value.Call()
      /usr/local/go/src/reflect/value.go:368 +0x149
  github.com/wailsapp/wails/v2/internal/binding.(*BoundMethod).Call()
      /home/lyimmi/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/internal/binding/boundMethod.go:73 +0x52e
  github.com/wailsapp/wails/v2/internal/frontend/dispatcher.(*Dispatcher).processCallMessage()
      /home/lyimmi/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/internal/frontend/dispatcher/calls.go:45 +0x924
  github.com/wailsapp/wails/v2/internal/frontend/dispatcher.(*Dispatcher).ProcessMessage()
      /home/lyimmi/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/internal/frontend/dispatcher/dispatcher.go:40 +0x324
  github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).processMessage.func1()
      /home/lyimmi/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/internal/frontend/desktop/linux/frontend.go:351 +0x101

Previous write at 0x00c0000255a0 by goroutine 16:
  main.(*App).startup()
-     /home/lyimmi/projects/wailst/app.go:24 +0x5a    <-- a.ctx = ctx
  main.(*App).startup-fm()
      <autogenerated>:1 +0x66
  github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).Run.func1()
      /home/lyimmi/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/internal/frontend/desktop/linux/frontend.go:149 +0xf0

Goroutine 99 (running) created at:
  github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).processMessage()
-     /home/lyimmi/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/internal/frontend/desktop/linux/frontend.go:350 +0xfa4    <-- result, err := f.dispatcher.ProcessMessage(message, f)
  github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).startMessageProcessor()
      /home/lyimmi/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/internal/frontend/desktop/linux/frontend.go:124 +0xbe
  github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend.func2()
      /home/lyimmi/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/internal/frontend/desktop/linux/frontend.go:109 +0x44

Goroutine 16 (finished) created at:
  github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).Run()
      /home/lyimmi/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/internal/frontend/desktop/linux/frontend.go:147 +0x145
  github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).Run()
      /home/lyimmi/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/internal/frontend/devserver/devserver.go:117 +0x1834
  github.com/wailsapp/wails/v2/internal/app.(*App).Run()
      /home/lyimmi/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/internal/app/app_dev.go:28 +0x9b
  github.com/wailsapp/wails/v2/pkg/application.(*Application).Run()
      /home/lyimmi/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/pkg/application/application.go:69 +0x2a7
  github.com/wailsapp/wails/v2.Run()
      /home/lyimmi/go/pkg/mod/github.com/wailsapp/wails/v2@v2.1.0/wails.go:14 +0x55
  main.main()
      /home/lyimmi/projects/wailst/main.go:19 +0x4e4
==================
```

### To Reproduce

1. Create a new Wails project
2. Use the following app.go code:
      ```golang
      package main
      
      import (
	      "context"
	      "fmt"
      
	      "github.com/wailsapp/wails/v2/pkg/runtime"
      )
      
      // App struct
      type App struct {
	      ctx context.Context
      }
      
      // NewApp creates a new App application struct
      func NewApp() *App {
	      return &App{}
      }
      
      // startup is called when the app starts. The context is saved
      // so we can call the runtime methods
      func (a *App) startup(ctx context.Context) {
	      a.ctx = ctx
      }
      
      // Greet returns a greeting for the given name
      func (a *App) Greet(name string) string {
	      runtime.MessageDialog(a.ctx, runtime.MessageDialogOptions{
		      Type:    runtime.InfoDialog,
		      Title:   "title",
		      Message: "msg",
	      })
      
	      return fmt.Sprintf("Hello %s, It's show time!", name)
      }
      
      ```
3. Run `wails dev --race` or `wails build --race`
4. When the app starts push the "Greet" button
5. See the race detector reporting 

### Expected behaviour

I would expect that the built in functions running without data race.

### Screenshots

![Screenshot from 2022-11-07 23-21-28](https://user-images.githubusercontent.com/8627125/200427945-f50d9bbf-471b-477a-8ba2-688b1822a5f8.png)

### Attempted Fixes

If I put a mutex on the App struct it solves it, but I don't think the problem originates there. 

### System Details

```shell
System
------
OS:		Pop!_OS
Version: 	22.04
ID:		pop
Go Version:	go1.19.1
Platform:	linux
Architecture:	amd64

Wails
------
Version: 		v2.1.0
Package Manager: 	apt

Dependency	Package Name		Status		Version
----------	------------		------		-------
*docker 	docker.io 		Installed 	20.10.14
gcc 		build-essential 	Installed 	11.3.0
libgtk-3 	libgtk-3-dev 		Installed 	3.24.33-1ubuntu2
libwebkit 	libwebkit2gtk-4.0-dev 	Installed 	2.36.8-0ubuntu0.22.04.1
npm 		npm 			Installed 	8.19.2
*nsis 		nsis 			Installed 	v3.08-2
pkg-config 	pkg-config 		Installed 	0.29.2

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
```

### Additional context

I can't really figure out where the problem is, but somewhere around the dispatcher / binding area.

Sorry I can't give you a narrower description.

**Comment by leaanthony** [comment] 2022-11-08 09:30
What happens if you wrap your context access in a mutex?

**Comment by stffabi** [comment] 2022-11-08 10:17
That occurs because the `OnStartup` callback is executed in a separate go routine and calls from the frontend are also executed in another go routine. So one go routine sets the context in the app struct and another uses it, where there's no synchronization point for the context.

That's also the root cause of an old issue #1407, where a frontend callback is executed before the OnStartup has finished.

**Comment by leaanthony** [comment] 2022-11-25 03:52
@Lyimmi shall we close this for now with the knowledge we'll be getting rid of the problem anyway?

**Comment by Lyimmi** [comment] 2022-11-25 05:46
@leaanthony sure, I'm fine with that.

**Closed** 2022-11-25 09:45 UTC
Labels: Bug, v3
