### ISSUE TITLE
Mac Program cannot lauch

### ISSUE THREAD

**Issue by drharryhe** [wailsapp/wails#1168] opened 2022-02-21 06:23 UTC
#####################################################
     **V1 users: If you have a technical issue, please do not open a bug this way!** 
                      Please use the `wails issue` command!
          If you do not do this then the issue may be closed automatically.                      

 NOTE: If your bug is related to Windows, make sure you read 
 the [Windows Developer Guide](https://wails.app/guides/windows/)
#####################################################

**Description**
using wails build to build a program on MacOS ,saying as myapp.app. when double click myapp.app, it can not be launched. but if i doubleclick myapp.app/Contents/MocOS/myapp, it can launch correctly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to build/bin
2. Double Click on 'myapp.app'
3. The program cannot be launched

**Expected behaviour**
myapp.app should be launched without error

**Screenshots**
n/a

**System Details**
V2 users: Please add the output of `wails doctor`.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/4024888/154900197-94d357a3-5924-498c-9d74-8cb35b000050.png">

**Additional context**
if i doubleclick myapp.app/Contents/MocOS/myapp, it can launch correctly.

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment] 2022-02-21 09:15
Can't reproduce on 12.0.1 (both ARM64 and AMD64). Please provide detailed steps including commands run and any debug output. Try running it via the "instruments" program and see what it says.

**Comment by drharryhe** [comment] 2022-02-21 16:22
thanks for quick response.  i am sorry but i did not catch you as what ""instruments" program and see what it says" mean .could you please give more information or any guideline link?

**Comment by leaanthony** [comment] 2022-02-21 19:29
Install Xcode. CMD+space and type instrument's

**Comment by drharryhe** [comment] 2022-02-22 06:35
thanks, leaanthony, here my instruments snapshot. since i am a beginner of MacOS developer, i'm not sure this is what you expected.  so i upload my demo to https://github.com/drharryhe/wailsdemo.  I would be grateful to you if you can take a look at my demo. 
thanks for help!

<img width="2596" alt="image" src="https://user-images.githubusercontent.com/4024888/155074303-f15a35b0-2223-
4dca-a104-02288a54424f.png">

**Comment by leaanthony** [comment] 2022-02-22 08:19
Instruments has a bunch of different profiles to run. Try a few and see if you can catch the error. Did you also check your `info.plist` is correct?

**Comment by drharryhe** [comment] 2022-02-22 09:01
when i double click my.app, i got error msgs in  system.log as below. Could you tell me how to fix it?

Feb 22 17:00:50 ruideMacBook-Pro com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.drharryhe.hguru.9107004.9107000(501)> [9256]
Feb 22 17:00:50 ruideMacBook-Pro com.apple.xpc.launchd[1] (application.com.drharryhe.hguru.9107004.9107000[37908]): Service exited with abnormal code: 2

**Comment by drharryhe** [comment] 2022-02-22 09:26
here is more system log,  which seems some file not found. but  it's weird why i can run it from my.app/content/macos/mybin?


Feb 22 17:24:04 ruideMacBook-Pro com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.drharryhe.hguru.9113550.9113547(501)> [9617]
Feb 22 17:24:04 ruideMacBook-Pro HGuru[39708]: getattrlist failed for /System/Library/Extensions/AppleIntelICLGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelICLGraphicsGLDriver: #2: No such file or directory
Feb 22 17:24:04 ruideMacBook-Pro HGuru[39708]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
Feb 22 17:24:04 ruideMacBook-Pro com.apple.xpc.launchd[1] (application.com.drharryhe.hguru.9113550.9113547[39708]): Service exited with abnormal code: 1

**Comment by drharryhe** [comment] 2022-02-22 10:02
my info.plist is this:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
	<key>CFBundlePackageType</key><string>APPL</string>
	<key>CFBundleName</key><string>HGuru</string>
	<key>CFBundleExecutable</key><string>HGuru</string>
	<key>CFBundleIdentifier</key><string>com.drharryhe.hguru</string>
	<key>CFBundleVersion</key><string>1.0.0</string>
	<key>CFBundleGetInfoString</key><string>Built using Wails (https://wails.app)</string>
	<key>CFBundleShortVersionString</key><string>1.0.0</string>
	<key>CFBundleIconFile</key><string>iconfile</string>
	<key>LSMinimumSystemVersion</key><string>10.13.0</string>
	<key>NSHumanReadableCopyright</key><string>Copyright @ 2022 Harry HE. All copyrights reserved.</string>
</dict></plist>

**Comment by newpurr** [comment] 2022-04-23 15:18
I have the same problem. Do you have a solution, brother

**Comment by newpurr** [comment] 2022-04-23 15:18
> I have the same problem. Do you have a solution, brother
100% chance of recurrence

**Comment by leaanthony** [comment] 2022-04-23 20:29
Not a Wails issue directly. Looks like some people get it for all kinds of programs.
https://discussions.apple.com/thread/252183335
https://www.reddit.com/r/MacOS/comments/l0t04q/mac_pro_big_sur_apps_cant_find_gpu_drivers/

**Comment by leaanthony** [comment] 2022-11-25 03:01
I believe this has been fixed in later macOS versions. Please reopen if it's still an issue 👍

**Closed by leaanthony** 2022-11-25 03:01 UTC
Labels: Bug, wont fix, cannot reproduce, v3

**Comment by deltaepsilon** [comment] 2024-03-26 14:37
I'm having a similar experience. My executable launches cleanly on its own, but the *.app bundle will never launch it. Double-click fails, as does `open QuiverPhotos.app` from the terminal.

I've triple-checked the `CFBundleExecutable` and run `chmod +x QuiverPhotos` on the executable itself. I'm at a loss.

Hopefully someone else has figured this out already!

<img width="1512" alt="Screenshot 2024-03-26 at 8 35 46 AM" src="https://github.com/wailsapp/wails/assets/878947/cf932209-67c6-47ea-a94e-6eed623cf791">

**Comment by deltaepsilon** [comment] 2024-03-27 11:38
I think I solved it.

I did a local build on MacOS and ran the following to see if it was signed. It wasn't. It was "ad hoc":

`codesign -dvvv QuiverPhotos.app`
```
Executable=/Users/chrisesplin/dev/quiver-photos-v2/build/bin/QuiverPhotos.app/Contents/MacOS/QuiverPhotos
Identifier=a.out
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20400 size=353406 flags=0x20002(adhoc,linker-signed) hashes=11041+0 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=242107fffa6b02a3625d19107e96d0de81ba2d0c
CandidateCDHashFull sha256=242107fffa6b02a3625d19107e96d0de81ba2d0cbcdb30da55898cd66f9109a3
Hash choices=sha256
CMSDigest=242107fffa6b02a3625d19107e96d0de81ba2d0cbcdb30da55898cd66f9109a3
CMSDigestType=2
CDHash=242107fffa6b02a3625d19107e96d0de81ba2d0c
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements=none
```

I already had my certificates configured on my machine, so I read out the developer ids:
```
bin git:(master) ✗ security find-identity -p codesigning -v
  1) BC6EEAC158FC4B9D9AEB734D65C115DB528E69F3 "Apple Development: Fáris Ismail (NBCZUK8367)"
  2) 35A795FE5BE240F5E3ABA5D3D51403D031328DA3 "Apple Development: Christopher Esplin (NLR9GCU5L5)"
  3) 4A1C379BF78BE47707CF84C2073274EEADF3CEB8 "Apple Distribution: Christopher Esplin (FZD76JR993)"
  4) 0359316A09368F4A5BBE08C9E662AD50D518591F "Developer ID Application: Christopher Esplin (FZD76JR993)"
```

Finally, I manually signed the executable and checked the signature again:
```
➜  bin git:(master) ✗ codesign -s "Developer ID Application: Christopher Esplin (FZD76JR993)" -f --timestamp -o runtime QuiverPhotos.app/Contents/MacOS/QuiverPhotos
QuiverPhotos.app/Contents/MacOS/QuiverPhotos: replacing existing signature
➜  bin git:(master) ✗ codesign -dvvv QuiverPhotos.app                                                                                                              
Executable=/Users/chrisesplin/dev/quiver-photos-v2/build/bin/QuiverPhotos.app/Contents/MacOS/QuiverPhotos
Identifier=com.chrisesplin.photos
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20500 size=353538 flags=0x10000(runtime) hashes=11041+3 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=7dcfb6deb617b18ed95c4b753f427b2ff74ddf3a
CandidateCDHashFull sha256=7dcfb6deb617b18ed95c4b753f427b2ff74ddf3ac32a6d1bc1010b8d62ec8d17
Hash choices=sha256
CMSDigest=7dcfb6deb617b18ed95c4b753f427b2ff74ddf3ac32a6d1bc1010b8d62ec8d17
CMSDigestType=2
CDHash=7dcfb6deb617b18ed95c4b753f427b2ff74ddf3a
Signature size=9057
Authority=Developer ID Application: Christopher Esplin (FZD76JR993)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Mar 27, 2024 at 5:31:54 AM
Info.plist entries=11
TeamIdentifier=FZD76JR993
Runtime Version=14.4.0
Sealed Resources version=2 rules=13 files=1
Internal requirements count=1 size=184
```

The file opens up now when I double-click it!

**Comment by leaanthony** [comment] 2024-03-27 19:39
Thanks for letting us know!

**Comment by xu756** [comment] 2024-11-09 10:36
> 我想我解决了。
> 
> 我在 MacOS 上进行了本地构建，并运行了以下命令来查看它是否已签名。结果显示未签名。它是“临时的”：
> 
> `codesign -dvvv QuiverPhotos.app`
> 
> ```
> Executable=/Users/chrisesplin/dev/quiver-photos-v2/build/bin/QuiverPhotos.app/Contents/MacOS/QuiverPhotos
> Identifier=a.out
> Format=app bundle with Mach-O thin (arm64)
> CodeDirectory v=20400 size=353406 flags=0x20002(adhoc,linker-signed) hashes=11041+0 location=embedded
> Hash type=sha256 size=32
> CandidateCDHash sha256=242107fffa6b02a3625d19107e96d0de81ba2d0c
> CandidateCDHashFull sha256=242107fffa6b02a3625d19107e96d0de81ba2d0cbcdb30da55898cd66f9109a3
> Hash choices=sha256
> CMSDigest=242107fffa6b02a3625d19107e96d0de81ba2d0cbcdb30da55898cd66f9109a3
> CMSDigestType=2
> CDHash=242107fffa6b02a3625d19107e96d0de81ba2d0c
> Signature=adhoc
> Info.plist=not bound
> TeamIdentifier=not set
> Sealed Resources=none
> Internal requirements=none
> ```
> 
> 我的机器上已经配置了证书，因此我读出了开发者 ID：
> 
> ```
> bin git:(master) ✗ security find-identity -p codesigning -v
>   1) BC6EEAC158FC4B9D9AEB734D65C115DB528E69F3 "Apple Development: Fáris Ismail (NBCZUK8367)"
>   2) 35A795FE5BE240F5E3ABA5D3D51403D031328DA3 "Apple Development: Christopher Esplin (NLR9GCU5L5)"
>   3) 4A1C379BF78BE47707CF84C2073274EEADF3CEB8 "Apple Distribution: Christopher Esplin (FZD76JR993)"
>   4) 0359316A09368F4A5BBE08C9E662AD50D518591F "Developer ID Application: Christopher Esplin (FZD76JR993)"
> ```
> 
> 最后，我手动对可执行文件进行了签名并再次检查签名：
> 
> ```
> ➜  bin git:(master) ✗ codesign -s "Developer ID Application: Christopher Esplin (FZD76JR993)" -f --timestamp -o runtime QuiverPhotos.app/Contents/MacOS/QuiverPhotos
> QuiverPhotos.app/Contents/MacOS/QuiverPhotos: replacing existing signature
> ➜  bin git:(master) ✗ codesign -dvvv QuiverPhotos.app                                                                                                              
> Executable=/Users/chrisesplin/dev/quiver-photos-v2/build/bin/QuiverPhotos.app/Contents/MacOS/QuiverPhotos
> Identifier=com.chrisesplin.photos
> Format=app bundle with Mach-O thin (arm64)
> CodeDirectory v=20500 size=353538 flags=0x10000(runtime) hashes=11041+3 location=embedded
> Hash type=sha256 size=32
> CandidateCDHash sha256=7dcfb6deb617b18ed95c4b753f427b2ff74ddf3a
> CandidateCDHashFull sha256=7dcfb6deb617b18ed95c4b753f427b2ff74ddf3ac32a6d1bc1010b8d62ec8d17
> Hash choices=sha256
> CMSDigest=7dcfb6deb617b18ed95c4b753f427b2ff74ddf3ac32a6d1bc1010b8d62ec8d17
> CMSDigestType=2
> CDHash=7dcfb6deb617b18ed95c4b753f427b2ff74ddf3a
> Signature size=9057
> Authority=Developer ID Application: Christopher Esplin (FZD76JR993)
> Authority=Developer ID Certification Authority
> Authority=Apple Root CA
> Timestamp=Mar 27, 2024 at 5:31:54 AM
> Info.plist entries=11
> TeamIdentifier=FZD76JR993
> Runtime Version=14.4.0
> Sealed Resources version=2 rules=13 files=1
> Internal requirements count=1 size=184
> ```
> 
> 当我双击它时文件就会打开！

same as I do, I cann't open it
