### ISSUE TITLE
[V2] go更新到1.19后，wails dev 报错

### ISSUE THREAD

**Issue by ghost** [wailsapp/wails#1693] opened 2022-08-04 08:42 UTC
### Description

go升级到1.19后，执行wails dev命令报错。
错误信息：invalid value "\"all=-N -l\"" for flag -gcflags: parameter may not start with quote character "

### To Reproduce

Wails V2 CLI beta-42
vue-ts
wails dev

### Expected behaviour

希望能在1.19半夏正常执行wails dev指令

### Screenshots

<img width="655" alt="image" src="https://user-images.githubusercontent.com/45232501/182802251-d7eaba5a-c2dd-4768-b985-897b22cd6a17.png">

<img width="759" alt="image" src="https://user-images.githubusercontent.com/45232501/182802184-41e0e620-fea8-4cba-9bbb-76cb51393a73.png">

![image](https://user-images.githubusercontent.com/45232501/182802340-24ad8b44-aa93-4abe-891c-a37ca20e4036.png)
![image](https://user-images.githubusercontent.com/45232501/182802966-c56b9b87-d56c-45be-a45f-36459e431c06.png)

### System Details

```shell
Wails CLI v2.0.0-beta.42

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	12.5
ID:		199506
Go Version:	go1.19
Platform:	darwin
Architecture:	amd64

Wails
------
Version: 	v2.0.0-beta.42

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2395
npm 				N/A		Installed	8.9.0
*upx 				N/A		Installed	upx 3.96
*nsis 				N/A		Installed	v3.08

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!


If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by stffabi** [comment] 2022-08-04 08:47
Thanks for reporting this and using Wails.

This seems to be a duplicate of #1688 and has already been fixed on master.

**Closed** 2022-08-04 08:48 UTC
Labels: Bug, v3

**Comment by leaanthony** [comment] 2022-08-04 08:49
Duplicate of #1690
