### ISSUE TITLE
[Linux] Gtk-CRITICAL **: 22:23:23.129: gtk_main_quit: assertion 'main_loops != NULL' failed

### ISSUE THREAD

**Issue by ianmjones** [wailsapp/wails#1654] opened 2022-07-25 21:27 UTC
### Description

When running an app built with Wails v2.0.0-beta.42 (and some earlier versions), whether as a built binary or via `wails dev`, when the app is quit, the following is displayed on the console:

```shell
Gtk-CRITICAL **: 22:23:23.129: gtk_main_quit: assertion 'main_loops != NULL' failed
```

### To Reproduce

1. Update to wails v2.0.0-beta.42
2. `wails init -t svelte -n wailsv2b42`
3. `cd wailsv2b42`
4. `wails build`
5. `build/bin/wailsv2b42`
6. Quit the app.

### Expected behaviour

No critical error displayed on console when app quits.

### System Details

```shell
Wails CLI v2.0.0-beta.42

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             NixOS
Version:        22.11
ID:             nixos
Go Version:     go1.18.4
Platform:       linux
Architecture:   amd64

Wails
------
Version:                v2.0.0-beta.42
Package Manager:        nixpkgs

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
*docker         nixos.docker    Installed       20.10.17
gcc             nixos.gcc       Installed       11.3.0
libgtk-3        nixos.gtk3      Installed       3.24.34
libwebkit       nixos.webkitgtk Installed       2.36.4
npm             nixos.nodejs    Installed       16.15.0
*nsis           nixos.nsis      Available       3.06.1
pkg-config      nixos.pkg-configInstalled       0.29.2
*upx            nixos.upx       Installed       3.96

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - nsis: nix-env -iA nixos.nsis



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment] 2022-07-25 22:42
Potentially using `g_application_quit()` instead of `gtk_main()` may fix this: https://stackoverflow.com/questions/36905118/code-cannot-exit-from-gtk-application-apparently-no-message-loops

Just need to test that the Go code continues to run after calling this.

**Comment by stffabi** [comment] 2022-07-26 06:15
The problem is `frontend.Quit` is called two times. The first time it is called e.g. when clicking the close button on the window. This call successfully executes `gtk_main_quit`. Then a second call to `frontend.Quit` will be initiated by the `app.Shutdown` method which is called after `frontend.Run` returns. 
https://github.com/wailsapp/wails/blob/6e0c2f7f791bebb1ceb77c28dd56ee8371f7f0ae/v2/internal/appng/app_production.go#L36-L48

This second call will then issue the assertion because the main_loop has already been finished. This has been introduced with PR #1488

**Comment by leaanthony** [comment] 2022-07-30 22:57
I think this one is covered by the PR and has been tested but not merged. Closing this to reduce noise 👍

**Closed by leaanthony** 2022-07-30 22:57 UTC
Labels: Bug, Ready For Testing, v2
