### ISSUE TITLE
None of the templates are working on Windows

### ISSUE THREAD

**Issue by lukasvosyka** [wailsapp/wails#284] opened 2019-11-03 01:01 UTC
**Description**

I really like the idea behind Wails. I was working with Electron till now, but I couldn't get the Get Started running. Building and compiling works fine, but when I start the .exe it shows me "An erro has occured in the script on this page", Line: 1, Char: 1, Error: Expected identifier, Code: 0..

**To Reproduce**
Steps to reproduce the behaviour:
- Install wails
- wails init
- wails build
- Run .exe

**Expected behaviour**
It shows something

**Screenshots**
![image](https://user-images.githubusercontent.com/7419311/68078786-cff43a80-fddd-11e9-9d81-354913f2ceff.png)

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.18.15-pre |
| Go Version    | go1.12.7 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 5.1.0 |
| Npm           | 6.12.0 |
| Node          | v12.13.0
 |

**Additional info**
I tried it on 2 different Windows 10 PCs, both with the same result.

**Comment by leaanthony** [comment] 2019-11-03 20:15
Hi. We have another ticket open for this. Windows 7,8 or 10?

**Comment by lukasvosyka** [comment] 2019-11-04 01:57
Hi Lea, sorry I didn’t know that. I am using Windows 10

**Comment by leaanthony** [comment] 2019-11-04 03:31
My advice would be to use the latest stable version: `wails update -version v0.18.5`. I've just issued a `go get github.com/wailsapp/wails/cmd/wails` and got a pre-release version, which is not what I was expecting as per [this page](https://golang.org/cmd/go/#hdr-Add_dependencies_to_current_module_and_install_them). I will need to investigate why pre-release versions are being pulled ahead of stable versions.

**Comment by leaanthony** [comment] 2019-11-04 04:31
Hi. Please run `wails update -pre` to get `v0.19.0-pre2`. Let me know if this fixes your issue. Thanks

**Comment by leaanthony** [comment] 2019-11-04 04:32
Closing as it is a duplicate of #278. Please post feedback on that ticket please 👍

**Closed by leaanthony** 2019-11-04 04:32 UTC
Labels: Enhancement, v3
