### ISSUE TITLE
[FEAT]: Native drap and drop for file and folder with complete filepath

### ISSUE THREAD

**Issue by hinupurthakur** [wailsapp/wails#1090] opened 2022-01-20 05:38 UTC
**Is your feature request related to a problem? Please describe.**
Currently, on Wails v1.16.8 as for windows development it depends on IE11 (as Windows development use the mshtml library which is only compatible with IE11), and On IE11, the drag and drop is not supported for folder. Whereas with Chrome, we can have file or folder drag and drop functionality.

**Describe the solution you'd like**
Feature that can be suitable would be native drag and drop with absolute path of dropped file/folder and if the dependency to IE11 can be removed.

**Describe alternatives you've considered**
Currently, We have tried the following approaches but not complete solution was found:
1. Use [ngx-file-drop](https://www.npmjs.com/package/ngx-file-drop) library for drag and drop, it worked fine for chrome but for IE11, only file drop was working fine and not folder. But was not providing absolute path of neither file not folder..
2. HTML Drag and drop: Failed for both file and folder.
3. Drag and drop on Input Type=File: Failed for both file and folder.
4. Created our own directive even it failed for both file and folder.

**Additional context**
![Screenshot from example Feature Request](https://user-images.githubusercontent.com/39610703/150279469-a0170725-9bad-41f7-878c-3cabd5730aea.png)

**Comment by leaanthony** [comment] 2022-01-20 06:10
For Windows, the recommendation is to move to v2.

**Comment by hinupurthakur** [comment] 2022-01-20 06:13
@leaanthony On v2, Do we have the native drag and drop functionality.

**Comment by leaanthony** [comment] 2022-01-20 06:57
No, but HTML dnd should.

**Comment by hinupurthakur** [comment] 2022-01-20 07:04
> No, but HTML dnd should.

Okay Let me check. I will update here with its status.

**Comment by hinupurthakur** [comment] 2022-01-24 08:22
@leaanthony It worked with wails v2 but We are not getting the full path of the drag and dropped file. Which make sense for the browser but the full path for the local machine should be accessible. Do we have any work around in wails?

**Comment by leaanthony** [comment] 2022-01-24 08:52
Thanks for replying. Not right now but happy to accept a PR if it works on all platforms. Why do you need the path?

**Comment by hinupurthakur** [comment] 2022-01-24 10:17
Okay, I will be happy to contribute for this feature. Should I include the complete drag and drop functionality ( HTML impplementation) with full path as Native drag and drop?

Also, I need the path as I want to create some chunks of the file at the location of where the file is located and that is to be done from the Backend (Go)

**Comment by misitebao** [comment] 2022-01-27 04:39
> Okay, I will be happy to contribute for this feature. Should I include the complete drag and drop functionality ( HTML implementation) with full path as Native drag and drop?
> 
> Also, I need the path as I want to create some chunks of the file at the location of where the file is located and that is to be done from the Backend (Go)

At present, there is no way for the front end to obtain the file content. The current feasible way is to start a service on the back end, and then pass the front end to the back end through the service, just like uploading a file on a web page. Because the current Wails does not provide a good way, this method can only be adopted. accomplish.

**Comment by Purple-CSGO** [comment] 2022-01-27 05:02
It's natural for modern app developers to bring in drag n drop feature. It makes users comfortable to select files or dirs. 

@hinupurthakur  Could you post a link referring to how the full path is got when it's done? It's definitely an important feature for me to choose the framework.

**Comment by hinupurthakur** [comment] 2022-01-27 07:14
> At present, there is no way for the front end to obtain the file content. The current feasible way is to start a service on the back end, and then pass the front end to the back end through the service, just like uploading a file on a web page. Because the current Wails does not provide a good way, this method can only be adopted. accomplish.

@misitebao Currently, yes involvment with the backend is the only work around but a feature for a drag and drop with complete file path would be a really good option for the wails.

**Comment by hinupurthakur** [comment] 2022-01-27 07:17
> @hinupurthakur Could you post a link referring to how the full path is got when it's done? It's definitely an important feature for me to choose the framework.

Currently from frontend there isn't any possiblity, The work around I am having is involving backend with frontend to get the fullpath

**Comment by leaanthony** [comment] 2022-01-27 08:56
I suggest you take a look at https://github.com/splode/optimus which has drag and drop capabilities.

**Comment by hinupurthakur** [comment] 2022-01-28 04:37
@leaanthony I have checked the https://github.com/splode/optimus implementation of drag and drop but it is limited to file only. I also need to implement drag and drop for directory (folder).

**Comment by leaanthony** [comment] 2022-01-28 08:04
I suggest changing the ticket title

**Comment by hinupurthakur** [comment] 2022-02-02 07:10
@leaanthony Can you help with how we can proceed with this issue to the feature implementation?

**Comment by leaanthony** [comment] 2022-02-02 07:32
https://protonet.com/blog/html5-experiment-drag-drop-of-folders/ ?

**Comment by hinupurthakur** [comment] 2022-02-03 10:34
@leaanthony This wasn't helpful for full filepath.

**Comment by hinupurthakur** [comment] 2022-02-03 10:35
@leaanthony This wasn't helpful for full filepath.

**Comment by leaanthony** [comment] 2022-02-03 10:45
I can't help you with this.

**Comment by hinupurthakur** [comment] 2022-02-03 10:48
@leaanthony So Can we work towards integrating this feature in wails? Or is it not possible at all?

**Comment by hinupurthakur** [comment] 2022-02-04 06:49
@leaanthony I am a backend developer but will research more on it and will provide more information here. Any help from other community members would be really appreciated as well.
Thanks!

**Comment by annikovk** [comment] 2022-02-11 09:21
Electron extends DOM to include path to file: https://www.electronjs.org/docs/latest/api/file-object#file-object

>  File interface provides abstraction around native files in order to let users work on native files directly with the HTML5 file API.

**Comment by leaanthony** [comment] 2022-02-11 10:22
Yeah, I wonder how they do that?

**Comment by leaanthony** [comment] 2022-03-06 10:29
How did you get on?

**Comment by hinupurthakur** [comment] 2022-03-06 15:54
@leaanthony I would really like to help here to implement something like what electronjs have but probably I will need some guidance there to understand the project better. Let me know if there is a community call or meeting that I can connect on to contribute to this.

**Comment by amlwwalker** [comment] 2022-05-04 16:36
@leaanthony @hinupurthakur 

Followed this conversation and dug into the Electron solution for this to see what was involved. I'm a little swept off my feet at the moment, however it seems that this is the code that does what you are asking about here 

https://github.com/electron/electron/blob/main/patches/chromium/blink_file_path.patch

referenced in the documentation here...

https://www.electronjs.org/docs/latest/api/file-object

How to map this to Wails, I am not sure, but perhaps this is a good place to start?

**Comment by leaanthony** [comment] 2022-05-04 20:27
Thanks for the links. The patch is patching the browser so there's not much we can take from that. Reopening though 👍

**Comment by selvindev** [comment] 2022-05-05 03:22
I would love to have this feature for a new Desktop App. This app ([Varly](https://github.com/varlyapp/varlyapp)) would benefit from having files/folders dropped right onto its UI.

Happy to contribute to this effort however I can.

Here is a repository/plugin that offers this functionality for Flutter. It contains the native code for macOS, Windows, and Linux: https://github.com/MixinNetwork/flutter-plugins/tree/main/packages/desktop_drop

I'm not an expert in C or Swift but willing to figure it out. Is the code in this repository something that we could bring into wails?

**Comment by wangleilei2010** [comment] 2022-05-12 06:20
![image](https://user-images.githubusercontent.com/24955267/168003878-7123543d-5a16-45b1-9bde-92fe2fd76bd4.png)
I also need this feature. Now the tool based wails2 could open local file dialog and select one and then import by the full path, that's great. If wails supports files dargging will be amazing. Because work in local, there's no need to transfer the full content of files from frontend  to backend, it just need a fullpath, backend read and parse from the path.

**Comment by leaanthony** [comment] 2022-05-12 10:24
Scheduled for 2.5 but will consider before then if a PR is raised 👍

**Comment by kilicbaran** [comment] 2022-09-24 18:13
As far as I understand, Tauri listens to file drop on the window containing the embedded Webview and fires an event with the file names, but I don't know whether the same can be done in Wails.

**Comment by Lyimmi** [comment] 2022-12-31 00:16
I looked around and tried a few options for this on linux.

I couldn't intercept webview's drop target no matter what I do the mouse cursor is stuck in "drop mode" and I have to restart the window manager... And if I made the window a drop target the webview caught the drop event first.

The working solution I could come up is I made an overlay with the following setup:

- overlay
  - box
    - menu
    - webview
  - label
  
Set the label to pass through events and opacity 0 and made it a drop target.

--wails-draggable:no-drag still works because it starts with a click on webview.

Probably we can find a better way, just thought I share my experiment.

[screencast_00002.webm](https://user-images.githubusercontent.com/8627125/210119343-b6207228-c699-43fe-a790-2b2b6bb6f660.webm)

**Comment by leaanthony** [comment] 2022-12-31 02:07
That's awesome! Does this mean the entire window is a drop target?

**Comment by Lyimmi** [comment] 2022-12-31 03:09
> That's awesome! Does this mean the entire window is a drop target?

Yes.

And I think this way we could switch between this and the WebView's drop target by toggling the overlay's order in runtime.

**Comment by emm1R** [comment] 2023-01-23 10:39
Any idea how long it will take until this is implemented?

**Comment by saucer-man** [comment] 2023-02-15 09:19
if use `<input type="file" id="fileImage" name="fileImage" @change="showImg">`， then how to get full filepath in frontend？

**Comment by Pritep** [comment] 2023-04-20 22:45
> 

Excuse me, Buy i didnt understand You, overlay and label?
How did You handled the mouse event?

**Comment by Lyimmi** [comment] 2023-04-20 23:24
> > 
> 
> Excuse me, Buy i didnt understand You, overlay and label?
> How did You handled the mouse event?

Hi, if your question is for me, I made the example above by modifying the GTK window and the WebView by adding an overlay on top of them and made that a drop target in GTK.

But it was just a test, it was not wired into wails just logged the coordinates to the terminal.

**Comment by Pritep** [comment] 2023-04-20 23:37
Thanks You

I have tried to reproduce the example, but if i don't make the modification it doesn't work

**Comment by umurpza** [comment] 2023-06-24 00:58
I'm also interested in this.

**Comment by leaanthony** [comment] 2023-07-09 22:21
Just an FYI: We're adding support for this in v3. The initial support will be that the drop zone is the entire window. It may be possible to identify an element from the client mouse coordinates using something like `document.elementFromPoint` but we'd have to take the scroll position of the page into account.

**Comment by ayatkyo** [comment] 2023-07-11 02:10
For Windows webview2, this may be useful. There is a sample for handling files using `<input type="file" />` and getting full path of that files:

- https://github.com/MicrosoftEdge/WebView2Samples/blob/main/SampleApps/WebView2APISample/assets/ScenarioDragDrop.html
- https://github.com/MicrosoftEdge/WebView2Samples/blob/main/SampleApps/WebView2APISample/ScenarioDragDrop.cpp

I have tried implementing this in Wails, and the progress so far is getting how many items dropped (I created 2 cases `<input type="file" />` and `drop` event with `dataTransfer`) and sending dummy data to the frontend.

Because my knowledge of Go and C++ is limited 😅 , I get stuck on porting [this line](https://github.com/MicrosoftEdge/WebView2Samples/blob/dd3ccca01a6625189f2fe48f85505c4abccdc1d7/SampleApps/WebView2APISample/ScenarioDragDrop.cpp#L38-L41), it always returns `nil` or crashes the app.

As this is so close to make it work, I will provide a demo repo for anyone that wants to test it.

**Comment by leaanthony** [comment] 2023-07-11 08:22
@ayatkyo If you create a branch off `v3-alpha` and open a PR, we could try help! 👍

**Comment by ayatkyo** [comment] 2023-07-13 19:45
> @ayatkyo If you create a branch off `v3-alpha` and open a PR, we could try help! 👍

Great, but currently I use v2 because cannot test the v3 right now, here is the [demo repo ](https://github.com/ayatkyo/wails-2-file-drop-test) and the fork of [go-webview2](https://github.com/ayatkyo/go-webview2/tree/feat-file-drop), the app will be crash in [this line](https://github.com/ayatkyo/go-webview2/blob/feat-file-drop/pkg/edge/chromium.go#L349-L356).

I also have used your https://github.com/leaanthony/webview2generator to generate go reference from the new WebView2.idl

any feedback will be appreciated, thanks

**Comment by leaanthony** [comment] 2023-07-13 20:14
I didn't think the generator still worked on the latest IDL. It's also flakey on Boolean conversion FYI.

**Comment by ayatkyo** [comment] 2023-07-13 20:21
Hi

> I didn't think the generator still worked on the latest IDL. It's also flakey on Boolean conversion FYI.

Actually, I just use some files that were generated and adjust them with the current Wails codebase 😅  .

I have updated the demo, and finally we can now get the full path of files (for Windows).

https://github.com/wailsapp/wails/assets/2143364/54a8781f-c098-4bbf-bd32-cd8550690255

**Comment by leaanthony** [comment] 2023-07-13 22:09
This is 🔥

**Comment by leaanthony** [comment] 2023-07-15 04:59
I think there's some things to do on this but it's a fantastic start! Are you wanting to do a PR for this @ayatkyo ? If you are too busy, I'm happy to take this on and give you full credit. Up to you 🙏

**Comment by ayatkyo** [comment] 2023-07-15 12:01
> I think there's some things to do on this but it's a fantastic start! Are you wanting to do a PR for this @ayatkyo ? If you are too busy, I'm happy to take this on and give you full credit. Up to you 🙏

Sure, if you don't mind, I will create Draft PR, as I want to learn more about the Wails internal.

**Comment by leaanthony** [comment] 2023-07-15 12:42
Awesome 🙏

**Comment by HKMV** [comment] 2023-07-17 10:21
It's awesome, I've wanted this feature for a long time

**Comment by AnthoniG** [comment] 2023-08-10 18:01
This is only Windows though so far isn't it?
No Mac or Linux ?
Also, no timeline for v3?

I wanted to build a file compression program. I can get the entire file if I use the FileReader API, but really I need the full path of the file to read it in via chunks.

**Comment by haukened** [comment] 2023-08-28 00:54
A little late to the party, but isn't this what webtkit2gtk allow-universal-access-from-file-urls is for?

Typically each file is considered a separate web origin, I'm pretty sure enabling this flag gives your the real system file path. (Not tested it myself).

[webkit2gtk documentation](https://webkitgtk.org/reference/webkit2gtk/unstable/property.Settings.allow-universal-access-from-file-urls.html)

**Comment by jphalip** [comment] 2023-08-28 02:40
> A little late to the party, but isn't this what webtkit2gtk allow-universal-access-from-file-urls is for?
> 
> Typically each file is considered a separate web origin, I'm pretty sure enabling this flag gives your the real system file path. (Not tested it myself).
> 
> [webkit2gtk documentation](https://webkitgtk.org/reference/webkit2gtk/unstable/property.Settings.allow-universal-access-from-file-urls.html)

That looks promising indeed. Electron enables that property: https://github.com/electron/electron/blob/d42a94dddeb86d349c050c2ee59b135bd6c8245c/shell/browser/electron_browser_client.cc#L420

**Comment by haukened** [comment] 2023-08-28 02:55
I'll see what I can do with this tomorrow! I'd be interested in this as well

**Comment by haukened** [comment] 2023-08-28 20:20
I've looked at this, and it looks like some of the assumptions made above are in fact true.
While this setting does allow webkit2 to operate outside the sandbox to some extent, its also true that electron is distributing a modified version of Chromium with an expanded version of the HTML5 `File` API thats being populated with the native system file path.   I don't see how this is currently possible in version 2, unless anyone has some bright ideas? 💡

**Comment by rangwea** [comment] 2023-11-07 02:25
I'm also waiting for the Native Drap feature. In the v2 version, I can only use this way to implement it: [onImagePasted](https://github.com/rangwea/swallow-wails/blob/main/frontend/src/components/ArticleEditor.jsx)
to upload image byte, and backend method [ArticleInsertImageBlob](https://github.com/rangwea/swallow-wails/blob/main/backend/app.go) to save image and return path.

**Comment by lyimmi** [comment] 2024-01-13 00:40
Hi, 

I need this functionality for one of my projects and I started implementing it on Linux because that is my most used platform.

As of now I solved the webview stealing my dnd events from the window and crashing my whole window manager issue, by simply calling `gtk_drag_dest_unset(G_OBJECT(webview));` on the webview and disabling all dnd events, this way the window can catch all the necessary events.

Here is my progress: https://github.com/lyimmi/wails/tree/feature/1090_native_drag_and_drop_for_file_and_folder

I made two options in the `options.App` struct:
- `EnableDragAndDrop` disables the webview's default drag and drop functionality and enables wails's custom drag and drop events and handlers.
- `DisableWebviewDragAndDrop` It can be used to prevent accidental file opening of dragged in files in the webview, when there is no need for drag and drop. _(Without cancelling dnd handlers in javascript)_

I have implemented two basic methods in the runtime both JS and GO side.  
It uses the already existing event system.  
The coordinates and the file lists are passed from `window.c` to the go side via the `processMessage()` function and after some validation and checking it is emitted to the JS and GO side as well.

The API is pretty linux specific so far, but I'm sure we can solve this on windows and mac as well.

@leaanthony and @stffabi if you have time and take a look at this solution and you think this kind of API could be solved on windows and mac I'm willing to sink some more in time to this and try to solve it on windows.


_**Below I made some examples of the current implementaion.**_


**The GO side:**

```golang
import "github.com/wailsapp/wails/v2/pkg/runtime"

runtime.DragAndDropOnMotion(ctx, func(x, y int) {
    log.Println("coords", x, y)
})

runtime.DragAndDropOnDrop(ctx, func(paths ...string) {
    log.Println("drop", paths)
})
```

**The JS side:**

```javascript
import {DragAndDropOnDrop, DragAndDropOnMotion} from "../wailsjs/runtime/runtime.js";

DragAndDropOnMotion((x,y) => {
  console.log("coords", x, y);
});

DragAndDropOnDrop(paths => {
  console.log("paths", paths);
});
```

**The JS side (extra):**

In javascript we could implement something like the code below. (Bit nicer maybe :sweat_smile:)

Something similar to the `--wails-draggable:drag` and `--wails-draggable:no-drag` style.  
It could be `--wails-drop-target:drop` and `--wails-drop-target:no-drop` with the stream of coordinates javascript could attach a class e.g `wails-drop-target-active` to the HTML element when a dragging mouse is over an element that is tagged whit `--wails-draggable:drag`.

This could be another option in the `options.App` struct `EnableDragAndDropHTMLSomethingSomething`.

```javascript
import {DragAndDropOnDrop, DragAndDropOnMotion} from "../wailsjs/runtime/runtime.js";

let prevEl = null;

DragAndDropOnMotion((x,y) => {
  const el = document.elementFromPoint(x, y);
  const elStyle = el.getAttribute("style");

  if(elStyle !== null && elStyle.indexOf("--wails-drop-target:drop") < 0){
    prevEl = el;
    el.classList.add("wails-drop-target-active");
  } else if(prevEl !== null) {
    prevEl.classList.remove("wails-drop-target-active");
  }
});

DragAndDropOnDrop(paths => {
  if(prevEl !== null) {
    prevEl.value = paths[0];
    prevEl.classList.remove("wails-drop-target-active");
  }
});
```

Here is a very basic example with the base application and some "advanced" CSS.

[Screencast from 2024-01-13 01-07-58.webm](https://github.com/wailsapp/wails/assets/8627125/21d2899c-e8cf-44ae-bb4b-fff68715d088)

**Comment by lyimmi** [comment] 2024-01-14 03:50
I successfully married @ayatkyo's and my solution and it works both on Windows and Linux now.

I dropped the movement coordinate events and changed the options.
When the `options.DragAndDrop.EnableWails` is set to `true` the events and handlers are started:
- On windows javascript handles the drops and sends it to the go side to resolve the file paths based on @ayatkyo work with some minor changes to be compatible with the Linux implementation.<br><br>The whole window is a drop target but the drop will be only accepted on html element tagged with `--wails-drop-target:drop`<br><br>On mouse hover elements with `--wails-drop-target:drop` get an html class `wails-drop-target-active`.<br>(The JS code for this is a bit ugly tbh. It was flickering a bit, so I had to make it more complex than I would have liked to.)
- On linux the implementation is a bit simple GTK pushes the drop event to go and go sends events to JS and go.
- On mac I think the implementation would be the same as on Linux. But I'm not versed in the magic of macOs develpement.

The `options.DragAndDrop.Disable` option disables the webview's DnD:
- On windows I used `chromium.AllowExternalDrag(false)`
- On Linux I used `gtk_drag_dest_unset(G_OBJECT(webview))`

The default runtime handlers can be left out if someone wants to implement a custom handler for the drop events by simply listening to `wails.dnd.drop` events.

Please try this fork and if its ok I'll make a PR for it.
https://github.com/lyimmi/wails/tree/feature/1090_native_drag_and_drop_for_file_and_folder

It needs some cleaning up but as a test I think its ok.

options:
```golang

type DragAndDrop struct {

	// EnableWails enables wails' drag and drop functionality that returns the dropped in files' absolute paths.
	EnableWails bool

	// Disable webview's drag and drop functionality.
	//
	// It can be used to prevent accidental file opening of dragged in files in the webview, when there is no need for drag and drop.
	Disable bool

	// CSS property to test for drag and drop target elements. Default "--wails-drop-target"
	CSSDropProperty string

	// The CSS Value that the CSSDropProperty must have to be a valid drop target. Default "drop"
	CSSDropValue string
}
```

go runtime method:

```golang
runtime.HandleDragAndDrop(ctx, func(paths ...string) {
    log.Println("drop", paths)
})
```

javascript runtime method:

```javascript
HandleDragAndDrop(paths => {
    console.log(paths);
});
```

**Comment by astrin-app** [comment] 2024-01-14 10:43
how about dragging files out of the window into something like a file explorer?

**Comment by lyimmi** [comment] 2024-01-14 17:51
> how about dragging files out of the window into something like a file explorer?

Well that is another can of worms that I think I'm going leave to some one else. :)

**Comment by APshenkin** [comment] 2024-02-10 14:27
@leaanthony @lyimmi 

I have some progress on macOS.
I can continue it, just want to confirm, that nobody picked it for now

**Comment by leaanthony** [comment] 2024-02-10 20:47
@APshenkin - Check this out: https://github.com/wailsapp/wails/pull/3203#issuecomment-1928853579 - feel free to branch that and provide updates if you like. The more people commenting/looking at this, the better!

**Comment by lyimmi** [comment] 2024-02-10 23:20
Hi @APshenkin I don't know what stage @pavelbinar (and his team) are at with it, but as @leaanthony said the more eyes looking at it the better. 

For example on windows there is a small window while the dom loads, that the drag and drop prevention is not loaded yet and your drop can still fall trough the original behavior and blow up the state of the program from than on. I have to look into that.

I think we should start the webview with the original D&D blocked and "disable" the wails implementation when the dom is ready. :thinking:

**Comment by APshenkin** [comment] 2024-02-11 03:05
@leaanthony @lyimmi @pavelbinar 

macOS is ready to be reviewed 🎉

https://github.com/wailsapp/wails/assets/14344430/8ee2dd20-677b-4d33-9764-d35d33965442

**Comment by Sammy-T** [comment] 2024-06-17 23:33
Using v2.9.1 on Windows 10, I'm not seeing either the Go or Js callback for `OnFileDrop` being called.

```go
DragAndDrop: &options.DragAndDrop{
  EnableFileDrop:     true,
  DisableWebViewDrop: true,
},
OnDomReady: func(ctx context.Context) {
  runtime.EventsOn(ctx, "wails:file-drop", func(optionalData ...interface{}) {
    log.Printf("events on file drop: %v", optionalData) // Doesn't get called
  })
  runtime.OnFileDrop(ctx, func(x, y int, paths []string) {
    log.Printf("Dropped at %v,%v\npaths: %v\n", x, y, paths) // Doesn't get called
  })
},
```

Additionally, `DisableWebViewDrop` doesn't seem to prevent the default webview open behavior.

**Comment by lyimmi** [comment] 2024-06-18 01:23
Hi,

I checked it on Win11.

Yes the DisableWebViewDrop does not register a javascript listener on windows to prevent the default behavior. This should be added, mac and linux handles this at the window level.

As far as I can see the current windows implementation requires the `--wails-drop-target:drop` css style to work on the js side. @jakubpeleska was it intentional? I don't remember if I put it there or not originally.

https://github.com/wailsapp/wails/blob/022a5ffec4a5d956a909796ca62411506847bb0e/v2/internal/frontend/runtime/desktop/draganddrop.js
```javascript

/**
 * onDrop is called when the drop event is emitted.
 * @param {DragEvent} e 
 * @returns 
 */
function onDrop(e) {
    if (!window.wails.flags.enableWailsDragAndDrop) {
        return;
    }
    e.preventDefault();

    if (!flags.useDropTarget) {   <----- this is the problem
        return;
    }

    // Trigger debounce function to deactivate drop targets
    if(flags.nextDeactivate) flags.nextDeactivate();
.....

```

How ever the go events are working fine for me.

**Comment by jakubpeleska** [comment] 2024-06-18 07:37
Hi, the condition was already present before my changes. 

https://github.com/wailsapp/wails/blame/318628d815d9b97ba2d0438efb34968c1a54acc7/v2/internal/frontend/runtime/desktop/draganddrop.js#L68

I did not encouter this problem as it is specific to Windows. However I think we can simply fix by moving the file resolving before the condition.

**Comment by hemkantSplat** [comment] 2024-06-18 08:09
> Using v2.9.1 on Windows 10, I'm not seeing either the Go or Js callback for `OnFileDrop` being called.
> 
> ```go
> DragAndDrop: &options.DragAndDrop{
>   EnableFileDrop:     true,
>   DisableWebViewDrop: true,
> },
> OnDomReady: func(ctx context.Context) {
>   runtime.EventsOn(ctx, "wails:file-drop", func(optionalData ...interface{}) {
>     log.Printf("events on file drop: %v", optionalData) // Doesn't get called
>   })
>   runtime.OnFileDrop(ctx, func(x, y int, paths []string) {
>     log.Printf("Dropped at %v,%v\npaths: %v\n", x, y, paths) // Doesn't get called
>   })
> },
> ```
> 
> Additionally, `DisableWebViewDrop` doesn't seem to prevent the default webview open behavior.

I have same issue with v2.9.0 none of the events are being called

**Comment by leaanthony** [comment] 2024-06-18 19:59
> I did not encouter this problem as it is specific to Windows. However I think we can simply fix by moving the file resolving before the condition.

Would it be possible for you to raise a quick PR for this? 🙏

**Comment by leaanthony** [comment] 2024-07-10 03:44
@FrancescoLuzzi @hemkantSplat - I'm testing this on the master branch and not seeing any issue. Events are being raised in Go and JS... 

In my main.go: ```go
		OnDomReady: func(ctx context.Context) {
			runtime.EventsOn(ctx, "wails:file-drop", func(optionalData ...interface{}) {
				log.Printf("events on file drop: %v", optionalData) // Doesn't get called
			})
			runtime.OnFileDrop(ctx, func(x, y int, paths []string) {
				log.Printf("Dropped at %v,%v\npaths: %v\n", x, y, paths) // Doesn't get called
			})
		},```

Using https://github.com/beam-transfer/wails-drag-and-drop as a sample project except I had to change the react component otherwise it immediately deregisters the listener:
```ts
  useEffect(() => {
    OnFileDrop((x, y, paths) => {
      console.log(x, y, "Dropped files: ", paths);
    }, true);
    // return () => OnFileDropOff();
  }, []);
```

So I'm unclear now what the linked PR is trying to fix 😅

**Comment by FrancescoLuzzi** [comment] 2024-07-10 04:04
@leaanthony My PR covers the case where you pass `false` when calling `OnFileDrop` in the JS side.
Since the check on that flag (`useDropTarget`) is done before computing the file path of the dropped file, the drop event is never triggered

I can't speak about the GO side of things since i've not used it 😄

**Closed** 2024-07-10 05:00 UTC
Labels: Enhancement, TODO, v3

**Comment by Sammy-T** [comment] 2024-07-11 18:39
So I'm able to get the Go callbacks to run now but I'm seeing some inconsistencies I'm not understanding using the current master branch. 

First, I was under the impression that I could use either the Go or Js `OnFileDrop()` methods as needed but I need to include both if I want the Go methods to run. Is this the intended behavior?

Also, if `--wails-drop-target: drop;` isn't set on a frontend element: 

- [x] The Go `EventsOn(ctx, "wails:file-drop", ...)` callback runs as expected
- [x] The Go `OnFileDrop()` callback runs as expected
- [x] The Js `EventsOn('wails:file-drop', ...)` callback runs as expected
- [ ] But the Js `OnFileDrop()` does not run the passed in callback

which doesn't make sense to me since the Js `OnFileDrop()` method needs to be used for any of it to work.

**Comment by FrancescoLuzzi** [comment] 2024-07-11 20:45
> First, I was under the impression that I could use either the Go or Js `OnFileDrop()` methods as needed but I need to include both if I want the Go methods to run. Is this the intended behavior?
> * [ ]  But the Js `OnFileDrop()` does not run the passed in callback

Yes it is intended, but only if you pass the `useDropTarget` as `true`
https://github.com/FrancescoLuzzi/wails/blob/master/v2/internal/frontend/runtime/desktop/draganddrop.js#L220-L229

This helps you implement the drop behavior without checking that the drop location is inside the bounds of the element that you intend to drop on, which would be something like:
```javascript
useEffect(() => {
    OnFileDrop((x, y, paths) => {
      // useRef that bad boy
      const bb = refDrop.current.getBoundingClientRect();
      if ( x >= bb.left && x <= bb.right && y >= bb.bottom && y <= bb.top){
         // do something with paths
      }
    }, false); // we want to handle this manually so set useDropTarget to false
    return () => OnFileDropOff();
  }, []);
```
