### ISSUE TITLE
window.open is not working on mac

### ISSUE THREAD

**Issue by askie** [wailsapp/wails#1522] opened 2022-07-03 08:00 UTC
### Description

on windows :
```
window.open("./test.htm","_blank");
```
on wails dev: work good, a browser window will open the test.html .

but ,on wails build, can not open the test.html file,browser window report error.

on mac dev and build mod :  window.open not working.

### To Reproduce
```
<button onclick="go()">go</button>
<script>
function go(){
window.open("test.html","_blank");
}
</script>
```
### Expected behaviour

on windows  and mac system, need window.open working properly.

### System Details

```shell
Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             MacOS
Version:        12.4
ID:             199506
Go Version:     go1.18.3
Platform:       darwin
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.37

Dependency                      Package Name    Status          Version
----------                      ------------    ------          -------
xcode command line tools        N/A             Installed       2395
npm                             N/A             Installed       8.11.0
*upx                            N/A             Available
*nsis                           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Comment by leaanthony** [comment] 2022-07-03 08:57
Yes, that won't work as you are trying to load a file that does not exist. Your best bet would be to use a data-uri for the html, eg

`data:text/html,%3Ch1%3EHello%2C%20World%21%3C%2Fh1%3E`

**Comment by askie** [comment] 2022-07-03 09:08
@leaanthony  Can you give me  a demo code? thx!

**Comment by askie** [comment] 2022-07-03 09:16
on windows the below code is working:
```
popwin=window.open("","_blank","height=600,width=400");
popwin.document.write("<h2>hello world</h2>");
```

but on macos, it's not working, the new window not open

**Comment by leaanthony** [comment] 2022-07-03 10:55
> @leaanthony  Can you give me  a demo code? thx!

No, sorry. I don't have any code that does this.

**Comment by csterritt** [comment] 2022-07-04 20:41
Supplying a full URL also doesn't work on Mac (don't have windows, so I can't test there):

~~~ js
window.open('https://www.google.com', '_blank')
~~~

Thanks!

**Comment by leaanthony** [comment] 2022-07-04 22:40
Did you check Apple's documentation on whether WkWebView supports window.open?

**Comment by csterritt** [comment] 2022-07-04 23:29
@leaanthony Sorry, my bad, I didn't check *Wails*'s documentation! Turns out `BrowserOpenURL` does exactly what I want. Thanks!

**Comment by leaanthony** [comment] 2022-07-08 06:13
Fixed by/Duplicate of https://github.com/wailsapp/wails/issues/1480.

**Closed by leaanthony** 2022-07-08 06:13 UTC
Labels: Bug, awaiting feedback, v2
