### ISSUE TITLE
How to check app window is fullscreen

### ISSUE THREAD

**Issue by wantg** [wailsapp/wails#1379] opened 2022-05-05 01:12 UTC
### Describe the solution you'd like

`
package runtime

func WindowIsFullScreen(ctx context.Context) bool
`

or provide two trigger

`
package options

type App struct {
...
OnFullscreen      func(ctx context.Context)
OnUnfullscreen  func(ctx context.Context)
...
}
`

**Comment by stffabi** [comment] 2022-05-05 06:40
Thanks for your feature request. That functionality should be coming with PR #1349 , which is currently WIP.

**Comment by leaanthony** [comment] 2022-05-05 07:51
Hey there 👋 There's a PR open for this that's being worked on. Would appreciate your input into that. Am on mobile so can't link right now. Cheers. 👍

**Comment by leaanthony** [comment] 2022-05-05 07:51
Would appreciate your input into the PR 👍

**Comment by leaanthony** [comment] 2022-05-05 21:26
Thanks for the kind feedback. Let us know how we can make it even better 👍

**Comment by kroksys** [comment] 2022-05-25 11:28
Created my first project with wails - finally some good GUI library for go! Thanks for a good work!
Eager to get ```IsFullscreen``` function.

**Comment by leaanthony** [comment] 2022-07-03 01:27
This is a duplicate of #1348. There's a draft PR open for this functionality. Please leave comments there. Thanks.

**Closed by leaanthony** 2022-07-03 01:27 UTC
Labels: Enhancement, v3
