### ISSUE TITLE
[FEAT] Detect new App Version / Auto Download and Update App?

### ISSUE THREAD

**Issue by KiddoV** [wailsapp/wails#2031] opened 2022-11-01 18:12 UTC
### Is your feature request related to a problem? Please describe.

It would be nice to have a built-in auto detect and update a ``Wails`` application, based on a backend server or GitHub repo?

Similar to GitHub Desktop or VSCode (made from Electron?) will ask user to update the application whenever new version are available, through a front-end popup message.

### Describe the solution you'd like

Make a built-in function or use external go lib?

**Comment by leaanthony** [comment] 2022-11-01 19:17
Duplicate of https://github.com/wailsapp/wails/issues/1178

**Closed** 2022-11-01 19:18 UTC
Labels: Enhancement, v3
