### ISSUE TITLE
frontend\wailsjs\runtime\package.json: Access is denied.

### ISSUE THREAD

**Issue by Web3codexio** [wailsapp/wails#2371] opened 2023-02-12 13:24 UTC
### Description

I run "wails dev" command and it got a error of  "frontend\wailsjs\runtime\package.json: Access is denied,which didnt show in eariler version

### To Reproduce

just follow the official documention to init the project and run the command of "wails dev"

### Expected behaviour

works fine

### Screenshots

![image](https://user-images.githubusercontent.com/50604703/218313689-cb0cce05-6709-493f-a0d9-709d686c1341.png)

### Attempted Fixes

1、update to the latest version
2、grant enough authority  to the project folder

### System Details

```shell
DEB | Using go webview2loader 
Wails CLI v2.3.1 

Scanning system - Please wait (this may take a long time)...Done. 

# System

OS           | Windows 10 Pro
Version      | 1809 (Build: 17763)
ID           | 
Go Version   | go1.18.1
Platform     | windows
Architecture | amd64

# Wails

Version | v2.3.1

# Dependencies

Dependency | Package Name | Status    | Version      
WebView2   | N/A          | Installed | 109.0.1518.78
npm        | N/A          | Installed | 9.4.2
*upx       | N/A          | Installed | upx 4.0.2
*nsis      | N/A          | Available | 
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
```

### Additional context

there must be something with the newest update,cause the error didnt show in version 2.2.0

**Comment by mingchangge** [comment] 2023-02-13 02:57
I also have the same problem
### wails dev screenshot：
![image](https://user-images.githubusercontent.com/26216558/218358497-4e674e0c-8fa0-4065-bbd5-ff4fd7a8dea7.png)
### wails build --debug screenshot：
![image](https://user-images.githubusercontent.com/26216558/218358723-a331c528-564f-40db-bcbf-846a2903b415.png)
### System Details
![image](https://user-images.githubusercontent.com/26216558/218358300-aa9db5eb-e228-48c1-ae5f-8e4c5966f22f.png)

**Comment by stffabi** [comment] 2023-02-13 06:30
Thanks for using Wails and bringing this issue up.

This seems like a duplicate of #2367 and I've added some information and a possible draft PR to improve the situation there.

Would be awesome if you could join the discussion over there so we have all the information in one place.

Thanks so much.

**Comment by stffabi** [comment] 2023-02-13 06:30
Duplicate of #2367

**Closed by stffabi** 2023-02-13 06:30 UTC
Labels: Bug, v2
