### ISSUE TITLE
WindowGetSize() Always larger than we set via options.App

### ISSUE THREAD

**Issue by zimolab** [wailsapp/wails#2297] opened 2023-01-14 15:36 UTC
### Description

i'am doing something like window state restoration in golang. I use runtime runtime.WindowGetSize() and runtime.WindowGetPosition() to get the size and position of the window, store them into a json file before shutdown, read them on startup. I found that WindowGetPosition() always returns width and height values larger than they should be.

### To Reproduce

1. create a project with whatever template
2. set the width and height of the window via option or WindowSetSize():
```go
wails.Run(&options.App{
		Title:  "wails-playground",
		Width:  1024,
		Height: 768,
		Menu:   appMenu.GetMenu(),
		AssetServer: &assetserver.Options{
			Assets: assets,
		},
		BackgroundColour: &options.RGBA{R: 27, G: 38, B: 54, A: 1},
		OnStartup:        app.startup,
		OnShutdown: func(ctx context.Context) {
			c.Save()
		},
		Bind: []interface{}{
			app,
		},
	})
// or like this
runtime.WindowSetSize(a.ctx, 1024, 768)
```
3.get the width and heigth of the window
```go
w, h := runtime.WindowGetSize(a.ctx)
fmt.Println("w,h", w, h)
```

In my set i got `w,h 1280 960` in console

### Expected behaviour

the width and height value we passed and we got should be exactly the same.

### System Details

```shell
DEB | Using go webview2loader
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Windows 10 Pro
Version      | 2009 (Build: 22621)
ID           | 22H2
Go Version   | go1.19.4
Platform     | windows
Architecture | amd64

# Wails

Version | v2.3.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 108.0.1462.76
npm        | N/A          | Installed | 8.19.2
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by stffabi** [comment] 2023-01-14 15:43
Thanks for using Wails and reporting this.

I suspect this might be a duplicate of https://github.com/wailsapp/wails/issues/2023

Are you using display scaling on your machine?

**Comment by sebastian0x62** [comment] 2023-01-20 21:49
I see that `SetSize()` scales the pixels. But I'm wondering if this is correct. When one sets the size, it should already respect the scaling factor. Even in the browser my scaled viewport has different pixels then my 100% view. When I want something to be 50% wide of my viewport, this number should not be scaled.

**Comment by stffabi** [comment] 2023-01-20 22:17
SetSize needs to scale on Windows, that's how it's meant to work.

See [High DPI Desktop Application Development on Windows](https://learn.microsoft.com/en-gb/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows?redirectedfrom=MSDN) and the [Win32 HiDPI Sample](https://github.com/microsoft/Windows-classic-samples/blob/7cbd99ac1d2b4a0beffbaba29ea63d024ceff700/Samples/DPIAwarenessPerWindow/client/DpiAwarenessContext.cpp#L241)

All sizes should be defined in 100% but on retrieving the sizes it need to be inverse scaled.

**Comment by sebastian0x62** [comment] 2023-01-20 22:32
@stffabi I could make a PR for that. How to name the opposite of those "Scale..." functions?

**Comment by stffabi** [comment] 2023-01-22 09:20
A fix for this has been merged and will be part of the next release.

Please feel free to reopen if you have any further issues with this.

**Closed by stffabi** 2023-01-22 09:20 UTC
Labels: Bug, v2
