### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by non-one** [wailsapp/wails#1407] opened 2022-05-18 07:06 UTC
### Description

change the go file and will trigger rebuild function.
but in crash "panic: runtime error: invalid memory address or nil pointer dereference" 100%

### To Reproduce

1. make a app
2. change the code in go file(for me, I add `log.Println("-----------------------")` code line
3. crash happen

### Expected behaviour

rebuild successfully

### Screenshots

![image](https://user-images.githubusercontent.com/32992657/168978194-ef085d8c-8692-47fa-858d-8245b0d0d2db.png)

### System Details

```shell
Wails CLI v2.0.0-beta.36


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Home    
Version:        2009 (Build: 19043)
ID:             21H1
Go Version:     go1.18
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.36

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       101.0.1210.47
npm             N/A             Installed       8.5.5
*upx            N/A             Available
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

[crash_log.txt](https://github.com/wailsapp/wails/files/8713940/cra.txt)

**Comment by leaanthony** [comment] 2022-05-18 07:50
Thanks for opening this. I couldn't reproduce locally. Could you please provide a bigger stack track? Thanks

**Comment by non-one** [comment] 2022-05-18 08:16
I get some different track from `wails dev` console:

```
DEB | [DevWebServer] Websocket client 0xc000480d80 connected
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x9ae6a1]

goroutine 73 [running]:
main.(*App).GetRuntimeInfo(0x1?)
        */pagetop/app.go:72 +0x41
reflect.Value.call({0xa7b320?, 0xc000004c60?, 0x0?}, {0xabef41, 0x4}, {0x15d6a28, 0x0, 0x9e45a0?})
        C:/Program Files/Go/src/reflect/value.go:556 +0x845
reflect.Value.Call({0xa7b320?, 0xc000004c60?, 0x4f2d9a?}, {0x15d6a28, 0x0, 0x0})
        C:/Program Files/Go/src/reflect/value.go:339 +0xbf
github.com/wailsapp/wails/v2/internal/binding.(*BoundMethod).Call(0xc00014c3f0, {0x15d6a28, 0x0, 0x9e45a0?})
        C:/Users/17100/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/internal/binding/boundMethod.go:73 +0x16f
github.com/wailsapp/wails/v2/internal/frontend/dispatcher.(*Dispatcher).processCallMessage(0xc0002b0100, {0xc0004a2c40, 0x5f}, {0xc334e0, 0xc00029c0e0})
        C:/Users/17100/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/internal/frontend/dispatcher/calls.go:45 +0x188
github.com/wailsapp/wails/v2/internal/frontend/dispatcher.(*Dispatcher).ProcessMessage(0xc0002973b0?, {0xc0004a2c40?, 0xc000484500?}, {0xc334e0?, 0xc00029c0e0?})
        C:/Users/17100/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/internal/frontend/dispatcher/dispatcher.go:39 +0x5e
github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).processMessage.func1()
        C:/Users/17100/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/internal/frontend/desktop/windows/frontend.go:494 +0x3e        
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).processMessage
        C:/Users/17100/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.36/internal/frontend/desktop/windows/frontend.go:493 +0x21b       
[0518/155819.529:ERROR:window_impl.cc(114)] Failed to unregister class Chrome_WidgetWin_0. Error = 0
Caught quit
Development mode exited
```
**AND I am in another trouble, I cant open the wails windows,which means I have to see my project on chrome broswer**
[start_log.txt](https://github.com/wailsapp/wails/files/8714406/start_log.txt)

I Guess the wails hide the key error. I cant find what happended !

**Comment by leaanthony** [comment] 2022-05-18 09:15
This looks like it's crashing in your own code "GetRuntimeInfo"

**Comment by non-one** [comment] 2022-05-18 09:30
When I change go code. the frontend code will also be rebuild? Because in `GetRuntimeInfo`  I use a variable which has been assigned a value in `startup func`. Frontend use `GetRuntimeInfo`  in onMounted(). So I have a question: when wails trigger rebuild, the frontend will start before app.startup?

**Comment by non-one** [comment] 2022-05-18 14:17
I am back. Because something worse. I run `wails build` and get the *.exe. But when I open executable file, nothing happend, no window #1305. `wails dev`works randomly and I can see the window. So I try to init another app from https://github.com/misitebao/wails-template-vue and find out that I can see the window after click the exe But `wails dev` not work, strange bug with no crash info. Tired...

**Comment by leaanthony** [comment] 2022-07-21 12:54
Closing this as it's old. Please reopen if you can provide more info.

**Closed** 2022-07-21 12:54 UTC
Labels: Bug, cannot reproduce, v2

**Comment by Osbornnnnn** [comment] 2022-09-04 20:14
I have this problem too. Tommorow i am give example code

![image](https://user-images.githubusercontent.com/36417885/188331794-fac30964-8b63-46d9-948e-c6f9eb08a43f.png)

**Comment by Osbornnnnn** [comment] 2022-09-04 20:15
I have this problem too. Tommorow i am give example code
![image](https://user-images.githubusercontent.com/36417885/188331827-d879b5a6-0856-47e4-aa84-061a520a88ce.png)
