### ISSUE TITLE
Wails WIndows app is recognized as Trojan

### ISSUE THREAD

**Issue by jkasperkiewicz** [wailsapp/wails#3130] opened 2023-12-14 14:53 UTC
### Description

After upgrading to Wails 2.7.1 application created by the compiler is recognized as Trojan under Windows.

The compiler command:
`wails build -ldflags='-s -w -X "main.version=$(VERSION)"' --platform windows/amd64`

### To Reproduce

It is hard to reproduce. I have quite big application.

go.mod

```
go 1.21

toolchain go1.21.5

require (
	github.com/mattn/go-sqlite3 v1.14.18
	github.com/pressly/goose/v3 v3.16.0
	github.com/wailsapp/wails/v2 v2.7.1
	go.uber.org/fx v1.20.1
)

require (
	github.com/bep/debounce v1.2.1 // indirect
	github.com/davecgh/go-spew v1.1.2-0.20180830191138-d8f796af33cc // indirect
	github.com/go-ole/go-ole v1.2.6 // indirect
	github.com/godbus/dbus/v5 v5.1.0 // indirect
	github.com/google/uuid v1.4.0 // indirect
	github.com/jchv/go-winloader v0.0.0-20210711035445-715c2860da7e // indirect
	github.com/labstack/echo/v4 v4.10.2 // indirect
	github.com/labstack/gommon v0.4.0 // indirect
	github.com/leaanthony/go-ansi-parser v1.6.0 // indirect
	github.com/leaanthony/gosod v1.0.3 // indirect
	github.com/leaanthony/slicer v1.6.0 // indirect
	github.com/leaanthony/u v1.1.0 // indirect
	github.com/mattn/go-colorable v0.1.13 // indirect
	github.com/mattn/go-isatty v0.0.20 // indirect
	github.com/pkg/browser v0.0.0-20210911075715-681adbf594b8 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	github.com/pmezard/go-difflib v1.0.1-0.20181226105442-5d4384ee4fb2 // indirect
	github.com/rivo/uniseg v0.4.4 // indirect
	github.com/samber/lo v1.38.1 // indirect
	github.com/sethvargo/go-retry v0.2.4 // indirect
	github.com/stretchr/testify v1.8.4 // indirect
	github.com/tkrajina/go-reflector v0.5.6 // indirect
	github.com/valyala/bytebufferpool v1.0.0 // indirect
	github.com/valyala/fasttemplate v1.2.2 // indirect
	github.com/wailsapp/go-webview2 v1.0.10 // indirect
	github.com/wailsapp/mimetype v1.4.1 // indirect
	go.uber.org/atomic v1.7.0 // indirect
	go.uber.org/dig v1.17.0 // indirect
	go.uber.org/multierr v1.11.0 // indirect
	go.uber.org/zap v1.23.0 // indirect
	golang.org/x/crypto v0.15.0 // indirect
	golang.org/x/exp v0.0.0-20230905200255-921286631fa9 // indirect
	golang.org/x/net v0.18.0 // indirect
	golang.org/x/sync v0.5.0 // indirect
	golang.org/x/sys v0.14.0 // indirect
	golang.org/x/text v0.14.0 // indirect
)
```

### Expected behaviour

To compile Windows safe application.

### Screenshots

<img width="232" alt="image" src="https://github.com/wailsapp/wails/assets/53968812/d264f528-9d81-4009-8ef9-ed6e1677d7ca">

### System Details

```shell
App has been compiled on Mac:

# Wails
Version | v2.7.1

# System
┌─────────────────────────┐
| OS           | MacOS    |
| Version      | 14.2     |
| ID           | 23C64    |
| Go Version   | go1.21.5 |
| Platform     | darwin   |
| Architecture | arm64    |
| CPU          | Unknown  |
| GPU          | Unknown  |
| Memory       | Unknown  |
└─────────────────────────┘

# Dependencies
┌─────────────────────────────────────────────────────────────────────┐
| Dependency                | Package Name | Status    | Version      |
| Xcode command line tools  | N/A          | Installed | 2405         |
| Nodejs                    | N/A          | Installed | 20.4.0       |
| npm                       | N/A          | Installed | 9.7.2        |
| *Xcode                    | N/A          | Installed | 15.1 (15C65) |
| *upx                      | N/A          | Installed | upx 4.1.0    |
| *nsis                     | N/A          | Installed | v3.09        |
└────────────────────── * - Optional Dependency ──────────────────────┘

# Diagnosis
 SUCCESS  Your system is ready for Wails development!

And it was run on Windows 11.
```

**Comment by stffabi** [comment] 2023-12-14 19:44
Thanks for using wails and reporting this.

This issue has been already been discussed several times in the past, lately in #3045. Unfortunately there's nothing we can do about that. It is a Go ecosystem problem and can be solved by code-signing your binaries with a valid CodeSign certificate.

**Comment by stffabi** [comment] 2023-12-14 19:45
Duplicate of #3045

**Closed by stffabi** 2023-12-14 19:45 UTC
Labels: Bug, v3

**Comment by jkasperkiewicz** [comment] 2023-12-14 20:19
It's strange, when I downgraded to Wails 2.7.0 the problem was gone.
