### ISSUE TITLE
[v2] Linux: Intermittent failure for desktop app to launch

### ISSUE THREAD

**Issue by lmeromy** [wailsapp/wails#1316] opened 2022-04-06 20:37 UTC
### Description

All dependencies are installed according to the documentation. Use the command "wails dev" to launch the desktop app, but no window appears. This only occurs intermittently with no discernable pattern or obvious trigger. 

### To Reproduce

In a Linux environment:
1. Install all dependencies
2. use 'wails dev' command
3. Sometimes the app launches normally, sometimes the following logs appear. 

### Expected behaviour

The app should launch normally. 

### Screenshots

See logs below: 
![image](https://user-images.githubusercontent.com/41759460/162065857-c068f0f1-6521-4f55-9985-a32f4fc635c8.png)

![image](https://user-images.githubusercontent.com/41759460/162065937-286e32cd-bd1b-4a60-b7b9-ec745a5b13d0.png)

![image](https://user-images.githubusercontent.com/41759460/162066077-c18bd835-33a3-4d0c-b03d-7dd109002d5f.png)

![image](https://user-images.githubusercontent.com/41759460/162066149-346a0058-bbc7-4b33-ad99-479312387913.png)

![image](https://user-images.githubusercontent.com/41759460/162066200-b297288b-1e83-4baf-a2f6-2dd69c017c23.png)

### System Details

```shell
System
------
OS:			Ubuntu
Version: 		20.04
ID:			ubuntu
Go Version:		go1.18
Platform:		linux
Architecture:		amd64
Package Manager: 	apt

Dependency	Package Name		Status		Version
----------	------------		------		-------
*docker		docker.io		Installed	20.10.13
gcc		build-essential		Installed	12.8ubuntu1.1
libgtk-3	libgtk-3-dev		Installed	3.24.20-0ubuntu1.1
libwebkit	libwebkit2gtk-4.0-dev	Installed	2.34.6-0ubuntu0.20.04.1
npm		npm			Installed	6.14.4+ds-1ubuntu2
*nsis		nsis			Available	3.05-2
pkg-config	pkg-config		Installed	0.29.1-0ubuntu4

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - nsis: sudo apt install nsis
```

**Comment by stffabi** [comment] 2022-04-07 04:50
Thanks for reporting this issue.

Looks like a duplicate of #1268. According to that issue, it should be fixed on master. Could you please give the latest master commit a try?
See also using [Bleeding Edge](https://wails.io/docs/next/guides/bleeding-edge)

**Comment by lmeromy** [comment] 2022-04-07 14:37
Thanks @stffabi I gave that a try, and unfortunately that did not solve the issue.

**Comment by napalu** [comment] 2022-04-07 15:34
Okay - I originally reported #1268 - I was always concerned that the error might have been masked by something on the client side (the application using wails) - we closed the issue when I stopped being able to reproduce it with my setup - there is a potential fix for it - @lmeromy are you doing anything special in the main/startup of your application?

**Comment by napalu** [comment] 2022-04-07 16:15
@KoduIsGreat or just bung the contents of #1320 in your bleeding-edge wails clone it's 2 lines if that's less hassle :)

**Comment by lmeromy** [comment] 2022-04-07 16:29
@napalu I tried your fix and then restarted the app 8 times....seems good! I guess I could have gotten lucky 8 times in a row, so I will post if I see he issue again.

**Comment by leaanthony** [comment] 2022-04-07 20:41
I'll merge the fix. Thanks everyone for your input 🙏👍

**Closed** 2022-07-10 20:12 UTC
Labels: Bug, v3
