### ISSUE TITLE
how to multiple select folder? i need this

### ISSUE THREAD

**Issue by plane55** [wailsapp/wails#2986] opened 2023-10-15 14:37 UTC
### Describe the solution you'd like

how to multiple select folder

**Comment by leaanthony** [comment] 2023-10-15 18:40
https://github.com/wailsapp/wails/pull/2960

**Comment by plane55** [comment] 2023-10-16 00:45
怎么实现的呢？代码是什么？How to achieve it ? show achieve code

**Comment by plane55** [comment] 2023-10-16 03:28
> #2960

i don't know how to achieve it ?

**Comment by leaanthony** [comment] 2023-10-16 07:13
Duplicate of #2411

**Closed by leaanthony** 2023-10-16 07:13 UTC
Labels: Enhancement, v3

**Comment by plane55** [comment] 2023-10-17 03:15
if don't have this select multiple folder I can't finish my application
