### ISSUE TITLE
[v2] Monteray (MacOS 12.0.1) Compatibility Issues

### ISSUE THREAD

**Issue by KoduIsGreat** [wailsapp/wails#935] opened 2021-11-11 16:59 UTC
**Description**
When using Dialogs on Mac Monteray a warning popup saying the open failed, (this happens both with OpenFileDialog and OpenDirectoryDialog)
error output:
```
021-11-11 11:39:06.158 waterfall-dev-darwin-arm64[4414:100468] *** Assertion failure in -[NSOpenPanel beginServicePanel:asyncExHandler:], NSVBOpenAndSavePanels.m:1907
2021-11-11 11:39:06.159 waterfall-dev-darwin-arm64[4414:100468] -[NSSavePanel beginSheetModalForWindow:completionHandler:]_block_invoke caught non-fatal NSInternalInconsistencyException '<NSOpenPanel: 0x135036f40> is attempting to advance this Open/Save panel to run phase while another self.advanceToRunPhaseCompletionHandler is in waiting for a previous attempt. An Open/Save panel cannot start to advance more than once.' with user dictionary {
    NSAssertFile = "NSVBOpenAndSavePanels.m";
    NSAssertLine = 1907;
} and backtrace (
        0   CoreFoundation                      0x00000001b0c2c12c __exceptionPreprocess + 240
        1   libobjc.A.dylib                     0x00000001b097d808 objc_exception_throw + 60
        2   Foundation                          0x00000001b1b58324 -[NSCalendarDate initWithCoder:] + 0
        3   AppKit                              0x00000001b412ac90 -[NSSavePanel beginServicePanel:asyncExHandler:] + 512
        4   AppKit                              0x00000001b412c140 -[NSSavePanel runModal] + 332
        5   waterfall-dev-darwin-arm64          0x0000000105696478 __41-[WailsContext OpenFileDialog:::::::::::]_block_invoke.328 + 36
        6   libdispatch.dylib                   0x00000001b0920e60 _dispatch_call_block_and_release + 32
        7   libdispatch.dylib                   0x00000001b0922bac _dispatch_client_callout + 20
        8   libdispatch.dylib                   0x00000001b09310ac _dispatch_main_queue_callback_4CF + 944
        9   CoreFoundation                      0x00000001b0bede60 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
        10  CoreFoundation                      0x00000001b0bab820 __CFRunLoopRun + 2540
        11  CoreFoundation                      0x00000001b0baa694 CFRunLoopRunSpecific + 600
        12  HIToolbox                           0x00000001b9720990 RunCurrentEventLoopInMode + 292
        13  HIToolbox                           0x00000001b9720704 ReceiveNextEventCommon + 552
        14  HIToolbox                           0x00000001b97204c4 _BlockUntilNextEventMatchingListInModeWithFilter + 72
        15  AppKit                              0x00000001b36ffaec _DPSNextEvent + 844
        16  AppKit                              0x00000001b36fe390 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1332
        17  AppKit                              0x00000001b36f03b0 -[NSApplication run] + 596
        18  waterfall-dev-darwin-arm64          0x000000010569382c Run + 272
        19  waterfall-dev-darwin-arm64          0x0000000105691430 _cgo_43b532242a4e_Cfunc_Run + 36
        20  waterfall-dev-darwin-arm64          0x0000000105008afc runtime.asmcgocall + 124
)

```

**To Reproduce**
Steps to reproduce the behaviour:

I've created a repo, that fails for me on my mac, but works on windows
https://github.com/KoduIsGreat/wails-v2-mac-os-dialog-issue

1. Clone repo
2. run wails dev
3. Click on the greet button

**Expected behaviour**
The dialog should open.

**Screenshots**
![Screen Shot 2021-11-11 at 11 39 35 AM](https://user-images.githubusercontent.com/13248655/141336556-ede19b83-7a03-429c-b520-e81c9b2015e3.png)

**System Details**
Wails CLI v2.0.0-beta.20

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             MacOS
Version:        12.0.1
ID:             199506
Go Version:     go1.17.2
Platform:       darwin
Architecture:   arm64

**Additional context**

- [ ] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment] 2021-11-11 19:31
AWESOME bug report. Thank you 🙏 I've been testing on Big Sur but can update over the weekend and test. Sounds like a permissions issue.

**Comment by leaanthony** [comment] 2021-11-11 19:35
Looks like it's a wider problem https://github.com/corpnewt/ProperTree/issues/111

**Comment by leaanthony** [comment] 2021-11-11 19:42
Try explicitly setting the default directory in the options and see what happens.

**Comment by KoduIsGreat** [comment] 2021-11-11 20:32
```go
// Greet returns a greeting for the given name
func (b *App) Greet(name string) string {
	path, err := runtime.OpenFileDialog(b.ctx, runtime.OpenDialogOptions{
		DefaultDirectory:           "test",
		DefaultFilename:            "test.txt",
		Title:                      "test",
		Filters:                    nil,
		AllowFiles:                 true,
		AllowDirectories:           true,
		ShowHiddenFiles:            false,
		CanCreateDirectories:       false,
		ResolvesAliases:            false,
		TreatPackagesAsDirectories: false,
	})
	if err != nil {
		runtime.LogError(b.ctx, err.Error())
	}
	return fmt.Sprintf("Hello %s, you opened this %s", name, path)
}
```
Still produces the above error

**Comment by leaanthony** [comment] 2021-11-12 11:00
Then let's see what comes out of all the tickets on Apple support

**Comment by leaanthony** [comment] 2021-11-12 19:29
Have confirmed by upgrading to Monterey. I think Apple has dropped the ball on this because there appears to be an unannounced API change to the Open dialog that is affecting a ton of projects and applications. What's worse is that xcode doesn't indicate the API change either. It looks like it's to do with thefilters and dropping support for `allowedFileTypes`, but using `allowedContentTypes` also throws an error.

Still investigating

**Comment by KoduIsGreat** [comment] 2021-11-13 14:26
Thanks! 👍🏻

**Comment by leaanthony** [comment] 2021-11-15 10:27
Lots of info here: https://bugs.python.org/issue44828

**Comment by leaanthony** [comment] 2021-11-16 07:56
There's a fix on `master` @KoduIsGreat. I've only tested on M1 12.0 so if you are able to, it would be amazing to test on earlier MacOS/Intel. Don't forget to update your `replace` line in your project.

**Comment by leaanthony** [comment] 2021-11-16 09:23
Just tested with High Sierra and it looks good 👍

**Comment by KoduIsGreat** [comment] 2021-11-16 16:06
@leaanthony  thanks, ill try it out !

**Comment by KoduIsGreat** [comment] 2021-11-16 18:17
@leaanthony I just tested against master in my test repo, i get a different issue now, the dialog pops up and then goes away and this is logged via wails: 
```
021-11-16 13:08:02.755 test-dev-darwin-arm64[36233:2936779]  is not a valid allowedFileType because it cannot be converted to a UTType
```
The greet fn:
```go
func (b *App) Greet(name string) string {
	path, err := runtime.OpenFileDialog(b.ctx, runtime.OpenDialogOptions{
		DefaultDirectory:           "test",
		DefaultFilename:            "test.txt",
		Title:                      "test",
		Filters:                    nil,
		AllowFiles:                 true,
		AllowDirectories:           true,
		ShowHiddenFiles:            false,
		CanCreateDirectories:       false,
		ResolvesAliases:            false,
		TreatPackagesAsDirectories: false,
	})
	if err != nil {
		runtime.LogError(b.ctx, err.Error())
	}
	return fmt.Sprintf("Hello %s, you opened this %s", name, path)
}
```

It seems like it doesn't like the nil `Filters` I tried setting them to the following and got different errors:
```go
	path, err := runtime.OpenFileDialog(b.ctx, runtime.OpenDialogOptions{
		DefaultDirectory:           "test",
		DefaultFilename:            "test.txt",
		Title:                      "test",
		Filters:                    []runtime.FileFilter {
			{
				DisplayName: "db files",
				Pattern:     ".db",
			},
		},
		AllowFiles:                 true,
		AllowDirectories:           true,
		ShowHiddenFiles:            false,
		CanCreateDirectories:       false,
		ResolvesAliases:            false,
		TreatPackagesAsDirectories: false,
	})
```
error:
```
2021-11-16 13:14:54.811 test-dev-darwin-arm64[36592:2946325] .db is not a valid allowedFileType because it cannot be converted to a UTType
2021-11-16 13:15:00.398 test-dev-darwin-arm64[36592:2946325] -[NSSavePanel beginSheetModalForWindow:completionHandler:]_block_invoke caught non-fatal NSObjectNotAvailableException 'The operation couldn’t be completed. (com.apple.ViewBridge error 16.)' with user dictionary {
    error = "Error Domain=com.apple.ViewBridge Code=16 \"(null)\" UserInfo={com.apple.ViewBridge.error.hint=advance to run phase, com.apple.ViewBridge.error.description=NSViewBridgeInvalidError}";
} and backtrace (null)

```
also tired with the pattern being `*.db` no error gets reported but dialog just disappears immediately

**Comment by KoduIsGreat** [comment] 2021-11-16 18:18
also fwiw, i tried with empty dialog options as well, similar results

**Comment by leaanthony** [comment] 2021-11-16 18:55
Interesting. I tried with a blank options struct and it work. The filter types is a known thing for 11+ but as it worked on mine I assumed it was deprecated, not broken. Thanks for testing, will address tonight if I get time

**Comment by leaanthony** [comment] 2021-11-17 10:13
@KoduIsGreat - Just pushed fixes to master. Tested with nil filters + 1 *.jpg filter and both worked as expected. I'm not sure whether wails will let you compile on anything less than MacOS 11 as it now links against `-framework UniformTypeIdentifiers`. It isn't clear to me if this will just be ignored by clang.

**Comment by KoduIsGreat** [comment] 2021-11-17 13:33
@leaanthony Sorry i only have this M1, 

However i'm still seeing the last issue i mentioned above with the new changes from master

With the following code 
```go
func (b *App) Greet(name string) string {
	path, err := runtime.OpenFileDialog(b.ctx, runtime.OpenDialogOptions{
		Filters:                    []runtime.FileFilter {
			{
				DisplayName: "jpg files",
				Pattern:     "*.jpg",
			},
		},
	})
	if err != nil {
		runtime.LogError(b.ctx, err.Error())
	}
	return fmt.Sprintf("Hello %s, you opened this %s", name, path)
}
```
no errors are thrown, but the dialog disappears quickily 

just to make sure i'm using master right, I cloned the wails repository and updated the replace to this 
`replace github.com/wailsapp/wails/v2 v2.0.0-beta.20 => /Users/aashelt/repos/wails/v2` correct?

**Comment by leaanthony** [comment] 2021-11-18 18:17
Yeah weird. Totally works for me:

https://user-images.githubusercontent.com/1943904/142367714-fa7f2126-9b2b-400c-a67b-afe4768e1222.mov

**Comment by KoduIsGreat** [comment] 2021-11-18 19:07
@leaanthony Ahh.... i see

so i was running wails dev, not wails build. If i run wails build and run the binary it works just fine however, wails dev the issue persists. hopefully this helps!

**Comment by leaanthony** [comment] 2021-11-18 19:24
Ah...wow, why would that be any different?  Will investigate

**Comment by leaanthony** [comment] 2021-11-18 19:26
I noticed fullscreen also is playing up in Monterey. Is that true for you too?

**Comment by KoduIsGreat** [comment] 2021-11-18 19:35
I haven't noticed that, what do you mean specifically?

**Comment by leaanthony** [comment] 2021-11-18 20:14
Set an app to be fullscreen and it fails to start fullscreen. Worked perfectly on Big Sur. Do you mind if I change the title of this ticket to Monterey Compatibility issues?

**Comment by KoduIsGreat** [comment] 2021-11-18 21:41
@leaanthony go ahead! :) I can try and see if there are any other wonkyness with menus etc.

**Comment by leaanthony** [comment] 2021-11-20 04:09
Did some digging into this. It's such a weird bug: simply moving the app from bin to the .app directory and it won't run. It even crashed lldb 🤔

**Comment by leaanthony** [comment] 2021-11-22 10:25
Made progress on fullscreen tonight. I think this affects all versions so not sure it belongs in this ticket. It's basically there, just some interesting size constraints issue to fix.

**Comment by leaanthony** [comment] 2021-11-23 10:07
Ok, so I've "fixed" this issue. It's the weirdest thing and I'm not 100% sure *why* it's fixed. Turns out, if you run the binary from a bundle, the dialogs work! Presumably this is why the main build works too. I suspect it's permissions because you can copy the dev binary into a bundle and it works. Anyway, fix on `master`. Let me know how you go.

**Comment by KoduIsGreat** [comment] 2021-11-23 15:49
Thanks for the hard work @leaanthony  i'll test shortly :)

**Comment by KoduIsGreat** [comment] 2021-11-29 14:06
@leaanthony  still no luck for me :(

**Comment by leaanthony** [comment] 2021-11-29 18:54
How strange. Is this Monterey on Intel?

**Comment by KoduIsGreat** [comment] 2021-11-29 20:48
nope :/
OS: MacOS
Version: 12.0.1
ID: 199506
Go Version: go1.17.2
Platform: darwin
Architecture: arm64

**Comment by leaanthony** [comment] 2021-11-29 21:10
What are the steps to reproduce from scratch based on the last release?

**Comment by KoduIsGreat** [comment] 2021-12-06 15:10
@leaanthony this is fixed, my bad.. I updated everything except the wails cli binary so now running on .21 everythings working great! thanks :)

**Comment by leaanthony** [comment] 2021-12-06 19:11
Did you set `AllowFiles` to `true`?

**Comment by KoduIsGreat** [comment] 2021-12-06 20:06
Got it. thanks, seems like everything is working.

**Comment by leaanthony** [comment] 2021-12-06 20:57
It's annoying but what would be the alternative? If nothing is set then make it default to files? How is there even a use case for not selecting either on both Windows and Mac?!? I ended up going for explicit and no hidden logic.

**Comment by KoduIsGreat** [comment] 2021-12-07 14:19
Yeah, that makes sense. I guess the only alternative is keep the bool around but invert its name so the default value of 'false' provides access to files, but thats probably more confusing. although now it doesn't really seem that theres any difference at all between openFile and openDirectory dialogs.

**Comment by stffabi** [comment] 2021-12-07 15:10
AFAIK, currently `OpenDirectoryDialog` ignores the flags `AllowFiles`/`AllowDirectories` and uses `false`/`true` for those, whereas  `OpenFileDialog` and `OpenMultipleFilesDialog` takes the flags into account.

Shouldn't we try to make sure that the platforms behave the same way as much as possible? The following code works as expected on Windows (opens a dialog to select a file) whereas on macOS it's impossible to select any file. From the perspective of a Wails's user this might be confusing.

```go
	path, err := runtime.OpenFileDialog(b.ctx, runtime.OpenDialogOptions{})
```

**Comment by leaanthony** [comment] 2021-12-07 19:18
Perhaps we should just get rid of those flags

**Comment by stffabi** [comment] 2021-12-07 20:10
I think it would be fine removing the flags.

**Comment by KoduIsGreat** [comment] 2021-12-08 19:30
👍🏻

**Comment by KoduIsGreat** [comment] 2021-12-14 18:42
@leaanthony  yet another bug on monteray (I think) related to dialogs, Save dialog on monteray doesn't seem to give me the option to save.

**Comment by leaanthony** [comment] 2021-12-15 08:29
Great pick up. Fixed on `master`, will release v2.0.0-beta.23 tonight.

**Comment by leaanthony** [comment] 2021-12-15 08:48
https://github.com/wailsapp/wails/releases/tag/v2.0.0-beta.23

**Comment by KoduIsGreat** [comment] 2021-12-15 17:49
nice, will test it soon
another issue i noticed is that text for submenus doesn't display

**Comment by leaanthony** [comment] 2021-12-15 20:36
Monteray - the gift that keeps on giving :-)

**Comment by KoduIsGreat** [comment] 2021-12-16 15:10
@leaanthony i updated to v2.0.0-beta.23 and save dialog doesn't look any different for me

**Comment by leaanthony** [comment] 2021-12-16 18:46
Please post your code. It's working great here.

**Comment by leaanthony** [comment] 2021-12-16 19:40
Just checking, you updated your project to use. 23 right?

**Comment by KoduIsGreat** [comment] 2021-12-17 13:53
@leaanthony correct, the head of https://github.com/KoduIsGreat/wails-v2-mac-os-dialog-issue
has an example that does not work for me. I might be a total mac noob, so please forgive me, but the dialog doesn't look any different for me from the open dialog. things like setting a title or default file dont seem to have any visible effect on the dialog either (not a huge deal but would expect it to). below is a screen shot of what it looks like for me.
![Screen Shot 2021-12-17 at 8 50 33 AM](https://user-images.githubusercontent.com/13248655/146554456-9af84987-1997-4e24-a6fb-d13b9ce85728.png)

**Comment by syddo** [comment] 2021-12-18 16:20
> Yeah weird. Totally works for me:
> 
>  dialogs.mov

out of topic question.. which Jetbrains IDE is being used here?

**Comment by leaanthony** [comment] 2021-12-18 19:23
> @leaanthony correct, the head of https://github.com/KoduIsGreat/wails-v2-mac-os-dialog-issue
> has an example that does not work for me. I might be a total mac noob, so please forgive me, but the dialog doesn't look any different for me from the open dialog. things like setting a title or default file dont seem to have any visible effect on the dialog either (not a huge deal but would expect it to). below is a screen shot of what it looks like for me.
> ![Screen Shot 2021-12-17 at 8 50 33 AM](https://user-images.githubusercontent.com/13248655/146554456-9af84987-1997-4e24-a6fb-d13b9ce85728.png)
> 
> 

I can see that you do have files there that are selectable. I'd noticed the title thing as well. I think they dropped showing that text. Is there anything in the save dialog that's now an issue?

**Comment by KoduIsGreat** [comment] 2021-12-20 15:51
I believe save dialog is fine, thanks for your patience :)

**Comment by leaanthony** [comment] 2022-03-06 10:18
@KoduIsGreat - Am I right in thinking there are now no outstanding compatibility issues here?

**Comment by KoduIsGreat** [comment] 2022-03-06 18:33
@leaanthony as far as I can tell with my recent tests everything seems to be ok

**Closed** 2022-03-06 19:24 UTC
Labels: Bug, awaiting feedback, WIP, TODO, v2
