### ISSUE TITLE
On v2.0.0 wails dev or build will fail if dist is not yet generated

### ISSUE THREAD

**Issue by olup** [wailsapp/wails#1900] opened 2022-09-25 12:37 UTC
### Description

In pipelines, or when I `dev`my project for the first time, the `frontend/dist` directory doesn't exists yet, or is empty. In such a sitution, `wails dev`or `wails build` will choke before even building the front, because the embed directory is missing.

It used to not be a problem, started after upgrading to the latest v2.0.0.

### To Reproduce

run `wails dev`

### Expected behaviour

`wails dev`or `build` should build the front end first and then build the go code and get the embed

### System Details

```shell
Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             MacOS
Version:        12.4
ID:             21F79
Go Version:     go1.19
Platform:       darwin
Architecture:   arm64

Wails
------
Version:        v2.0.0

Dependency                      Package Name    Status          Version
----------                      ------------    ------          -------
xcode command line tools        N/A             Installed       2395
npm                             N/A             Installed       8.19.1
*upx                            N/A             Available 
*nsis
```

**Comment by stffabi** [comment] 2022-09-25 12:59
Thanks for using Wails and reporting this.

Good catch, this seems to be a problem since generating the bindings before building has been introduced. The problem is the bindings can't be generated if the embed folder is missing, since we build the app for self generating the bindings. In order to build the frontend we also need the bindings generated beforehand, so that's a problem.

**Comment by olup** [comment] 2022-09-25 12:59
Errata : This is actually not working with the previous version I had (beta 42). I wonder what could have changed. FIY my repo is here https://github.com/olup/lunii-admin

**Comment by olup** [comment] 2022-09-25 13:05
Hum ok. As a workaround I am contemplating generating a dummy `frontend/dist` directory with an empty `.txt` file in my pipeline, however this is a very common situation - it should probably be addressed in the docs.

Could the bindings be generated from a build done with a build flag and place the embedding in a separate file that is conditional to the flag ? This is a bit ugly. Or have the CLI make sure that there is something in the directory beforehand ? But this directory is decided by the user in the code, the cli would'nt know what to look for I guess.

**Comment by olup** [comment] 2022-09-25 13:06
And, on a side note, thanks a lot for building wails.

**Comment by stffabi** [comment] 2022-09-25 13:09
There's already a build tag involved for building the bindings it is: `bindings`

So you use that in your case, but it would be great to have this addressed in a generic way for all users. Determining the folder is pretty hard and would involve static analysis, in some cases it could be maybe impossible.

**Comment by leaanthony** [comment] 2022-09-25 13:16
One solution is to scan the main.go source for the embed directly then just make the directory, the problem is that it might be in a different file. Another way is to do static analysis on the Bindings and remove the current bindings generation method. Considering we are aiming to support multiple windows that have the potential to have different assets, I'm more inclined to do the static analysis as the bindings should only ever exist in the main config

**Comment by olup** [comment] 2022-09-25 13:19
I think target DX is : there is no dist directory - no one should be gitting the dist. 
So it is doomed to fail in pipelines. 
Keeping a placeholder file there is not even possible as the wails cli will rewrite the directory on dev.
I'll try the build flag route, and this should probably become a default in templates ?

**Comment by olup** [comment] 2022-09-25 13:22
build flags works perfect anyway :-)

**Comment by leaanthony** [comment] 2022-09-26 10:18
What do we need to action on this ticket?

**Comment by olup** [comment] 2022-09-26 13:56
I am not sure.
It could be making a note of this in the doc
It could be updating the templates with the build tag protection as
non-gited dist dirsctory is the default practice.
What do you think ?

Le lun. 26 sept. 2022 à 12:18, Lea Anthony ***@***.***> a
écrit :

**Comment by sunshine69** [comment] 2022-09-30 10:21
I hit this problems when building on my macos as well, however on Ubuntu it does not have problems.
I fixed it by mkdir buid/dist and touch build/dist/.txt however it does not provide out of the box working experience.

so not sure what you guys need to do but whatever it is we should make it work without the need to do things that is not in the doc.

Thanks

**Comment by olup** [comment] 2022-09-30 10:46
For refrence,this is how I do it:
https://github.com/olup/lunii-admin/blob/main/embed-empty.go
https://github.com/olup/lunii-admin/blob/main/embed.go

**Comment by bearsh** [comment] 2022-10-05 07:50
if I'm not wrong, the `frontend/dist` folder gets recreated during the build. so one simple solution is to simple populate it with a dummy file during binding generation if the folder is empty...

**Comment by stefpap** [comment] 2022-10-10 17:38
Hello, not yet sure if I'm facing the exact same issue. When building on docker with v2.0.0 cli i get the following error.

```
#10 0.219 GOOS=windows GOARCH=386 wails build -platform windows -debug -ldflags "-w -s -H windowsgui" -o launcher.exe
#10 0.230 Wails CLI v2.0.0
#10 0.230 
#10 0.231 App Type: 		desktop
#10 0.231 Platforms: 		windows
#10 0.231 Compiler: 		/usr/local/go/bin/go
#10 0.231 Skip Bindings: 		false
#10 0.231 Build Mode: 		Debug
#10 0.231 Obfuscated: 		false
#10 0.231 Skip Frontend: 		false
#10 0.231 Compress: 		false
#10 0.231 Package: 		true
#10 0.232 Clean Build Dir: 	false
#10 0.232 LDFlags: 		"-w -s -H windowsgui"
#10 0.232 Tags: 			[]
#10 0.232 Race Detector: 		false
#10 0.232 Output File: 		launcher.exe
#10 0.232 
#10 0.233 Building target: windows/386
#10 0.233 ----------------------------
#10 0.233   - Generating bindings: Error: 
#10 26.48 
#10 26.48 fork/exec /tmp/wailsbindings: no such file or directory
```

However, if I downgrade the cli version to `v2.0.0-beta.44.2` building works as expected. Do you think this might be related?

**Comment by stffabi** [comment] 2022-10-10 18:06
@stefpap I suspect your problem is more related to #1921.

Could you try to remove the GOOS/GOARCH from your command and just use '-platform windows/386' ?

**Comment by stefpap** [comment] 2022-10-10 19:18
@stffabi You are right! Thank you for pointing me in the right direction.
Removing the GOOS/GOARCH produces other errors since I'm cross compiling from linux to windows as well. But I'll keep looking into this, and update the other issue if I spot anything

**Comment by stffabi** [comment] 2022-10-10 19:21
@stefpap you shouldn't get any errors in your case since you arent't cross compiling with a custom c compiler lile the author of the other issue.
I'm doing this all the time for windows without any problems, can you please post your errors over there in the other issue?

**Comment by leaanthony** [comment] 2022-10-16 10:34
Please try the above PR to see if this fixes your problem. If you are unsure how to do this, please follow [this guide](https://wails.io/docs/guides/bleeding-edge#testing-a-pr). Let us know how you get on 👍

**Closed** 2022-10-16 12:08 UTC
Labels: Bug, Ready For Testing, v2
