### ISSUE TITLE
Cannot exit wails serve after executed Windows

### ISSUE THREAD

**Issue by TheNerdyHamster** [wailsapp/wails#159] opened 2019-07-15 15:11 UTC
**Description**

When I am executing wails serve in the cmd it won't let me exit it with CTRL-C or create a new serve. So to fix it right now I need either to find the program in task manager or restart the computer.

**To Reproduce**
1. Create a new project with wails.
2. Run `wails serve`
3. Try to exit it with CTRL-C

**Expected behavior**
I expect it to exit and stop wails backend.

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.0 |
| Go Version    | go1.12.5 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |

**Comment by leaanthony** [comment] 2019-07-18 10:46
Thanks for opening this. Will check it out as soon as we can.

**Comment by leaanthony** [comment] 2019-07-24 08:12
Update: this weekend is Windows bug fixing

**Comment by Lilahamstern** [comment] 2019-08-04 11:08
> Update: this weekend is Windows bug fixing

Do we have any update on this?

**Comment by leaanthony** [comment] 2019-08-04 22:02
Hi @Lilahamstern. I did spend some time on it. The issue is the way windows handles signals is different to Mac/Linux. I was able to reproduce it and it's irrittating as hell! Please test the latest prerelease using `wails update -pre` and try again. Let us know how it goes... 👍

**Comment by Lilahamstern** [comment] 2019-08-05 09:04
Hi, @leaanthony. I tested it a bit this morning. Dident see any diffrence. Will try again later when I am home, to verify it was the correct version.

**Comment by leaanthony** [comment] 2019-08-24 05:15
Any updates?

**Comment by leaanthony** [comment] 2019-09-01 06:02
I looked at this again today. There's something weird going on around the area of signal handling on windows if you exec an external binary. The way serve works is this:

- compile project with a special flag to indicate that it should serve the backend in headless mode
- exec the resultant binary 

Even with all the signal handling code in place, ctrl-c never gets picked up after execing the binary. I also looked at `cmd.Start` as an alternative but nothing. It's like the signals get lost somewhere.

**Comment by leaanthony** [comment] 2019-10-28 21:00
This should be fixed by the latest pre-release. `wails update -pre` to get it. Please let us know how you get on.

**Comment by leaanthony** [comment] 2019-10-28 21:00
Closed in error.

**Comment by leaanthony** [comment] 2019-11-05 19:41
Closed due to inactivity

**Closed by leaanthony** 2019-11-05 19:41 UTC
Labels: Bug, v3
