### ISSUE TITLE
 Crosscompiling to Mac not currently supported.

### ISSUE THREAD

**Issue by tong-xiaolong** [wailsapp/wails#2462] opened 2023-03-07 06:56 UTC
### Description

![image](https://user-images.githubusercontent.com/122947448/223346505-458b87ca-6852-4edb-9ab1-fc491073ef3f.png)
无论是本地构建还是github action 都构建不成功

### To Reproduce

wails build --platform darwin/universal -webview2 download 

### Expected behaviour

构建成功

### System Details

```shell
PS D:\golong\新建文件夹\EasyHost> wails doctor  
DEB | Using go webview2loader
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Windows 10 Pro
Version      | 2009 (Build: 22621)
ID           | 22H2
Go Version   | go1.20.1
Platform     | windows
Architecture | amd64

# Wails

Version | v2.3.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 110.0.1587.63
npm        | N/A          | Installed | 8.3.1
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by stffabi** [comment] 2023-03-07 08:51
Thanks for using Wails and opening this enhancement request. 

We do not currently support cross compilation to something other than Windows. But it's on the roadmap, we would love to see you joining the discussion in #1041.

**Comment by stffabi** [comment] 2023-03-07 08:51
Duplicate of #1041

**Closed** 2023-03-07 08:52 UTC
Labels: Bug, v2
