### ISSUE TITLE
Events cancellation callback not being returned when using imports

### ISSUE THREAD

**Issue by badarsebard** [wailsapp/wails#2225] opened 2022-12-21 04:54 UTC
### Description

The [documentation](https://wails.io/docs/reference/runtime/events) describes the EventsOn function returning a callback that can be used to cancel the listener. In my current build, this function is not being returned in my frontend. After examining the `runtime.js` I have found the following:

```js
export function EventsOnMultiple(eventName, callback, maxCallbacks) {
    window.runtime.EventsOnMultiple(eventName, callback, maxCallbacks);
}

export function EventsOn(eventName, callback) {
    EventsOnMultiple(eventName, callback, -1);
}
```

So it looks like the the functions being exported are invoking the function from the window runtime but not returning the new cancellation callback. I get the correct behavior in my frontend code when I use `window.runtime.EventsOn` but not if I'm using an import statement such as `import * as runtime from "../wailsjs/runtime";` and invoking with `runtime.EventsOn`.

### To Reproduce

Import the runtime as a module
```js
import * as runtime from "../wailsjs/runtime";
```

Invoke the EventsOn function
```js
let cancelCallback = runtime.EventsOn("eventname", () => {});
cancelCallback();
```

Invocation fails with error that `undefined` is not a function.

### Expected behaviour

EventsOn works whether invoking with `window.runtime.EventsOn` or through the use of imports.

### System Details

```shell
Wails CLI v2.2.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Pop!_OS
Version:        22.04
ID:             pop
Go Version:     go1.19.1
Platform:       linux
Architecture:   amd64

Wails
------
Version:                v2.2.0
Package Manager:        apt

Dependency      Package Name            Status          Version
----------      ------------            ------          -------
*docker         docker.io               Installed       20.10.21
gcc             build-essential         Installed       11.3.0
libgtk-3        libgtk-3-dev            Installed       3.24.33-1ubuntu2
libwebkit       libwebkit2gtk-4.0-dev   Installed       2.38.2-0ubuntu0.22.04.2
npm             npm                     Installed       8.6.0
*nsis           nsis                    Installed       v3.08-2
pkg-config      pkg-config              Installed       0.29.2

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
```

**Comment by leaanthony** [comment] 2022-12-21 07:41
Hi! Thanks for using Wails and opening this ticket. This was a recent addition so leave it with us to work out what's happened 👍

**Comment by derhasi** [comment] 2023-01-31 12:37
Just asked myself the same.

Looks to me like it is caused by https://github.com/wailsapp/wails/blob/0a32c1124e1df87e8d1658fcd8641d1f6c312c16/v2/internal/frontend/runtime/wrapper/runtime.js not using a `return` for most of the methods.

**Comment by leaanthony** [comment] 2024-11-18 09:55
This was fixed a while back. Closing.

**Closed by leaanthony** 2024-11-18 09:55 UTC
Labels: Bug, investigating, v3
