### ISSUE TITLE
[V2]: Error on "wails dev" with go 1.19

### ISSUE THREAD

**Issue by ulrichSchreiner** [wailsapp/wails#1690] opened 2022-08-03 10:35 UTC
### Description

when using go 1.19 the command `wails dev` fails to compile the go code

~~~
❯ go version
go version go1.19 linux/amd64
❯ wails dev
Wails CLI v2.0.0-beta.42

Executing: go mod tidy -compat=1.17
Executing: wails generate module
Installing frontend dependencies...
Running frontend DevWatcher command: 'npm run dev'
Building application for development...
  - Installing frontend dependencies: Done.
  - Compiling frontend: npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.

> frontend@0.0.0 dev
> vite

(⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠦ : timing config:load:flatten Completed in 2ms
  vite v2.9.14 dev server running at:

Vite Server URL: http://localhost:3000/
  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 187ms.

Done.⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠦ : timing config:load:flatten Completed in 2ms
invalid value "\"all=-N -l\"" for flag -gcflags: parameter may not start with quote character "
usage: go build [-o output] [build flags] [packages]
Run 'go help build' for details.
~~~

using go 1.18, everything works. 

`wails build` works fine

### To Reproduce

install go 1.19 and try to use `wails dev`

### Expected behaviour

the app should start with a window which reloads/recompiles when saving code.

### System Details

```shell
Plase note: the shown go-version is **NOT** the go version i use for compiling, i think this is the version which was used to compile "wails".

❯ wails doctor
Wails CLI v2.0.0-beta.42

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Arch Linux
Version:        Unknown
ID:             arch
Go Version:     go1.18.4
Platform:       linux
Architecture:   amd64

Wails
------
Version:                v2.0.0-beta.42
Package Manager:        pacman

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
*docker         docker          Installed       1:20.10.17-1
gcc             gcc             Installed       12.1.0-3
libgtk-3        gtk3            Installed       1:3.24.34-1
libwebkit       webkit2gtk      Installed       2.36.4-2
npm             npm             Installed       8.15.1-1
pkg-config      pkgconf         Installed       1.8.0-1

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
```

**Comment by stffabi** [comment] 2022-08-03 10:53
Thanks for reporting this and using Wails.

This seems to be a duplicate of #1688 and has already been fixed on master.

**Closed** 2022-08-03 10:53 UTC
Labels: Bug, v2
