### ISSUE TITLE
希望心中系统消息通知等等系统级api

### ISSUE THREAD

**Issue by zk3151463** [wailsapp/wails#2532] opened 2023-03-27 03:14 UTC
### Is your feature request related to a problem? Please describe.

希望心中系统消息通知等等系统级api

### Describe the solution you'd like

希望心中系统消息通知等等系统级api

### Describe alternatives you've considered

希望心中系统消息通知等等系统级api

**Comment by stffabi** [comment] 2023-03-27 05:47
Thanks for using Wails and opening this enhancement request.

Translated by deepl:
> I hope the system message notification and other system-level api in mind

If you are referring to notifications support, there's already an issue for that and a draft PR. Please refer to #1788

**Comment by stffabi** [comment] 2023-03-27 05:48
Duplicate of #1788

**Closed by stffabi** 2023-03-27 05:48 UTC
Labels: Enhancement, v3
