### ISSUE TITLE
SQLite database cannot read data

### ISSUE THREAD

**Issue by 3090015134** [wailsapp/wails#3366] opened 2024-04-02 03:32 UTC
### Description

When obfuscated is set to true in the configuration file wails.json and garbleargs is set, the program built with wails build cannot read the data in the sqlite3 database

### To Reproduce

Configure obfuscated to true in the configuration file wails.json and set garbleargs

### Expected behaviour

Can read and write sqlite3 database normally

### System Details

```shell
# Wails
Version | v2.8.0

# System
┌───────────────────────────────────────────────────────────────────────────────────┐
| OS           | Windows 10 Enterprise                                              |
| Version      | 2009 (Build: 22635)                                                |
| ID           | 23H2                                                               |
| Go Version   | go1.21.6                                                           |
| Platform     | windows                                                            |
| Architecture | amd64                                                              |
| CPU          | Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz                          |
| GPU 1        | Virtual Display Device (Huawei) - Driver: 1.0.0.9                  |
| GPU 2        | NVIDIA GeForce MX350 (NVIDIA) - Driver: 31.0.15.5186               |
| GPU 3        | RayLink Virtual Display Adapter (Rayvision) - Driver: 1.0.2.0      |
| GPU 4        | Intel(R) UHD Graphics (Intel Corporation) - Driver: 27.20.100.8984 |
| Memory       | 16GB                                                               |
└───────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 123.0.2420.65 |
| Nodejs     | N/A          | Installed | 20.11.0       |
| npm        | N/A          | Installed | 10.2.4        |
| *upx       | N/A          | Available |               |
| *nsis      | N/A          | Available |               |
└─────────────── * - Optional Dependency ───────────────┘

# Diagnosis
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/
```

**Comment by leaanthony** [comment] 2024-04-02 08:00
Hi! It looks like you are trying to report a bug but haven't provided enough details. Please make sure your report includes: 
- Clear, reproducible steps that demonstrates the bug
- Please include the output of `wails doctor`

**Comment by fyonecon** [comment] 2024-04-02 11:37
我用IndexDB存储数据

**Comment by 3090015134** [comment] 2024-04-03 12:49
> Hi! It looks like you are trying to report a bug but haven't provided enough details. Please make sure your report includes:
> 
> * Clear, reproducible steps that demonstrates the bug
> * Please include the output of `wails doctor`

https://github.com/3090015134/test.git    

Here are the results from Wails Doctor：
![image](https://github.com/wailsapp/wails/assets/131777537/4ba0ae55-e857-4da1-9f8d-e47183867324)

**Comment by 3090015134** [comment] 2024-04-03 12:49
> 我用IndexDB存储数据

是的，我也考虑过。

**Comment by yibaiba** [comment] 2024-12-03 07:06
I also encountered this problem，when i use wails.exe build -windowsconsole -nsis  ,

my sql is `[0.258ms] [rows:0] SELECT * FROM system_services WHERE name = "halo" AND system_services.deleted_at IS NULL ORDER BY system_services.id LIMIT 1 `  ,

use wails.exe build -obfuscated -windowsconsole -nsis sql is 
`SELECT * FROM system_services WHERE name = "halo" AND system_services.aev_mbz_l_oksl_ IS NULL ORDER BY system_services.zca_jw_g3u_nm_h LIMIT 1

2024/12/03 15:04:08 [31;1m??:1 [35;1mSQL logic error: no such column: name (1)
[0m[33m[0.000ms] [34;1m[rows:0][0m SELECT * FROM `system_services` WHERE name = "halo" AND `system_services`.`aev_mbz_l_oksl_` IS NULL ORDER BY `system_services`.`zca_jw_g3u_nm_h` LIMIT 1

`  
Caused the software to crash！！！  How can I exclude specific fields to ensure they are not confused?

**Comment by leaanthony** [comment] 2024-12-03 09:25
You'll have to read up on the garble site. I don't know what your project is like, but an old version of the readme allowed you to indicate which structs not to garble: https://gitee.com/WZFlik/garble/blob/master/README.md?skip_mobile=true

**Comment by leaanthony** [comment] 2024-12-03 09:27
As this is an issue with the programs and garble itself, I'm going to close this issue. You're more likely to get help with questions on the discord server.

**Closed** 2024-12-03 09:27 UTC
Labels: Bug, v2

**Comment by yibaiba** [comment] 2024-12-03 11:47
> 您必须阅读 garble 网站。我不知道您的项目是什么样的，但旧版本的自述文件允许您指示哪些结构不应被混淆：[https://gitee.com/WZFlik/garble/blob/master/README.md ?skip_mobile=true](https://gitee.com/WZFlik/garble/blob/master/README.md?skip_mobile=true)

Thank you, I have solved this problem。 

`type Test struct {
	ID        uint           `json:"id" gorm:"primarykey;colum:id;"`
	Name    string `jgorm:"unique;type:varchar(255);column:name;"`
}

func (*Test) TableName() string {
	return "test"
}
func init() {
	var _ = reflect.TypeOf(Test{})
}
` 
Solve this problem after adding all the struct used by my grom to  ` var _ = reflect.TypeOf(Text{})`
