### ISSUE TITLE
[v2] Can the background be transparent?

### ISSUE THREAD

**Issue by ZeronoFreya** [wailsapp/wails#1296] opened 2022-03-29 13:50 UTC
# v2@latest

I can only make the window semi-transparent, but can I make it fully transparent?

![](https://raw.githubusercontent.com/ZeronoFreya/Gallery/master/tt.png)

I don't know if you understand it, and if not, I can't explain more

```
System
------
OS:             Windows 10 Home China              // win11
Version:        2009 (Build: 22000)
ID:             21H2
Go Version:     go1.17.6
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       99.0.1150.55
npm             N/A             Installed       8.3.0
*upx            N/A             Available
*nsis           N/A             Available
```

---

> I found a way, windows only
Use winapi to modify the window style

```golang

import (
"github.com/lxn/win"
)

// other code ...

func (a *App) startup(ctx context.Context) {
    hwnd := win.FindWindow(nil, syscall.StringToUTF16Ptr("Your App Title"))
    win.SetWindowLong(hwnd, win.GWL_EXSTYLE, win.GetWindowLong(hwnd, win.GWL_EXSTYLE)|win.WS_EX_LAYERED)
}
```

Disable WindowIsTranslucent

**Comment by misitebao** [comment] 2022-03-30 12:39
@leaanthony 
I understand the meaning of this question. At present, the webview part of the Wails application can only be semi-transparent, not fully transparent. He hopes that the webview part can be fully transparent.

**Comment by leaanthony** [comment] 2022-03-30 13:56
It can be fully transparent, but you're not providing any information that the ticket template requests, such as platform.

**Comment by misitebao** [comment] 2022-03-30 14:33
I have tested it many times on the windows platform, and it has always been impossible. I originally thought this was intentionally restricted.😂

**Comment by leaanthony** [comment] 2022-03-30 21:14
It's possible on Windows just not exposed. It's also supported if you're running windows preview. The problem is, there's no indication on this ticket what OS the poster is talking about.

**Comment by ZeronoFreya** [comment] 2022-04-01 03:05
> It's possible on Windows just not exposed. It's also supported if you're running windows preview. The problem is, there's no indication on this ticket what OS the poster is talking about.
> 
> If you are using v2, please include the output of wails doctor

It's my fault, I did forget to specify the platform
win11
Please see the question for details

**Comment by leaanthony** [comment] 2022-04-06 09:37
> If you are using v2, please include the output of wails doctor

**Comment by ZeronoFreya** [comment] 2022-04-06 12:34
> > If you are using v2, please include the output of wails doctor

I really don't understand what you want, wails doctor I've appended at the end of the question, or do you want to know the version number? Wails CLI v2.0.0-beta.34

Still say you want Dependency Package Name Status Version?
```
System
------
OS:             Windows 10 Home China
Version:        2009 (Build: 22000)
ID:             21H2
Go Version:     go1.17.6
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       100.0.1185.29
npm             N/A             Installed       8.3.0
*upx            N/A             Available
*nsis           N/A             Available
```

**Comment by NanoNik** [comment] 2022-06-12 14:14
I've met the same issue when tried to make my window background transparent. The solution provided in the first post (adding `WS_EX_LAYRED`) will work only if user have DWM composition enabled, if it is not - window will be invisible.

So before adding `WS_EX_LAYRED` you should check for composition enabled using `DwmIsCompositionEnabled`.

My initial goal was to make window borders rounded (on Windows 10 and below), as a workaround for PC's without DWM composition I used `SetWindowRgn`.

**Comment by leaanthony** [comment] 2022-06-14 09:19
Is this something you could consider making a PR for?

**Comment by NanoNik** [comment] 2022-06-24 22:10
@leaanthony I'll see what I can do with it in a few days

**Comment by leaanthony** [comment] 2022-10-19 11:24
@NanoNik still interested in this?

**Comment by NanoNik** [comment] 2022-10-23 04:51
@leaanthony Yes, I'm still intrested in this feature, actually I already use somewhat transparent window in production, but on some systems (especially running Windows 7) even with DWM enabled sometimes it's just doesn't work, so I'm not really sure how to fix or debug it. I was able to reproduce it in a VM only with DWM disabled.

**Comment by sohaha** [comment] 2023-03-31 12:41
Is it still impossible to achieve transparent windows on Windows?

**Comment by claudioluciano** [comment] 2023-04-28 02:13
any news on the transparent issue?
It's possible to the background be translucid at least ?

**Comment by leaanthony** [comment] 2023-08-03 22:42
This has been implemented for v3. If anyone wants to backport, please raise a PR 👍

**Closed by leaanthony** 2023-08-03 22:42 UTC
Labels: Enhancement, TODO, v3

**Comment by gunter423** [comment] 2024-05-14 21:35
Hello, we've been able to set full transparency on Windows 10 and Windows 11 with the following code :

```go
import (
"github.com/lxn/win"
)

// other code ...

func (a *App) startup(ctx context.Context) {
    hwnd := win.FindWindow(nil, syscall.StringToUTF16Ptr("Your App Title"))
    win.SetWindowLong(hwnd, win.GWL_EXSTYLE, win.GetWindowLong(hwnd, win.GWL_EXSTYLE)|win.WS_EX_LAYERED)
}
```
and set this in `main.go` : 

```go
err = wails.Run(&options.App{
...your_options,
BackgroundColour: &options.RGBA{R: 0, G: 0, B: 0, A: 0},
Windows: &windows.Options{
             WebviewIsTransparent: true,
             WindowIsTranslucent: false,
      }
})
```

**Comment by JadeVane** [comment] 2024-08-06 03:49
I am very happy to see that the effect I want to see is achieved on Windows, but now I want to ask a slightly off-topic question. Can parameters similar to WebviewIsTransparent be implemented on Linux? The current situation is that only the WindowIsTranslucent parameter is available, so in Linux , either create a window with both background color and shadow, or remove both, which means that if I want to create a window with rounded corners, I can only remove the background color and shadow at the same time, which means that I I want to implement the window shadow effect by myself, but in fact I did not find the parameters to implement the window shadow in [options](https://wails.io/zh-Hans/docs/reference/options), so I would like to know Are there any plans now to implement the WebviewIsTransparent parameter on Linux as well?

some necessary information below

```
# Wails
Version         | v2.9.1
Package Manager | apt   

# System
┌─────────────────────────────────────────────────────────────────────────────────┐
| OS           | Ubuntu                                                           |
| Version      | 22.04                                                            |
| ID           | ubuntu                                                           |
| Go Version   | go1.22.3                                                         |
| Platform     | linux                                                            |
| Architecture | amd64                                                            |
| CPU          | AMD Ryzen 5 PRO 4650U with Radeon Graphics                       |
| GPU          | Renoir (Advanced Micro Devices, Inc. [AMD/ATI]) - Driver: amdgpu |
| Memory       | 23GB                                                             |
└─────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌──────────────────────────────────────────────────────────────────────────┐
| Dependency | Package Name          | Status    | Version                 |
| *docker    | docker.io             | Installed | 24.0.7                  |
| gcc        | build-essential       | Installed | 12.9ubuntu3             |
| libgtk-3   | libgtk-3-dev          | Installed | 3.24.33-1ubuntu2.2      |
| libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.44.2-0ubuntu0.22.04.1 |
| npm        | npm                   | Installed | 10.5.0                  |
| *nsis      | nsis                  | Available | 3.08-2                  |
| pkg-config | pkg-config            | Installed | 0.29.2                  |
└──────────────────────── * - Optional Dependency ─────────────────────────┘

# Diagnosis
Optional package(s) installation details: 
  - nsis: sudo apt install nsis
```

**Comment by jrtp** [comment] 2024-08-18 12:49
Does not work for me, the window is always showing the background color set in main.go without the 0 alpha on windows 11. Is there something else that must be taken care of?

> Hello, we've been able to set full transparency on Windows 10 and Windows 11 with the following code :
> 
> ```go
> import (
> "github.com/lxn/win"
> )
> 
> // other code ...
> 
> func (a *App) startup(ctx context.Context) {
>     hwnd := win.FindWindow(nil, syscall.StringToUTF16Ptr("Your App Title"))
>     win.SetWindowLong(hwnd, win.GWL_EXSTYLE, win.GetWindowLong(hwnd, win.GWL_EXSTYLE)|win.WS_EX_LAYERED)
> }
> ```
> 
> and set this in `main.go` :
> 
> ```go
> err = wails.Run(&options.App{
> ...your_options,
> BackgroundColour: &options.RGBA{R: 0, G: 0, B: 0, A: 0},
> Windows: &windows.Options{
>              WebviewIsTransparent: true,
>              WindowIsTranslucent: false,
>       }
> })
> ```

**Comment by AlexyL** [comment] 2024-09-23 04:00
@jrtp Did you replace `"Your App Title"` with your actual app title?
