### ISSUE TITLE
Triggering the go function in curretn view nesting iframe page, no response

### ISSUE THREAD

**Issue by JoiLa** [wailsapp/wails#2253] opened 2022-12-30 02:26 UTC
### Description

I have a page, in the parent page view, I  inject one iframe page. Triggering the go function in this iframe page view , no response. so I think in iframe view call go function  should  has response.

![image](https://user-images.githubusercontent.com/42708003/210027694-8cdb50fb-77a5-4cab-b28b-0c07450d0459.png)

### To Reproduce

1. git clone git@github.com:JoiLa/wails-v2.2.0-vue-project-example.git
2. cd frontend && npm i;
3. cd the project root && npm run quick-build-windows-app

### Expected behaviour

iframe views in the current page can effectively trigger the go function

### Attempted Fixes

in iframe page view, the code `window.parent.window.go...`  can receive go function response

### System Details

```shell
Wails CLI v2.2.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Enterprise
Version:        2009 (Build: 19045)
ID:             22H2
Go Version:     go1.19.4
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.2.0

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       108.0.1462.54
npm             N/A             Installed       6.14.13
*upx            N/A             Installed       upx 3.96
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Comment by leaanthony** [comment] 2022-12-30 03:05
Duplicate of https://github.com/wailsapp/wails/issues/2047 ?

**Comment by JoiLa** [comment] 2022-12-30 06:19
> Duplicate of #2047 ?

:) I think this problem Not the same , you can try  my provided `reproduce` .

**Comment by leaanthony** [comment] 2022-12-30 22:07
I think it is the same problem because the iframe is a different page so it won't have the bindings injected.

**Comment by JoiLa** [comment] 2023-01-02 03:38
![image](https://user-images.githubusercontent.com/42708003/210193327-3c97b3c3-0c5d-4289-82c8-3d38e0af7901.png)

vue use  history router, so load view already  run wails script

```html
<script src="/wails/ipc.js"></script>
<script src="/wails/runtime.js"></script>
```

**Comment by stffabi** [comment] 2023-01-02 22:31
Yes this is currently not possible.
- For Windows we currently only register for messages from the main frame and not from other frames. We would also need to call the Callback in the correct IFrame.
- For Darwin we receive the call but the callback goes into the main frame instead of the correct frame.
- For Linux I'm not sure if it's possible at all.

Another thing that would need to be discussed how Events should work. One would need to specify the frame into which the Event should be sent.

**Closed** 2023-04-27 09:48 UTC
Labels: Bug, v2
