### ISSUE TITLE
Vue router not working

### ISSUE THREAD

**Issue by adeyinkabadmus** [wailsapp/wails#236] opened 2019-09-14 21:29 UTC
**Description**

When i run the app independently, the vue router works well in the browser but after bundling into executable and running, the view is blank. The template doesn't get loaded in the view.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System Details**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.14-pre |
| Go Version    | go1.12.9 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 9.2.1 |
| Npm           | v11.1.0 |
| Node          | 6.11.3 |

**Additional context**

**Comment by leaanthony** [comment] 2019-09-15 04:28
Duplicate of #150

**Closed by leaanthony** 2019-09-15 04:28 UTC
Labels: Bug, v3

**Comment by adeyinkabadmus** [comment] 2019-09-18 15:37
The view was blank because i had mode in route configuration set to history. It works as expected after removing it. Just in case anyone else has the same problem. Thanks @leaanthony
