### ISSUE TITLE
Wails serves but won't run with built (win10 amd64)

### ISSUE THREAD

**Issue by Tekk-Know** [wailsapp/wails#521] opened 2020-10-07 17:52 UTC
**Description**
I am unable to get wails to work correctly in my win10 env. Testing with vanilla template without any changes after starting project with 'Wails init'. Following along the 'Installing Wails' I am able to get the clean project to serve / display in localhost, but the 'Wails build' .exe will not run and throws script error. 'Script Error', 'Object doesn't support property or method 'addEventListner', Line: 10, Char: 5.

**To Reproduce**
Steps to reproduce the behaviour:
1. 'Wails Init' on clean dir and cd into project
2. 'Wails build -d' in project root
3. On success, navigate to build dir
4. Click on '*outputfilename*.exe'
5. See 'Script Error' on screen.

**Expected behaviour**
I expect application to launch w/o error similar to behavior when serving project in localhost / chrome.

**Screenshots**
![Screenshot 2020-10-07 125034](https://user-images.githubusercontent.com/15911092/95368602-f3e8b780-089b-11eb-9139-a6051032da35.png)

**System Details**
| Name   | Value |
| ----- | ----- |
| Wails Version | v1.8.0 |
| Go Version    | go1.15.2 |
| Platform      | windows |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| GCC           | 9.2.0 |
| Npm           | 6.14.8 |
| Node          | v12.18.3|

**Additional context**

**Comment by Tekk-Know** [comment] 2020-10-07 20:42
The last outputs of the debug console:
```
time="2020-10-07T15:38:21-05:00" level=debug msg="[WebView] Enabling Wails console"
time="2020-10-07T15:38:21-05:00" level=debug msg="[WebView] Eval" js="(function () {\n\n    window.wailsconsole = {};..."
time="2020-10-07T15:38:21-05:00" level=debug msg="[WebView] Eval" js="!function(n){var t={};function e(r){if(t[r])r..."
```

**Comment by leaanthony** [comment] 2020-10-07 21:33
Thanks for reporting this. Will check today.

**Comment by Tekk-Know** [comment] 2020-10-07 21:37
In the webview.go file:
`w.eventManager.On("wails:loaded", callback)` does not appear to fire before error is thrown.  But the `w.window.Run()` is reached though I cannot yet tell if it's running correctly.

**Comment by leaanthony** [comment] 2020-10-09 05:38
Can't reproduce. Installed v1.8.0, created a vanilla app and it worked fine. 
![image](https://user-images.githubusercontent.com/1943904/95547089-e07d4e00-0a4d-11eb-8270-5c5e1b64ea72.png)

**Comment by Tekk-Know** [comment] 2020-10-09 13:10
> Can't reproduce. Installed v1.8.0, created a vanilla app and it worked fine.

Hmm, what's your environment like? What TDM are you using? Is docker needed for build our just for packaging?

**Comment by Tekk-Know** [comment] 2020-10-09 17:16
@leaanthony 
I cleared out wails from my %gopath%\pkg\mod\github.com\wailsapp and re-downloaded it via 'go get'.  I'm showing @v1.8.0.  I'm still seeing this issue. I'm running go1.15.2, but I did go ahead and set my "GO111MODULE" env var to "on" per instructions.  Issue persists per original description.

**Comment by Tekk-Know** [comment] 2020-10-09 17:50
Commenting out the /assets/console.js import in the "webview.go' file changes the error to "Expected Identifier".

**Comment by Tekk-Know** [comment] 2020-10-09 19:04
The imported code from **wails.js** when passed through **evalJS()** causes error during the `w.window.eval(js)` execution, returning "evaluation failed".

**Comment by leaanthony** [comment] 2020-10-09 19:06
I used Wails v1.8.0, TDM with gcc 9 & Win 10 Pro 2004. Is your machine old/slow? I'm wondering if it's a timing issues with old PCs. Not seen it myself...

**Comment by Tekk-Know** [comment] 2020-10-09 19:16
> I used Wails v1.8.0, TDM with gcc 9 & Win 10 Pro 2004. Is your machine old/slow? I'm wondering if it's a timing issues with old PCs. Not seen it myself...

I wouldn't consider it to be slow (i7-7820HQ Quad @ 2.9GHz , 16GB RAM)

**Comment by leaanthony** [comment] 2020-10-11 02:23
run `scripts/build.sh` or `go run build.go` in the scripts directory.

**Comment by Rezrazi** [comment] 2020-10-17 14:08
+1

**Issue description**
After creating a fresh project with `wails init` I tried adding Zendesk's Garden UI kit and inserting a component from that library to the app.
When I run `wails serve` alongside `npm run start` the app renders correctly and everything is fine.
Building the app with `wails build -d` return the following error box https://gyazo.com/316824143d1964c2aa44a4d3817bc058

**App.js**
```javascript
import React from "react";
import { Anchor } from "@zendeskgarden/react-buttons";
import "./App.css";

const App = () => (
  <div className="App">
    <Anchor href="#default">Hey</Anchor>
  </div>
);

export default App;

```

**Comment by leaanthony** [comment] 2020-10-17 18:58
Arrow functions will break IE11 unless you use a polyfill.

**Comment by leaanthony** [comment] 2020-10-17 18:59
@Tekk-Know had issues with the vanilla template yesterday. Investigating.

**Comment by Rezrazi** [comment] 2020-10-17 20:47
> Arrow functions will break IE11 unless you use a polyfill.

Tried again with both class and function Component definition.
Issue persists

**Comment by leaanthony** [comment] 2020-10-17 22:12
The only advice I can offer you is include the UIKit code bit by bit from the vanilla template (which works for me now). See what breaks.

**Comment by leaanthony** [comment] 2020-10-17 22:14
part of me is thinking we should inject corejs on windows by default but this may have unintended consequences.

**Comment by Rezrazi** [comment] 2020-10-17 22:48
> The only advice I can offer you is include the UIKit code bit by bit from the vanilla template (which works for me now). See what breaks. 

I tried going this path, adding imports doesn't break the build, but as soon as I include a ui component into the app, whichever it may be, the build breaks, even the simplest components that are just wrappers around HTML elements such as <H1> which is a wrapper around the regular <h1>

**Comment by leaanthony** [comment] 2020-10-18 04:14
Well IE11 can certainly render h5 so there must be something else going on. If you put your examples in a repo, I'll have a look.

**Comment by Rezrazi** [comment] 2020-10-18 09:38
> Well IE11 can certainly render h5 so there must be something else going on. If you put your examples in a repo, I'll have a look.

I've created a simple wails project that recreates the issue encountered, README is provided for details about the issue
https://github.com/Rezrazi/wailsgarden

**Comment by leaanthony** [comment] 2020-10-18 10:04
Thanks. Your browserlist looks like it might exclude IE11

**Comment by Rezrazi** [comment] 2020-10-18 10:08
> Thanks. Your browserlist looks like it might exclude IE11

the browserlist have not been changed, and they're default from `wails/cmd/templates/create-react-app/frontend/package.json.template`

```json
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

**Comment by leaanthony** [comment] 2020-10-18 19:41
Thanks for the feedback. I wonder how the react template currently works without these? Different version of create-react-app I guess?

**Comment by leaanthony** [comment] 2020-10-18 19:41
@Tekk-Know - I am once again unable to produce this exact issue. The issue I saw turned out to be something completely different in the end.

**Comment by Rezrazi** [comment] 2020-10-18 20:47
> Thanks for the feedback. I wonder how the react template currently works without these? Different version of create-react-app I guess?

It's more specific to the ui package I was trying to use, as I tried a couple other packages, they did not present any issue upon building and running the executable, it seems this package did not ship with polyfills so it was never an issue related to Wails.

However it might perhaps interesting to considering changing the default `package.json` present in the template, and force the IE11 compatibility even for development that way, maybe, we can assure the app runs correctly and is ready to be built for production.

**Comment by leaanthony** [comment] 2020-10-25 09:50
Closing this issue as I cannot reproduce. @Tekk-Know perhaps check out [this](https://wails.app/guides/windows) guide to make it work.

**Closed by leaanthony** 2020-10-25 09:50 UTC
Labels: Bug, cannot reproduce, v3

**Comment by Tak1za** [comment] 2020-11-24 09:03
Not sure if this is the right place, but my wails serve and wails build are out of sync.
Wails serve shows the right things with npm start, but wails build is quite behind with the UI changes.
