### ISSUE TITLE
How to connect it to Nuxt

### ISSUE THREAD

**Issue by AndreiD** [wailsapp/wails#180] opened 2019-08-04 21:10 UTC
Hello all,

I like vue & all, but I found the nuxt framework much easier for a beginner.  https://nuxtjs.org/ 
does anyone know how I can connect Wails to Nuxt 

~~~
import Bridge from "./wailsbridge";

Bridge.Start(() => {
  new Vue({
    render: h => h(App)
  }).$mount("#app");
});
~~~

but there isn't any "App" in Nuxt. 

I tried via a plugin but:

~~~~
import Bridge from "./wailsbridge";

export default ({ app }) => {

  Bridge.Start(() => {
     ???????
  });

}
~~~~

**Comment by leaanthony** [comment] 2019-08-04 21:57
Hi @AndreiD. I'm unfamiliar with Nuxt. If it's difffereenntt enough from the Cue template, a nuxt specific template may be needed. The code within the start() method is whatever code you'd normally run to start Nuxt.

**Comment by bh90210** [comment] 2019-08-05 02:33
Hey @AndreiD it's late over here so if my answer has gaps I will come back tomorrow.

For now a couple of things:
1. What you are after is this https://nuxtjs.org/api/configuration-global-name#the-globalname-property wails tries to find 'app' id.
```Example:

nuxt.config.js

{
  globalName: 'myCustomName' <--- change to 'App'
}
```

WailsBridge I feel I want to say it should go here `/layouts/default.vue` but that is just a guess I might be 100% wrong 
```
Wails.Init(() => {
<template>
  <div>
    <nuxt />
  </div>
</template>
});
```

other than that and I haven't looked much into what options nuxtjs gives you when building, but it I suspect they went after reactjs' `create-react-app` strategy. We dealt with that on reactjs implementation. 
Essentially for `nuxtjs` to produce the build `wails` is needed we'll have to fork this repo https://github.com/nuxt/create-nuxt-app alter it as needed and then push it to our npmjs (ie. https://www.npmjs.com/package/wails-react-scripts) 
(again - I might be wrong on this one as well I'll have a better look in a few hours :+1: )

**Comment by bh90210** [comment] 2019-08-05 10:13
hello, I just realised your are probably using an "older" version of wails! There were some breaking changes around `v0.17.6-pre`.
I would recommend to `wails update -pre` which will install `v0.17.11-pre` but the documentation is not ready yet.
If u feel adventurous though give it a try!

**Comment by AndreiD** [comment] 2019-08-05 16:57
if you want, you can implement https://gitcoin.co/products or some similar reward. I want to give come crypto to anyone that wants to solve this integration

**Comment by leaanthony** [comment] 2019-08-05 21:45
We will certainly look at getting this into v0.18.0. There's been a lot of changes and we need to make sure we don't break everything so nuxt will be bleeding edge for a couple of weeks or so. Just setting expectations 😃

**Comment by o1lab** [comment] 2019-08-19 21:11
+1 

Pointers to integrate with nuxt would be great
Came across wails in one of the meetups. 👍 

And is there a way we can call/use any npm package in wails ?

**Comment by leaanthony** [comment] 2019-08-22 10:25
Hi! Looks like GitHub lost my original reply. 
You can use any npm package you like so long as it can be used in a browser/packed by webpack. 
Out of interest, what Meetup was it and are there slides online? We have a links page and would love to add more content to it.

**Comment by AndreiD** [comment] 2019-08-22 11:31
I think the issue is... we're novices in Javascript. Of course it can be integrated with whatever, but can someone help us with a sample project  :+1:

**Comment by leaanthony** [comment] 2019-08-22 22:22
Of course @AndreiD. I'm not personally across every framework so this really has to be a community effort. We really want to encourage everyone to participate! 🚀

**Comment by bh90210** [comment] 2019-08-23 07:03
OK I have an implementation in the working. I'll have files in a few hours.

I've forked [create nuxt app](https://github.com/bh90210/create-nuxt-app) and modified it as necessary to produce a build that will work with a wails template I am also working on.
I will upload to npm like we did [here](https://www.npmjs.com/package/wails-react-scripts) under wails-nuxt-app and hopefully you will be able to create new projects by running `npx wails-nuxt-app <project-name>`

How it will work: 
* First you will have to update to latest wails `-pre` release
* Then you will have to copy the provided template under [`wails/cmd/templates`](https://github.com/wailsapp/wails/tree/master/cmd/templates)
then to create a new nuxt based project you will
1. run `wails init` as normally and choose nuxt option (at the end of the prompts wails will try to build the project, it will fail but that's ok)
2. then you'll have to cd in `new-project` and run `npx wails-nuxt-app new-project`
3. copy all files created in `new-project/new-project` folder in `new-project/frontend`

from this point on you will be able to use `wails server` and `wails build` as expected. 

Is this solution alright for now?

**Comment by leaanthony** [comment] 2019-08-24 05:19
If this works as intended @bh90210, let's get a PR! 🚀

**Comment by AndreiD** [comment] 2019-08-24 14:54
Hello. I tried to follow all the steps in your "tutorial" but I can't make it to work. building it looks for 

~~~~
⣽ Packing + Compiling project...2019/08/24 17:47:12 open /home/me/workspace_learn/wailsnuxttemplate/frontend**/dist/app.js: no such file or directory**

Mewn 

✗ Packing + Compiling project...
Error: exit status 1
~~~~

upon building the nuxt project, you get 

![image](https://user-images.githubusercontent.com/542665/63639000-7b269c00-c697-11e9-90e1-55e00b31cd71.png)

so there isnt' any app.js there. That is for Vue.js but Nuxt has a little different. 

also I can't get the window to pop-up. It blocks at ">>>>> To connect, you will need to run 'npm run serve' in the 'frontend' directory <<<<<",
but in frontend there's already "npm run dev" running (not serve, as nuxt use dev)

**Comment by bh90210** [comment] 2019-08-24 15:33
I haven't finished the work yet :)
just explained a possible scenario to see if everyone is onboard before start working :+1: 

there are two issues remaining to solve and I'll have everything working but I am not expert with js either so please be patient.

**Comment by AndreiD** [comment] 2019-08-24 17:32
sorry, I missed the part "How it WILL work"

**Comment by codeg33k** [comment] 2019-08-29 11:04
I'm trying to carve out some time to start contributing.

**Comment by leaanthony** [comment] 2019-08-29 11:21
@AndreiD the way it works for the other frameworks is that you just generate a skeleton project and you get a base build. Not sure that's any need for more them that?

**Comment by bh90210** [comment] 2019-08-29 16:30
wrong person tag.. 😂

**Comment by leaanthony** [comment] 2019-09-02 21:21
If we can't get this working this week, let's look at it post v1.

**Comment by leaanthony** [comment] 2019-09-08 22:29
@AndreiD moving this to after the v1 release which will be November. Priority is stabilisation and tying up loose ends for the v1 release.

**Comment by leaanthony** [comment] 2019-10-02 06:57
Closing for now and listing on the https://github.com/wailsapp/wails/wiki/Post-V1-Enhancements page

**Closed by leaanthony** 2019-10-02 06:57 UTC
Labels: Enhancement, v3
