### ISSUE TITLE
run just a vite-express local proxy in main.go

### ISSUE THREAD

**Issue by ganeshkbhat** [wailsapp/wails#2189] opened 2022-12-09 10:38 UTC
### Description

the main.go runs the frontend index.html and the related assets. i wanted to check if I can run just a express localhost:xxxx/ and have it served using my main.go. `frontend/dist/index.html` is served. 

Use case: `I just have a custom built vite-express server https://localhost:8000 or https://www.domain.com:8000/ to be served.`

### To Reproduce

NA

### Expected behaviour

I wish to find if I can run just a local proxy in main.go. I have my own vite-express server running at a perticular host.

### Attempted Fixes

NA

### System Details

```shell
NA - All OS including win, linux, mac.
```

### Additional context

- Run a local proxy instead of index.html frontend
- All OS including win, linux, mac. 

### Currently I am building for Android as well using electron and trying to integrate.

**Comment by leaanthony** [comment] 2024-11-18 09:53
I believe this is a dupe of https://github.com/wailsapp/wails/issues/1469

**Closed by leaanthony** 2024-11-18 09:53 UTC
Labels: Bug, v3
