### ISSUE TITLE
[v2]The window size displayed by the windows application is different from the setting!

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#1164] opened 2022-02-20 22:10 UTC
**Description**
The window size displayed by the windows application is different from the setting, the displayed size is significantly larger than the size set by the parameter.(Please see the screenshot below for the specific effect)

**To Reproduce**
There is no need to reproduce steps, because it can be displayed normally in the previous version, because the recent update caused this problem, you can use the default template to create a new project, and then run to see if this problem exists.

**Expected behaviour**
The window size can be displayed according to the set size.

**Screenshots**
The normal size should be the same size as the red rectangle.
![image](https://user-images.githubusercontent.com/28185258/154866659-e6d094d2-2794-4da6-88de-ce090f47b9db.png)

**System Details**
```shell
$ wails doctor
Wails CLI v2.0.0-beta.30


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.17.6
Platform:       windows
Architecture:   amd64

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       98.0.1108.56
npm             N/A             Installed       8.5.1
*upx            N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Additional context**

**Comment by crushonyou18** [comment] 2022-02-21 01:30
I had the same problem after updating `wails`.

**Comment by leaanthony** [comment] 2022-02-21 06:20
@stffabi - is this related to DPI scaling?

**Comment by stffabi** [comment] 2022-02-21 06:32
Thanks for this report. I've just tried wails `v2.0.0-beta.30` and master and created a new vanilla project. Unfortunately I'm unable to reproduce it and the sizing seems to work fine on my Windows 11 and two other Windows 10 machines. The update to Windows 10 21H2 is currently running on one of my machines and I'll test it again on that.

Do you use some special DPI scaling or other display settings? 

From the screenshot it looks like it somehow would use the max size in your case. Wold it be possible for you to test it without the min max constraints and see if the size is correct in that case?

**Comment by stffabi** [comment] 2022-02-21 06:53
> There is no need to reproduce steps, because it can be displayed normally in the previous version, because the recent update caused this problem, you can use the default template to create a new project, and then run to see if this problem exists.

By previous version do you mean `v2.0.0-beta.29`, or was it an older version?

**Comment by stffabi** [comment] 2022-02-21 08:51
@misitebao I've taken a look into your screenshot and measured the sizes of the windows. It seems like your red rectangle has the size of about 1530x995 pixels. The Vue template seems to use 1600x1000 pixels as initial size. So I assume the red rectangle should be 1600x1000 pixels. The window size that Wails uses seems to be about 2775x1753 pixels. From the initial size of 1600x1000 pixels this seems to be a factor of about 1.75 apart, which would be a hint that a dpi scaling of 175% is in use.

If this is the case and 175% dpi scaling is active, the behaviour seems to be fine in my point of view. The size which a user defines in the options is always in the 100% dpi scaling space and is scaled to the target dpi space of the monitor. In previous versions of Wails this scaling did only work for modulo 100% scaling factors, but not in the case of e.g. 150% or 175%. This has been fixed in `v2.0.0-beta.30` with PR #1098.

AFAIK this is how dpi scaling should work and also how .NET works if AutoScaleMode is set. It seems also to be consistent with the dpi changed event, where Windows gives a suggested new size of the window when dpi scaling has changed.
It is also how scaling works e.g. for the Explorer. An easy test to show the consistent behaviour is to set dpi scaling to 100%, then open the Wails app and open an Explorer window. Resizing the Explorer window to match the windows size of the Wails app. Afterwards one changes the scaling to e.g. 150%. After the change the Wails window and the Explorer window have been resized the same way and both still have the same final size. Opening a new instance of the Wails app then should result in the same final size and should be identical to the Explorer and the first Wails window.

**Comment by leaanthony** [comment] 2022-02-21 09:18
Yeah sounds like it's just scaling up based on DPI.

**Comment by leaanthony** [comment] 2022-02-21 09:22
This is what it looks like to me: 
![image](https://user-images.githubusercontent.com/1943904/154925724-a7b790eb-27c4-4483-a7a1-c0a19333755d.png)

**Comment by misitebao** [comment] 2022-02-21 16:14
> By previous version do you mean v2.0.0-beta.29, or was it an older version?

@stffabi 
My last version is `v2.0.0-beta.28`, it can be displayed normally. During this period, I have upgraded the operating system once, but I have not modified the display related settings, so there are only two reasons for the problem: upgrading wails caused this problem or upgrading The operating system is causing this problem.

**Comment by misitebao** [comment] 2022-02-21 16:18
> which would be a hint that a dpi scaling of 175% is in use.

@stffabi
Your guess is correct, my OS display settings are scaled to 175%, but I didn't change the settings, it was the same before, strangely it was showing fine before.

**Comment by misitebao** [comment] 2022-02-21 16:38
@leaanthony 
My settings are the same as yours, and the results displayed are the same as yours, but the size of the application seems to be different from the size in the settings. And it wasn't like this before, it's a bit smaller than what it shows now.

**Comment by misitebao** [comment] 2022-02-21 16:41
@leaanthony @stffabi 
After my test, it seems that the previous version (26-30) will also display like this. Is it because I upgraded the operating system?

**Comment by leaanthony** [comment] 2022-02-21 19:28
Yes, it wasn't correctly taking DPI into account before.

**Comment by misitebao** [comment] 2022-02-22 20:47
@stffabi @leaanthony 
It seems that something is not right. The zoom value and resolution recommended by my operating system are `200%` and `3000*2000` respectively. I set the wails application to `1600*1000`. After running, the interface exceeds the entire screen, which seems to be the same as Other applications are not the same.
But before that, the size of the program is normal. A recent update caused this change.

**Comment by stffabi** [comment] 2022-02-22 21:09
I'm not quite sure if I understand you correctly. If you have a resolution of `3000*2000` with a scaling ratio of `200%' and startup options of `1600*1000`, the final window size will be `3200*2000`. This exceeds the resolution of `3000*2000` and therefore will exceed the screen. 

Currently there's no logic involved to check that the startup window size won't exceed your screen, and there's also no logic to decrease the startup size automatically. So the startup options must be selected carefully.

**Comment by misitebao** [comment] 2022-02-22 21:19
@stffabi 
OK, I get it.😂

**Closed** 2022-02-22 21:20 UTC
Labels: Bug, v2
