### ISSUE TITLE
Flag to disable backend rebuild in dev

### ISSUE THREAD

**Issue by hkeide** [wailsapp/wails#2053] opened 2022-11-05 11:53 UTC
### Is your feature request related to a problem? Please describe.

I use autosave in my IDE and rebuilding the Go code and thereby resetting the runtime state is too intrusive for me.

### Describe the solution you'd like

Add a flag `-nogorebuild` to `wails dev` to disable the automatic backend rebuild logic

### Describe alternatives you've considered

Adding `-e dummyextension` to the `dev` command seems to accomplish what I want, but I imagine other people may want this behavior too. 

Alternatively this trick could be added to the docs since it seems to work fine.

### Additional context

Happy to create a PR to modify docs or to add an explicit flag if this is desirable.

**Comment by leaanthony** [comment] 2022-11-05 12:44
Yeah feel free to raise a PR for these 👍👍

**Comment by OlegGulevskyy** [comment] 2022-12-13 08:20
Me too during my project dev on wails I realised how much go rebuild on each save `can` be inconvenient, not always is, of course.
I am guessing @hkeide don't have plans to pick up on this, so I could take a swing at this.

To take this a step further, I am thinking of a `wails.json` property to add a glob pattern of files to ignore, when save is occurred. This should give some flexibility - if you want, you ignore all, or just specific files that you don't want go to rebuild.
What do you think @leaanthony ? I am not familiar with the file watcher that `wails` use but it shouldn't be too much of a problem, I imagine?

**Comment by OlegGulevskyy** [comment] 2022-12-13 08:24
By the way @leaanthony , I think this is a duplicate of #2032 , if I am not mistaken.

**Comment by leaanthony** [comment] 2022-12-13 12:30
Similar but not the same.

**Comment by haukened** [comment] 2023-08-29 16:41
Fixed in PR #2870

**Closed** 2023-08-30 11:24 UTC
Labels: Enhancement, TODO, Good First Issue, v3
