### ISSUE TITLE
Window resize using wails dev

### ISSUE THREAD

**Issue by freehelpdesk** [wailsapp/wails#2357] opened 2023-02-07 23:41 UTC
### Description

During testing, wails dev does not provide functionality for resizing the window like it does while compiling while running in frameless mode.

Drag does not work as well when running the app though wails dev

### To Reproduce

Frameless: true
wails dev

### Expected behaviour

The window to be resized and resize events to be handled like it does in the full build of the application

### Screenshots

![image](https://user-images.githubusercontent.com/115826724/217391999-20374b2b-d18f-4166-9543-036513b72b72.png)
![image](https://user-images.githubusercontent.com/115826724/217392078-119af4f4-a48c-4fa0-a84f-0626566b81bb.png)

### Attempted Fixes

Tried modifying the source to allow this on the devserver. Did not succeed.

### System Details

```shell
DEB | Using go webview2loader
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Windows 10 Pro     
Version      | 2009 (Build: 22621)
ID           | 22H2               
Go Version   | go1.19.4           
Platform     | windows
Architecture | amd64

# Wails

Version | v2.3.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 109.0.1518.78
npm        | N/A          | Installed | 9.3.1
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by stffabi** [comment] 2023-02-12 10:09
Thanks for using Wails and reporting this.

Seems like a recently regression, because I'm certain dragging worked for the intial v2 release.

Will try to test it soon.

**Comment by stffabi** [comment] 2023-02-12 19:57
I've just tried that with a clean new project `wails init -n myproject -t svelte` with wails v2.3.1. Resizing and also dragging worked as expected during `wails dev` with a frameless window.

Could you please provide us with a minimal reproduction guide? Can you reproduce it with a clean new wails project?

**Comment by stffabi** [comment] 2023-02-12 20:39
It seems like the wrong IPC is used, when using wails dev it should use the in-process IPC when shown in the app. But from your error message it seems like the websocket IPC is used like when using the browser for accessing the devserver.

Is the IPC probably added manually?

**Comment by stffabi** [comment] 2023-03-01 05:45
@freehelpdesk were you able to solve this with your frontend team?

**Comment by stffabi** [comment] 2023-04-21 05:14
I think we could close this issue, because it seems not be a general resize problem. @freehelpdesk please feel free to reopen it if you need any further help or have question how to track it down.

**Closed by stffabi** 2023-04-21 05:14 UTC
Labels: Bug, cannot reproduce, v2
