### ISSUE TITLE
Support Distribution 'LinuxMint'

### ISSUE THREAD

**Issue by rcprcp** [wailsapp/wails#244] opened 2019-09-28 20:08 UTC
**Description**
Distribution 'LinuxMint' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.0 |
| Go Version    | go1.13 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | LinuxMint |
| Distribution Version   | 19.1 |
| Discovered by   | lsb |

thank you.

**Comment by bh90210** [comment] 2019-09-28 21:53
hello @rcprcp 
mint is supported in the latest pre-release
you can update using `wails update -pre`

duplicate of #232 #238

**Closed** 2019-09-30 20:15 UTC
Labels: Enhancement, v3

**Comment by rcprcp** [comment] 2019-09-30 22:48
Thanks, works perfectly.
