### ISSUE TITLE
need trayMenu

### ISSUE THREAD

**Issue by bing050802** [wailsapp/wails#1454] opened 2022-06-14 09:38 UTC
### Is your feature request related to a problem? Please describe.

old version can use wails.Runtime to add TayVersion,how to do in V2?

### Describe the solution you'd like

https://github.com/overlordtm/trayhost

**Comment by leaanthony** [comment] 2022-06-14 12:01
Duplicate of #1010

**Closed** 2022-06-14 12:02 UTC
Labels: Enhancement, v3
