### ISSUE TITLE
请添加对webgl2,webgpu的支持

### ISSUE THREAD

**Issue by exment** [wailsapp/wails#1497] opened 2022-06-27 01:47 UTC
### Describe the solution you'd like

现在在windows的webview2下是支持webgl的
但是在macos,linux下只支持到webgl1
请添加webgl2的支持，马上webgpu也要正式定稿了，请考虑添加支持，非常感谢！

### Describe alternatives you've considered

查看wails v2源码，使用了https://github.com/zserge/webview
这个库对linux的支持是使用了libwebkit2gtk-4.0-dev，底层使用WebKitGTK已经支持WEBGL2，WEBGPU

**Comment by stffabi** [comment] 2022-06-28 12:46
Thanks for opening the issue. Please take a look into the discussion https://github.com/wailsapp/wails/discussions/1496

We already support WebGL2 on Windows and MacOS. For Linux the Problem is that almost all distributions don't enable WebGL2 in their WebKit2GTK package. So we can't use WebGL2 as long as the installed WebKit2 doesn't support it.

Do you know of a distribution which compiles WebKit2GTK with WebGL2 support?

**Comment by exment** [comment] 2022-07-05 01:26
谢谢，我这里经过测试在mac os 11上 还是webgl1.0，估计到了mac os 12上会自动支持webgl2了吧。。。
webkitgtk的源代码里面有 
WEBKIT_OPTION_DEFAULT_PORT_VALUE(ENABLE_WEBGL2 PRIVATE ON)
但是不知道为何就是使用的webgl1...
另外webkitgtk的source中已经有WEBGPU相关内容，希望WEBGPU定稿以后能直接被支持吧。。。

**Comment by stffabi** [comment] 2022-07-09 13:46
Wails doesn't ship Webkit2 in any way within the binary. So Wails always uses Webkit which is provided by the Operating System. If Apple didn't activate Webgl2 on older MacOS<12 we can't do anything about that. That's how Wails is meant to Work.
If you want to have the exact same browser environment on all Operating Systems you are better served by something like Electron.

**Comment by exment** [comment] 2022-07-14 11:58
非常感谢！

**Comment by leaanthony** [comment] 2022-07-14 12:24
Closing this as there's nothing we can do. Updating GTK may improve this situation and that's covered by another issue 👍

**Closed by leaanthony** 2022-07-14 12:24 UTC
Labels: Enhancement, v3
