### ISSUE TITLE
[v3] AlwaysOnTop dosent work on macos

### ISSUE THREAD

**Issue by marggx** [wailsapp/wails#3834] opened 2024-10-16 20:56 UTC
### Description

Hi, I have created a simple new project with wails3 init. I have set the option AlwaysOnTop: true on the webview window. When i start the app with wails3 dev the window opens as normal, now when i click on any other app the window does not stay on top it goes behind the other window. I created the same project with wails2 and it works fine.

Wails2
```
err := wails.Run(&options.App{
        Title:  "lola2",
        Width:  1024,
        Height: 768,
        AssetServer: &assetserver.Options{
            Assets: assets,
        },
        BackgroundColour: &options.RGBA{R: 27, G: 38, B: 54, A: 1},
        OnStartup:        app.startup,
        Bind: []interface{}{
            app,
        },
        AlwaysOnTop: true,
    })
```
    
Wails3
```
window := app.NewWebviewWindowWithOptions(application.WebviewWindowOptions{
        Title: "Window 1",
        Mac: application.MacWindow{
            InvisibleTitleBarHeight: 50,
            Backdrop:                application.MacBackdropTranslucent,
            TitleBar:                application.MacTitleBarHiddenInset,
        },
        AlwaysOnTop:      true,
        URL:              "/",
    })
```

### To Reproduce

1. create a basic project with wails2 and wails3
2. add AlwaysOnTop in both projects
3. start both projects with wails dev (not simultaneously)
4. wails2 window will aways stay on top
5. wails3 window will get behind other windows

### Expected behaviour

The Wails3 window should stay on top of every window

### System Details

```shell
# System
┌──────────────────────────────┐
| Name          | MacOS        |
| Version       | 14.2.1       |
| ID            | 23C71        |
| Branding      | Sonoma       |
| Platform      | darwin       |
| Architecture  | arm64        |
| Apple Silicon | true         |
| CPU           | Apple M2 Pro |
| CPU           | Unknown      |
| GPU           | Unknown      |
| Memory        | Unknown      |
└──────────────────────────────┘

# Build Environment
┌───────────────────────────────┐
| Wails CLI    | v3.0.0-alpha.7 |
| Go Version   | go1.22.8       |
| -buildmode   | exe            |
| -compiler    | gc             |
| CGO_CFLAGS   |                |
| CGO_CPPFLAGS |                |
| CGO_CXXFLAGS |                |
| CGO_ENABLED  | 1              |
| CGO_LDFLAGS  |                |
| GOARCH       | arm64          |
| GOOS         | darwin         |
└───────────────────────────────┘

# Dependencies
┌────────────────────────────────────────────────────────────────────────┐
| Xcode cli tools | 2405                                                 |
| npm             | 10.8.1                                               |
| *NSIS           | Not Installed. Install with brew install makensis.   |
└─────────────────────── * - Optional Dependency ────────────────────────┘
```

**Comment by leaanthony** [comment] 2024-10-20 01:53
Hi there! Thanks for this feedback.
Whilst v3 is in alpha, we have a strict feedback procedure outlined here: https://v3alpha.wails.io/getting-started/feedback
This is to reduce noise whilst the branch is unstable and keep all the information in one place. We'd love to have you as part of the [v3 feedback](https://discord.gg/ZDBd9bKE) loop so please consider opening a new post there. Just a copy and paste would be fine.
Closing this for now.
Thanks again 🙏

**Comment by leaanthony** [comment] 2024-11-17 09:06
It doesn't crash for me.
@marggx  is it because you're using v3.0.0-alpha7 directly instead of the v3-alpha branch? Perhaps the fix isn't released yet. Check your go.mod to see if the replace line is there. If that still doesn't work, please feel free to reopen this.

**Comment by gtsteffaniak** [comment] 2024-12-05 00:13
I also have this same issue, ill open an issue if this one doesn't get reponed within a week.

**Comment by leaanthony** [comment] 2024-12-05 21:36
I cannot reproduce this with the `v3/examples/window` demo:

https://github.com/user-attachments/assets/f7731dd4-e8f9-4534-abe0-9b68cba94cbc

```# System
┌──────────────────────────────┐
| Name          | MacOS        |
| Version       | 15.1.1       |
| ID            | 24B2091      |
| Branding      | MacOS 15.1.1 |
| Platform      | darwin       |
| Architecture  | arm64        |
| Apple Silicon | true         |
| CPU           | Apple M4 Max |
| CPU           | Unknown      |
| GPU           | Unknown      |
| Memory        | Unknown      |
└──────────────────────────────┘

**Comment by gtsteffaniak** [comment] 2024-12-05 23:13
try something like `v3/examples/hide-window`, doesn't work for me:
![Dec-05-2024 17-12-49](https://github.com/user-attachments/assets/e6f83fa4-3bef-421d-b38f-a59f7fd32210)

```
go 1.23.1

require github.com/wailsapp/wails/v3 v3.0.0-alpha.7

# System
┌──────────────────────────────┐
| Name          | MacOS        |
| Version       | 14.4.1       |
| ID            | 23E224       |
| Branding      | Sonoma       |
| Platform      | darwin       |
| Architecture  | arm64        |
| Apple Silicon | true         |
| CPU           | Apple M1 Pro |
| CPU           | Unknown      |
| GPU           | Unknown      |
| Memory        | Unknown      |
└──────────────────────────────┘

# Build Environment
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| Wails CLI      | v3.0.0-alpha.7                                                                                                            |
| Go Version     | go1.23.1                                                                                                                  |
| -buildmode     | exe                                                                                                                       |
| -compiler      | gc                                                                                                                        |
| CGO_CFLAGS     |                                                                                                                           |
| CGO_CPPFLAGS   |                                                                                                                           |
| CGO_CXXFLAGS   |                                                                                                                           |
| CGO_ENABLED    | 1                                                                                                                         |
| CGO_LDFLAGS    |                                                                                                                           |
| DefaultGODEBUG | asynctimerchan=1,gotypesalias=0,httpservecontentkeepheaders=1,tls3des=1,tlskyber=0,x509keypairleaf=0,x509negativeserial=1 |
| GOARCH         | arm64                                                                                                                     |
| GOARM64        | v8.0                                                                                                                      |
| GOOS           | darwin                                                                                                                    |
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌────────────────────────────────────────────────────────────────────────┐
| Xcode cli tools | 2406                                                 |
| npm             | 10.8.2                                               |
| *NSIS           | Not Installed. Install with `brew install makensis`. |
└─────────────────────── * - Optional Dependency ────────────────────────┘

```

**Comment by leaanthony** [comment] 2024-12-06 11:46
I'm pretty sure it's because you're using alpha.7. I just released alpha.8 with a fix in it: https://github.com/wailsapp/wails/releases/tag/v3.0.0-alpha.8

**Closed** 2024-12-06 11:47 UTC
Labels: Bug, Good First Issue, v3

**Comment by gtsteffaniak** [comment] 2024-12-07 00:04
So I did test this after upgrading to alpha 8 and still saw the issue for my project -- but not the examples.

So, I started from an example and added properties back until I saw the same issue and found the problem:

When a window is initially defined with hidden :

```
		Hidden:      true,
		AlwaysOnTop: true,
```

It doesn't respect the AlwaysOnTop property after .Show() is called on the window, in fact it usually starts unhidden behind most windows.

**Comment by leaanthony** [comment] 2024-12-07 08:54
There are a number of cocoa calls that require the window to be shown first and this may be one of them. We can apply this on the show event like we do to disable the shadow. Great sleuthing. Thanks! 🙏
