### ISSUE TITLE
Accessing local files doesn't work in production build 

### ISSUE THREAD

**Issue by jbrodriguez** [wailsapp/wails#2248] opened 2022-12-27 17:01 UTC
### Description

i created a custom AssetHandler
```
func (h *FileLoader) ServeHTTP(res http.ResponseWriter, req *http.Request) {
	var err error
	requestedFilename := req.URL.Path
	println("Requesting file:", requestedFilename)
	filename := strings.Replace(requestedFilename, "/img/", "", -1)
	fileData, err := os.ReadFile(filename)
	if err != nil {
		res.WriteHeader(http.StatusBadRequest)
		res.Write([]byte(fmt.Sprintf("Could not load file %s", filename)))
	}

	res.Write(fileData)
}
```
the requested filename is something like

`/img//Volumes/storage/music/media/album/cover.jpg`

so i remove `/img/` and open the file (`/Volumes/storage/music/media/album/cover.jpg`) and serve it 

this works in dev (`wails dev`), but in prod (`wails build`) it just doesn't show the image (cover.jpg)

also note that both in dev and prod, the os (macos) requests permission to read the file, which i grant

### To Reproduce

this is a handler management issue

### Expected behaviour

i expected the app to behave the same both in dev and prod

### System Details

```shell
Wails CLI v2.2.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	12.6
ID:		21G115
Go Version:	go1.19.3
Platform:	darwin
Architecture:	arm64

Wails
------
Version: 	v2.2.0

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools  	N/A 		Installed 	2395
npm  				N/A 		Installed 	8.15.0
*upx  				N/A 		Available
*nsis  				N/A 		Available
```
```


### Additional context

_No response_

**Comment by stffabi** [comment] 2022-12-27 19:38
Thanks for using Wails and reporting this issue.

This issue has already been fixed on master. You can use this [guide](https://wails.io/docs/guides/bleeding-edge) to test the master branch.

**Comment by stffabi** [comment] 2022-12-29 08:45
Wails version '2.3.0' has been released with the fix.

Please feel free to reopen if you still have a problem with this.

**Closed** 2022-12-29 08:45 UTC
Labels: Bug, fixed on master, v2

**Comment by kaichaosun** [comment] 2023-06-29 10:50
The issue is still exist with `v2.5.1`.

**Comment by stffabi** [comment] 2023-06-29 12:52
@kaichaosun are you using an AssetHandler? The OP did use that and from your comment it seems like you are trying to open a file somewhere in a Wails app not directly from an AssetHandler.

Did you make sure the `text.json` is in the same location where your binary is? If you don't specify an absolute path the file is being searched relatively to your current working directory and that is the directory of the binary being run as default.

**Comment by tjayrush** [comment] 2024-11-29 11:36
The link above that says, "Use this guide" (https://wails.io/docs/guides/bleeding-edge) doesn't work.

**Comment by leaanthony** [comment] 2024-11-29 19:11
It's the manual builds link
