### ISSUE TITLE
v2.1.0 use wails build report errors panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by ParkourLiu** [wailsapp/wails#1990] opened 2022-10-18 12:07 UTC
### Description

After upgrading from v2.0.0-beta.39.2 to v2.1.0,wails build report errors errors panic: runtime error: index out of range [1] with length 1
![4A@NG PJ3 M5179JM( S6~B](https://user-images.githubusercontent.com/33681340/196421170-d1c82db5-b731-4659-b059-b88665d85de8.png)

Back to v2.0.0-beta.39.2, everything is normal
![H)BCIIRCXO`LJY$PRF%5D}H](https://user-images.githubusercontent.com/33681340/196421896-cc8763c1-6157-4399-97ea-ad77c08f3a3a.png)

### To Reproduce

I don't know how to reproduce in other environments
Only my environment can make this error
Rebuild a new demo,can not be reproduced

### Expected behaviour

nothing

### System Details

```shell
Wails CLI v2.1.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Enterprise LTSC 2019
Version:        1809 (Build: 17763)
ID:
Go Version:     go1.18.6
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.1.0

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       106.0.1370.47
npm             N/A             Installed       8.19.2
*upx            N/A             Available
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download



If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by leaanthony** [comment] 2022-10-18 19:52
Hey there 👋 Thanks for opening this. Looks like you've found an edge case. Are you able to debug this and tell us what kind of struct triggers this? If not, can you show us the structs that you are using so we can reproduce? Thanks.

**Comment by ParkourLiu** [comment] 2022-10-19 01:47
When I make the following changes to the source code, the compilation is normal



![image](https://user-images.githubusercontent.com/33681340/196577809-82b134cb-f473-4005-84a1-e4916cab9f41.png)

**Comment by ParkourLiu** [comment] 2022-10-19 01:51
When I make the following changes to the source code, no error will be reported during compilation



![7QSNG1L~AXHJ())4_X)_O%I](https://user-images.githubusercontent.com/33681340/196578320-4dc9ae89-0c4f-40ee-86d1-8611abecce59.png)

**Comment by leaanthony** [comment] 2022-10-19 07:03
Awesome! Thanks for figuring this out. Are you comfortable making a PR for this?

**Comment by ParkourLiu** [comment] 2022-10-20 11:54
Thank you. I'd like to. I hope wails gets stronger and stronger

**Comment by stffabi** [comment] 2022-11-01 20:43
I think we can close this, since the PR has been merged. Thanks again for providing a PR for fixing this.

**Closed by stffabi** 2022-11-01 20:43 UTC
Labels: Bug, awaiting feedback, v2
