### ISSUE TITLE
Cannot invoke Go functions after refresh page

### ISSUE THREAD

**Issue by fdaines** [wailsapp/wails#2276] opened 2023-01-06 19:22 UTC
### Description

I'm running a Wails+Vue application with `wails dev` that invokes a Go function (declared in the `app.go` file).
After refresh the page (right button in the WebView offers this option), I cannot invoke the backend functions again.

The backend call only works when I restart the command `wails dev`

### To Reproduce

1. `wails dev` to run the application
2. Display a Vue Component which invokes a backend method (declared in `app.go` file)
3. Refresh the webview (right button and "refresh" option)

### Expected behaviour

I can invoke backend Go functions when I refresh the Vue pages.

### Screenshots

<img width="576" alt="image" src="https://user-images.githubusercontent.com/5248484/211084214-f7f7a750-5ce3-41db-a41c-0d50420445fd.png">

### System Details

```shell
wdemo » wails doctor                                                                                                                                                                                ~/fdaines/wdemo
Wails CLI v2.2.0

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | MacOS
Version      | 12.6.1
ID           | 21G217
Go Version   | go1.19.3
Platform     | darwin
Architecture | arm64

# Wails

Version | v2.2.0

# Dependencies

Dependency                | Package Name | Status    | Version
Xcode command line tools  | N/A          | Installed | 2395
npm                       | N/A          | Installed | 8.15.0
*Xcode                    | N/A          | Installed | 14.2 (14C18)
*upx                      | N/A          | Available |
*nsis                     | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by stffabi** [comment] 2023-01-06 19:42
Thanks for using Wails and reporting this issue.

Unfortunately I wasn't able to reproduce this with a new vue bootstrapped project with: `wails init -t vue -d test -n test`

Would it be possible for you to provide us a minimal reproduction guide based on a new vue project?

**Comment by KnockOutEZ** [comment] 2023-03-18 17:52
Same issue with react too

**Comment by stffabi** [comment] 2023-04-18 10:59
Thanks for reporting this, we already have another issue to track this problem. So I'm going to close this one in favour of #2262

**Comment by stffabi** [comment] 2023-04-18 10:59
Duplicate of #2262

**Closed** 2023-04-18 11:00 UTC
Labels: Bug, v2
