### ISSUE TITLE
The dev watcher mode cannot use bound go methods in the console.

### ISSUE THREAD

**Issue by misitebao** [wailsapp/wails#1374] opened 2022-05-04 00:18 UTC
### Description

With dev watcher mode, bound go methods cannot be used in the console.

### To Reproduce

1. go install github.com/wailsapp/wails@v2.0.0-beta.36
2. wails init -n Wails-Vue -t vue
3. cd Wails-Vue
4. Run `wails dev`
5. Visit `localhost:3000` in the browser
6. Unable to access bound go method in console

### Expected behaviour

Binding Go methods can be accessed in the browser console.

### System Details

```shell
$ wails doctor
Wails CLI v2.0.0-beta.36


Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Pro
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.18
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.36
Revision:       531d7cfb629e403084ca122912c096c3fd2f5c34
Modified:       true

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       101.0.1210.32
npm             N/A             Installed       8.3.1
*upx            N/A             Available
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Comment by misitebao** [comment] 2022-05-04 00:39
The reason is the missing `ipc.js` file.

**Comment by stffabi** [comment] 2022-05-04 05:55
Hi @misitebao thanks for this report, seems to me like a duplicate of #1357. 

Connecting directly to Vite will never work, wails can't inject the runtime/bindings there. If you want to develop in a browser, please open the Wails DevServer which is per default on `localhost:34115`

**Comment by misitebao** [comment] 2022-05-05 13:38
@stffabi @leaanthony 
If so, what's the point of `frontend:dev:serverUrl`? And visit `localhost:34115`, when the front-end code is updated, the UI will not be automatically updated.😢

**Comment by stffabi** [comment] 2022-05-05 13:42
Since the introduction of `frontend:dev:serverUrl` Wails now fully supports external devserver and will reverse proxy to the external dev server. So by specifying the `frontend:dev:serverUrl` you can use `wails dev` and you get a fully automatically reloading dev experience by using e.g. vite. You can also browse to  `localhost:34115` which will also do auto reloads.

**Comment by stffabi** [comment] 2022-05-05 13:45
Just use one of the vite powered templates and you have a fully auto reload dev experience. You can either use wails directly and see auto reloads there, or you can browse with your browser to `localhost:34115` and see auto reloads there as soon as the frontend code gets changed and vite has triggered the reload.

**Comment by misitebao** [comment] 2022-05-05 13:49
@stffabi 
When running `wails dev`, the front end will start the development server and generate resources in the virtual directory. It stands to reason that files should not be generated in the `dist` directory, but the `wails dev` command seems to also execute the command in `frontend:build` , and resource files are generated in the `dist` directory.

**Comment by stffabi** [comment] 2022-05-05 13:53
That's not a problem since `wails dev` will use the `vite dev server` to show the frontend.

**Comment by stffabi** [comment] 2022-05-05 14:15
I personally see no problem with those two redundant calls.

**Closed** 2022-05-05 14:21 UTC
Labels: Bug, v2

**Comment by misitebao** [comment] 2022-05-05 14:44
For discussion of the issues mentioned above, please move to https://github.com/wailsapp/wails/discussions/1384
