### ISSUE TITLE
CSS files do not work

### ISSUE THREAD

**Issue by RobQuistNL** [wailsapp/wails#3132] opened 2023-12-14 18:52 UTC
### Description

Adding CSS files in a project does not work in the wails dev app.

### To Reproduce

1. Make project
2. Add e.g. bootstrap css file
3. Add into index.html like so:
```html
    <link href="./src/bootstrap.css" rel="stylesheet">
```
4. No CSS used in dev app (it works in browser on asset browser (port 5174), works in devserver (port 34115), does not work in app.
5. Embedding the contents of the .css file in the .html file with <style> tags works fine
6. See that loading also happens, it just never gets parsed or something

### Expected behaviour

See working CSS

### System Details

```shell
# Wails
Version         | v2.7.1
Package Manager | apt   

# System
┌─────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | Ubuntu                                                                   |
| Version      | 22.04                                                                    |
| ID           | ubuntu                                                                   |
| Go Version   | go1.21.1                                                                 |
| Platform     | linux                                                                    |
| Architecture | amd64                                                                    |
| CPU          | AMD Ryzen 9 5900X 12-Core Processor                                      |
| GPU          | TU102 [GeForce RTX 2080 Ti Rev. A] (NVIDIA Corporation) - Driver: nvidia |
| Memory       | 130GB                                                                    |
└─────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌──────────────────────────────────────────────────────────────────────────┐
| Dependency | Package Name          | Status    | Version                 |
| *docker    | docker.io             | Installed | 24.0.7                  |
| gcc        | build-essential       | Installed | 11.4.0                  |
| libgtk-3   | libgtk-3-dev          | Installed | 3.24.33-1ubuntu2        |
| libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.42.3-0ubuntu0.22.04.1 |
| npm        | npm                   | Installed | 8.19.4                  |
| *nsis      | nsis                  | Available | 3.08-2                  |
| pkg-config | pkg-config            | Installed | 0.29.2                  |
└──────────────────────── * - Optional Dependency ─────────────────────────┘

# Diagnosis
Optional package(s) installation details: 
  - nsis: sudo apt install nsis

 SUCCESS  Your system is ready for Wails development!
```

**Comment by RobQuistNL** [comment] 2023-12-14 19:06
Okay, so somehow you have to "import" the css files inside of the javascript files that are loaded in the html files
:clown_face:

**Comment by stffabi** [comment] 2023-12-14 19:40
Thanks for using Wails and reporting this issue.

This issue has already been discussed several times within the past, it's a duplicate of https://github.com/wailsapp/wails/issues/2705 and is currently a known issue related due to old Webkit versions not providing the request headers and Vite. You could either use an import instead of a link for the CSS file or you could bump your minimum Webkit2 requirement to 2.36 when building your App. You can find more details https://github.com/wailsapp/wails/issues/2705#issuecomment-1585647956.

**Comment by stffabi** [comment] 2023-12-14 19:41
Duplicate of #2705

**Closed** 2023-12-14 19:41 UTC
Labels: Bug, v2
