### ISSUE TITLE
[Feature] Unify width and height for retina displays 

### ISSUE THREAD

**Issue by WizardOfCodez** [wailsapp/wails#481] opened 2020-08-29 16:50 UTC
When coding a cross plattform app we stumbled upon the fact that the pixel size you define in ``createApp`` are different on Mac Retina Displays. That's due a different pixel scale factor (on retina displays 2.0).
On electron someone fixed it like this: https://stackoverflow.com/questions/59385237/electron-window-dimensions-vs-screen-resolution but it would be awesome if wails could handle this by default. 

We still got no working solution now and will update this post if we got one before you :)

**Comment by leaanthony** [comment] 2020-08-29 20:30
Are you using a custom `info.plist`? Because the default has a setting to tackle this: `<key>NSHighResolutionCapable</key><true/>`.

**Comment by CrackDavid** [comment] 2020-08-30 05:43
Yes, already have this in my Info.plist but no change in the app whatsoever :(

**Comment by leaanthony** [comment] 2020-08-30 09:56
Well that's pretty weird. I genuinely though MacOS scaled windows based on what it new about the screen's DPI

**Comment by CrackDavid** [comment] 2020-10-15 17:46
Is this issue still under active research? Would be happy to provide any information

**Comment by leaanthony** [comment] 2020-10-16 02:25
Sounds like we need the Mac equivalent of this PR for Windows: https://github.com/wailsapp/wails/pull/498

**Comment by lightmyfire17** [comment] 2020-10-24 18:05
Facing the same UI scaling problem using 13" Macbook Pro. @leaanthony Is it possible to fix this in near future?

**Comment by leaanthony** [comment] 2020-10-25 02:06
Do you know what the fix might be?

**Comment by leaanthony** [comment] 2020-10-25 10:01
Would this be along the right tracks? https://stackoverflow.com/questions/54429178/hidpi-backingscalefactor-on-macos-how-to-get-actual-value

**Comment by leaanthony** [comment] 2020-10-25 10:03
Hmmm even if we did solve this by patching webview.h, supporting multi monitor might be quite hard. I'm supporting multi monitor in v2 so I'll add this as a task for that.

**Comment by lightmyfire17** [comment] 2020-10-25 10:11
Nice, waiting for the release!

**Comment by leaanthony** [comment] 2020-10-25 11:49
Might be a while but it'll be worth it! 
![image__7_](https://user-images.githubusercontent.com/1943904/97106217-5bb05680-1714-11eb-8340-66bb4afe644a.png)

**Comment by leaanthony** [comment] 2020-10-25 22:13
@CrackDavid - I may have a solution but it would be good to get a bit more information. What does your output look like and what should it look like?

**Comment by CrackDavid** [comment] 2020-10-26 06:47
@leaanthony sure! I meanwhile did some more investigations and it seems that wails is totally behaving correct. More explanation incoming:

We got an app that has hardcoded 768px height. If I open it on my MacBook Pro Mid 2014...

- on the built-in Retina Display: App has nearly the same height as the screen
- on an external monitor: App has only half the size of the monitor

First of all that issue seemed odd because the MacBook should have a full-hd display. If you dig a little deeper I found out that it by default scales the OS to 1440x900 which answers all my questions. 

The only way for wails to correspond to this (I guess you will have the same problems in windows too) is to extract the scaleFactor from the OS and adjust the Application window to that.

But honesty I don't think that this is a feature we really need.

**Comment by leaanthony** [comment] 2020-10-26 07:40
That's great to hear. I did some experiments and got the scaling factor from the system, adjusted width and height and it looked pretty small! I was about to look at scaling the web content so it was all in proportion but it looks like this isn't actually the right solution? I wonder what @lightmyfire17 has to say about this?

**Comment by lightmyfire17** [comment] 2020-10-26 09:31
@leaanthony I'have just set the windows display apps scale to 150%, built the app, then set scale to normal 100% and everything was fine due to this [PR#498 ](https://github.com/wailsapp/wails/pull/498). So for the Mac it's definitely the scaleFactor thing you have to count before the build process starts

**Comment by leaanthony** [comment] 2020-10-26 11:53
Thanks for the info. I can't quite see how this works. If i adjust width and height based on the scale factor, the window is tiny even though i have scaled monitor mode.

**Comment by leaanthony** [comment] 2020-10-29 14:50
@lightmyfire17 please provide something that I can reproduce this as I can't.

**Comment by lightmyfire17** [comment] 2020-10-29 20:02
As @CrackDavid said it's not actually a wails bug itself, just system-related stuff. So, I think you can close the issue, thanks for your time.

**Closed** 2020-10-29 20:34 UTC
Labels: Enhancement, awaiting feedback, v3
