### ISSUE TITLE
feat: clojurescript+reagent template

### ISSUE THREAD

**Issue by Vaelatern** [wailsapp/wails#214] opened 2019-08-27 23:04 UTC
So I'm writing a new template, which will use a tool called `leiningen` to have a clojurescript template, using reagent (clojurescript bindings to react)
I was just wondering what tips I might have before embarking. It seems I make a minimum root project directory, but add a whole `frontend/` directory as created exactly by the tool from its own templates, is that right? Or can I invoke `lein` from `wails init`?

I also imagine I need to bind to certain wails javascript libraries?

**Comment by bh90210** [comment] 2019-08-27 23:34
for the binding please have a look at the existing implementations https://github.com/wailsapp/wails/blob/develop/cmd/templates/create-react-app/frontend/src/index.js
https://github.com/wailsapp/wails/blob/develop/cmd/templates/angular-template/frontend/src/main.ts
https://github.com/wailsapp/wails/blob/develop/cmd/templates/vuebasic/frontend/src/main.js

wails needs two files, a javascript and a css inside a div with id app. 

for the general anatomy of a template see https://github.com/wailsapp/wails/tree/develop/cmd/templates

**Comment by leaanthony** [comment] 2019-08-28 11:54
Hey @Vaelatern, that's a cool idea. Templates are super flexible and can be whatever you want them to be. The main thing to consider is what is in metadata.json. This contains the commands run by wails init, build and serve. Obviously.more goes on that just those commands but they are the hooks.
The most complete example of template.json is the [Angular](https://github.com/wailsapp/wails/blob/develop/cmd/templates/angular-template/template.json) one.

Let is know.if we can help you. Cheers.

**Comment by Vaelatern** [comment] 2019-08-29 00:50
Can I run a command to create the template? Or is the only option copying in the template folder?

**Comment by bh90210** [comment] 2019-08-29 09:36
[you can do it via command line](https://wails.app/development/#tooling), although I don't ever use it, I just copy/paste the boilerplate and take for there.

[take react template as an example](https://github.com/wailsapp/wails/blob/master/cmd/templates/create-react-app/main.go.template)
wails expects a js and a css file.
```go
func main() {

  js := mewn.String("./frontend/build/static/js/main.js")
  css := mewn.String("./frontend/build/static/css/main.css")
```

[and if you take a closer look here](https://github.com/wailsapp/wails/blob/develop/cmd/templates/create-react-app/frontend/src/index.js) js needs to have a div called 'app'
```js
Wails.Init(() => {
  ReactDOM.render(<App />, document.getElementById('app'));
});
```

**Comment by leaanthony** [comment] 2019-08-29 11:18
Not sure if this got documented but if you build a custom wails binary with a "dev" tag then there's a template generator. It's pretty old though bit might be helpful?

**Comment by Vaelatern** [comment] 2019-08-29 14:11
I mean can I have wails run the script for me at init time. Seems the answer is no.

**Comment by bh90210** [comment] 2019-08-29 16:33
please explain what do u mean cause I got confused 😕

**Comment by leaanthony** [comment] 2019-08-29 21:07
@Vaelatern Currently it can generate from any template that exists in [this directory](https://github.com/wailsapp/wails/tree/master/cmd/templates). Feel free to either add your template there manually or use the [dev newtemplate](https://wails.app/development/#creating-new-project-templates) command to make one for you. If you want it to be an official template, please create a PR when it works 👍 As stated previously, we will be adding remote templates hopefully before v1.

**Comment by Vaelatern** [comment] 2019-08-29 21:47
I mean that when a template is used, not created, a script is run. As in, when I use `wails init`, not before then.

**Comment by bh90210** [comment] 2019-08-29 21:59
now I got more confused tbh :smile: 

[from the docs](https://wails.app/development/#tooling)
```
Tooling
The Wails cli has developer tooling built in, but needs activating. To create a developer version, do the following:

cd cmd/wails
go install --tags=dev
This unlocks a wails dev command that has subcommands for development.

#Creating new project templates
With a developer enabled cli, you can run wails dev newtemplate to create a new project template. You will be asked a number of questions regarding your template and as a result, a new directory will be created in <project-root>/cmd/templates.

```

**Comment by Vaelatern** [comment] 2019-08-29 22:20
So, commands get run by you the developer, yes? Things like `ls`, `cd` etc. `wails init` is such a command.

To start a new leinginen project you run `lein new` . Instead of me running `lein new` on my system, I want to run it on the user's system.
Can I?

**Comment by bh90210** [comment] 2019-08-29 22:30
first of all I am 100% unfamiliar with clojure or leinginen.

if it was JS something like angular's cli [(see how we dealt with it here)](https://github.com/wailsapp/wails/blob/master/cmd/templates/angular-template/frontend/package.json.template) (or create-react-app or create-nuxt-app etc) could apply. 

but if u need `lein new` to run, it is going to be a two step process, which I think is fine (!), at least for now. Although I can see potential uses of wails being able to exec/run commands after `wails init`.

**Comment by Vaelatern** [comment] 2019-08-30 00:50
I can PR the support to run a template script if you like. I've run commands from other golang projects.

**Comment by leaanthony** [comment] 2019-08-30 07:59
It sounds like you want to mainly use `lein` to do the actual projects and bolt Wails around it. Our current model is to dump out known working versions of templates and let people customise as they need. 'Outsourcing' the template generation could lead to a lot of support headaches so we probably wouldn't support that directly. However, if you really wanted to do this, you have the freedom to call what you like via the ["init" and "install"](https://github.com/wailsapp/wails/blob/master/cmd/templates/angular-template/template.json#L12-L13) values. Wails init will first call the "init" script, then, if successfull, the "build" script. 

Are these the hooks you're looking for?

**Comment by Vaelatern** [comment] 2019-08-30 13:30
Install and build are used after the template is created, isn't that the case?

I'm looking for a oneshot creation, does install offer this? A creation script that's never called again?

**Comment by leaanthony** [comment] 2019-08-31 10:53
Not directly. I was inferring that whatever you called for install could do that. I think it's something we *could* look at but I think probably in the context of remote templates. Mainly because issues with those tools shouldn't be flooding this project, which is the danger. I'm open to it, just needs some more thought and discussion.

**Comment by Vaelatern** [comment] 2019-09-02 07:30
I'm afraid I'm a bit of a javascript novice.

When wails projects have an npm dependency on `@wailsapp/runtime`, what does that mean? Specifically, why the `@` sign?

What javascript must be called from my template? Must I begin my app with a `Wails.Init()` call?

**Comment by leaanthony** [comment] 2019-09-03 12:20
That's the runtime library for the frontend. The @ just indicates the username. Your frontend can be clojurescript. Justmake sure you import the runtime and call the Init() function like the oher templates. The callback to this is called when the runtime is ready.

**Comment by leaanthony** [comment] 2019-09-13 08:08
Hmmmm.... that's weird. Do you think it's a webpack thing? Do you have a link to your source you can share so I can debug it?

**Comment by Vaelatern** [comment] 2019-09-19 06:59
I'm trying to turn it into a reasonable template with the same CSS for the rotating image so I can demonstrate in a simple way. Also properly debug.

**Comment by leaanthony** [comment] 2019-09-19 08:56
Let me know if I can help in any way.

**Comment by Vaelatern** [comment] 2019-09-19 13:42
Yeah, the default background, that's just done with CSS? I don't have to find any javascript doing weird magic?

**Comment by leaanthony** [comment] 2019-09-19 19:26
Indeed! Simply CSS.

**Comment by Vaelatern** [comment] 2019-09-20 05:36
Ah. When I do a wails build, the wails connector doesn't get injected. window.wails never gets defined. (Though that may be unrelated).
But when I wails serve, the wails connector works great.

Relatedly, the binary (wails build) has connected in the past to a frontend left over from a previous run (wails serve).

Working on that minimum example still to get something tangible for debugging that isn't crazy long.

**Comment by airking05** [comment] 2019-09-27 14:00
I think the problem is that your binary app isn't injected "wailsbridge.prod.js" properly and wails connector show up in build mode...

see there
https://github.com/wailsapp/wails/blob/7dd42f964b4998323668a17cddd64ecd11a67190/cmd/helpers.go#L276

**Comment by Vaelatern** [comment] 2019-09-27 14:17
Hm, that could well be. The deal with clojurescript is it doesn't use a traditional npm build, so things that only function within NPM normally will not necessarily do so here.

Still working on this though.

**Comment by airking05** [comment] 2019-09-27 14:49
@Vaelatern can you show me the result of below command?
we have to check versions of wails.

`wails version
cat go.mod|grep wails`

**Comment by Vaelatern** [comment] 2019-09-27 15:30
0.17.15-pre right now.

**Comment by leaanthony** [comment] 2019-10-02 06:56
@Vaelatern any progress? Is there anything I can help with? I'm closing a lot of tickets temporarily whilst we go into feature freeze and will re-open post v1. Listing on the https://github.com/wailsapp/wails/wiki/Post-V1-Enhancements page.

**Closed** 2019-10-02 06:56 UTC
Labels: Enhancement, v3
