### ISSUE TITLE
[V2, Bug] Window maximized on negative coordinates

### ISSUE THREAD

**Issue by IrishBruse** [wailsapp/wails#1094] opened 2022-01-22 19:26 UTC
**Description**
When maximized the window on my monitor that is on the left of my main display the window spans all the monitors at once. This only happens on the left one apposed to my right one which makes me assume it is due to the windows x coordinates being < 0

**To Reproduce**
Steps to reproduce the behaviour:
Maximize a window that is in negative screen x coordinates.

**Expected behaviour**
The window to only maximize to fit the single screen and not to span all 3 screens

**Screenshots**
## Left monitor when maximized
![image](https://user-images.githubusercontent.com/14964651/150652716-7ff08907-bd68-4da5-bf00-d33de7b3cdb5.png)

Middle When maximized
![image](https://user-images.githubusercontent.com/14964651/150652731-70189b4d-04e2-43f0-8ff2-77cac52e8feb.png)

Right when maximized
![image](https://user-images.githubusercontent.com/14964651/150652734-3bfdeadf-1439-4084-a128-bb0a74d60d30.png)

**System Details**
V2 users: Please add the output of `wails doctor`.
![image](https://user-images.githubusercontent.com/14964651/150652829-d18f352c-1837-4705-aa50-ab6702540fc0.png)

- [x] This issue is for Windows and I have read the [Windows Developer Guide](https://wails.app/guides/windows/)

**Comment by leaanthony** [comment] 2022-01-22 22:44
Hey thanks for reporting this! I have no way of reproducing this so it's going to take guess work. @stffabi has done a bit of work on this recently so maybe there's something obvious to them?

**Comment by stffabi** [comment] 2022-01-26 07:56
Unfortunately I was also unable to reproduce this. I've tried it with 2 displays, does it happen for you on 2 displays only? Would it be possible for you provide a minimal main.go with your settings? Maybe Min/Max Width/Height has some effects. 

It's interesting that this happens because AFAIR maximizing is done by Windows itself.

**Comment by IrishBruse** [comment] 2022-01-26 23:05
so I figured out it is caused only on the left monitor when i set the max size to this
![image](https://user-images.githubusercontent.com/14964651/151261550-444b659e-b5df-45bc-a8d7-a764311c92db.png)
if i just delete the max size variables then it doesnt bug out it seems to be a bug when the max size is bigger than what the window actually grows to

![image](https://user-images.githubusercontent.com/14964651/151261953-4603da5e-863e-4301-9b7b-6f960690487f.png)
it appears the the window forces it self to be the max size when maximizing instead of just the size to fix the display

**Comment by stffabi** [comment] 2022-01-27 07:50
Thanks @IrishBruse I was able to reproduce it and I have an idea where the problem lies. I'll keep you updated.

**Comment by stffabi** [comment] 2022-01-27 08:48
Could you please give PR leaanthony/winc#14 a try by replacing winc version in your go.mod with `github.com/stffabi/winc v0.0.0-20220127083852-9801ff2555c0`

**Comment by leaanthony** [comment] 2022-01-27 08:50
Nice debugging @IrishBruse and thanks for picking this up @stffabi! I'll merge once it gets the green light.

**Comment by leaanthony** [comment] 2022-02-01 09:06
@IrishBruse - Any feedback? Keen to merge this fix in 👍

**Comment by IrishBruse** [comment] 2022-02-01 09:39
Ill check it out in a few hours sorry for the wait been away from my PC.

**Comment by IrishBruse** [comment] 2022-02-01 21:33
> github.com/stffabi/winc v0.0.0-20220127083852-9801ff2555c0

Yup that fixed it in my project and a new empty wails app with the max width and height changed.

**Comment by stffabi** [comment] 2022-02-03 05:45
@IrishBruse awesome, thanks so much for testing. The winc PR has been merged and #1122 to bump the dependency is created.

**Closed** 2022-02-03 06:05 UTC
Labels: Bug, v3
