### ISSUE TITLE
After Build Cannot Run in Win10 AMD64

### ISSUE THREAD

**Issue by divowu** [wailsapp/wails#1837] opened 2022-09-09 03:38 UTC
### Description

 I create a HelloWorld project  and build it. But the builded application cannot runing in my windows 10 amd64.(Nothing window ui being open) 
It can runing well in  win 11.

### To Reproduce

1, create a helloworld project and build it , with below wails commands:
   wails init -n helloworld
    wails build 
2, Double click the compiled exe file : ${project folder}/build/bin/helloworld.exe

After clicked , nothing happen in my win10 amd64, but it work in win11 amd64.

### Expected behaviour

Nothing.

### System Details

```shell
Wails CLI v2.0.0-beta.44.2

System
------
OS:             Windows 10 Pro
Version:        1903 (Build: 18362)
ID:
Go Version:     go1.19.1
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.44.2

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       105.0.1343.27
npm             N/A             Installed       8.19.1
*upx            N/A             Installed       upx 3.96
*nsis           N/A             Installed       v3.08

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!

If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

**Comment by giteshnxtlvl** [comment] 2022-09-09 06:11
Working with these specs. 

```
Wails CLI v2.0.0-beta.44.2

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Windows 10 Home
Version:        2009 (Build: 19044)
ID:             21H2
Go Version:     go1.18.5
Platform:       windows
Architecture:   amd64

Wails
------
Version:        v2.0.0-beta.44.2

Dependency      Package Name    Status          Version
----------      ------------    ------          -------
WebView2        N/A             Installed       105.0.1343.27
npm             N/A             Installed       8.11.0
*upx            N/A             Available
*nsis           N/A             Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Comment by stffabi** [comment] 2022-09-09 07:54
Thanks for using Wails und reporting this.

Could you please build a debug build `wails build --debug` and paste the output of the console when started from the command line on your Win10 system?

Thanks 🙏

**Comment by divowu** [comment] 2022-09-09 08:31
Thanks for your quick reply！ 

When I use this command, it has the following error:
Building target: windows/amd64
------------------------------
  - Installing frontend dependencies: Done.
  - Compiling frontend: Done.
  - Generating bundle assets: Done.
  - Compiling application: Error: open D:\workspace\go\wails\helloworld\frontend\wailsjs\runtime\package.json: Access is denied.

ERROR: open D:\workspace\go\wails\helloworld\frontend\wailsjs\runtime\package.json: Access is denied.

And I found out the folder ‘frontend/wailsjs/runtime’ has been deleted.

**Comment by divowu** [comment] 2022-09-09 08:41
The above error occurred when I used this command ‘wails build -debug’.

When I use 'wails dev‘, And then I got blow message:

vite v2.9.15 building for production...
    transforming...
    ✓ 4 modules transformed.

    Could not resolve '../wailsjs/go/main/App' from src/main.js
    error during build:
    Error: Could not resolve '../wailsjs/go/main/App' from src/main.js
        at error (D:\workspace\go\wails\helloworld\frontend\node_modules\rollup\dist\shared\rollup.js:198:30)
        at ModuleLoader.handleResolveId (D:\workspace\go\wails\helloworld\frontend\node_modules\rollup\dist\shared\rollup.js:22464:24)
        at D:\workspace\go\wails\helloworld\frontend\node_modules\rollup\dist\shared\rollup.js:22427:26

ERROR: exit status 1

**Comment by divowu** [comment] 2022-09-09 09:10
Sorry for my mistaken.
 The command I used ‘wails build --debug' instead of ‘wails build -debug'， It can build a debug mode application.
But I run the application, It hold on a black screen.

![mistaken](https://user-images.githubusercontent.com/43426822/189315131-9c1cf797-acfc-4fa6-8f24-d98b49ce1514.PNG)

**Comment by 107295472** [comment] 2022-09-13 00:24
me too
And I found out the folder ‘frontend/wailsjs/runtime’ has been deleted.
And I found out the folder ‘frontend/wailsjs/go/main’ has been deleted.

**Comment by leaanthony** [comment] 2022-09-13 01:57
@divowu @107295472 - Could you please try the latest release as this includes a change that should fix this issue? To upgrade, please run: `wails update -pre`

**Comment by 107295472** [comment] 2022-09-13 02:07
D:\gowork>wails init -n gorelease -t vue
Wails CLI v2.0.0-beta.rc.1

Initialising Project 'gorelease'
--------------------------------

go: downloading github.com/wailsapp/wails/v2 v2.0.0-beta.rc.1
changeme imports
        github.com/wailsapp/wails/v2: reading github.com/wailsapp/wails/go.mod at revision v2.0.0-beta.rc.1: git ls-remote -q origin in D:\go\pkg\mod\cache\vcs\dbbb6a107e3dfe96e9ff1ab7827b976e6610ab061efea00c59230864b280a6d6: exit status 128:
        fatal: unable to access 'https://github.com/wailsapp/wails/': Failed to connect to github.com port 443 after 21051 ms: Timed out
changeme imports
        github.com/wailsapp/wails/v2/pkg/options: reading github.com/wailsapp/wails/go.mod at revision v2.0.0-beta.rc.1: git ls-remote -q origin in D:\go\pkg\mod\cache\vcs\dbbb6a107e3dfe96e9ff1ab7827b976e6610ab061efea00c59230864b280a6d6: exit status 128:
        fatal: unable to access 'https://github.com/wailsapp/wails/': Failed to connect to github.com port 443 after 21051 ms: Timed out


ERROR: exit status 1

**Comment by 107295472** [comment] 2022-09-13 02:13
Error: CreateFile D:\gowork\gorelease\frontend\wailsjs\go\main: Access is denied.
Unable to kill process and cleanup binary: TerminateProcess: Access is denied.
ERROR: GetFileAttributes: The system cannot find the file specified.

**Comment by 107295472** [comment] 2022-09-13 02:17
D:\gowork\gorelease>wails dev
Wails CLI v2.0.0-rc.1.1

Executing: go mod tidy
Building frontend for development...
  - Generating bindings: Done.
  - Installing frontend dependencies: Done.
  - Compiling frontend: Done.

> frontend@0.0.0 dev
> vite


  VITE v3.1.0  ready in 261 ms

Vite Server URL: http://127.0.0.1:5173/
  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
Running frontend DevWatcher command: 'npm run dev'
Building application for development...
  - Generating bindings: Done.
  - Generating bundle assets: Done.
  - Compiling application: Done.

watching: D:\gowork\gorelease
watching: D:\gowork\gorelease\build
watching: D:\gowork\gorelease\build\bin
INF | Serving assets from frontend DevServer URL: http://127.0.0.1:5173/
watching: D:\gowork\gorelease\build\darwin
watching: D:\gowork\gorelease\build\windows
watching: D:\gowork\gorelease\build\windows\installer
DEB | WebView2 Runtime Version '105.0.1343.33' installed. Minimum version required: 94.0.992.31.
watching: D:\gowork\gorelease\frontend
watching: D:\gowork\gorelease\frontend\dist
watching: D:\gowork\gorelease\frontend\dist\assets
watching: D:\gowork\gorelease\frontend\src
watching: D:\gowork\gorelease\frontend\src\assets
Error: CreateFile D:\gowork\gorelease\frontend\wailsjs\go\main: Access is denied.
watching: D:\gowork\gorelease\frontend\src\assets\fonts
watching: D:\gowork\gorelease\frontend\src\assets\images
watching: D:\gowork\gorelease\frontend\src\components
watching: D:\gowork\gorelease\frontend\wailsjs
watching: D:\gowork\gorelease\frontend\wailsjs\go
Unable to kill process and cleanup binary: TerminateProcess: Access is denied.
ERROR: GetFileAttributes: The system cannot find the file specified.

**Comment by 107295472** [comment] 2022-09-13 02:19
build no problem

**Comment by 107295472** [comment] 2022-09-13 02:35
wailsjs/go/   not generated

**Comment by 107295472** [comment] 2022-09-13 03:18
dev did not call the method of generating files? GenerateGoBindings

**Comment by divowu** [comment] 2022-09-13 08:20
@leaanthony ,
I update wails with your command `wails update -pre` and update the wails module to v2.0.0-rc.1.1, build a debug mod application with `wails build --debug`. It still hold on a black screen.
![mistaken](https://user-images.githubusercontent.com/43426822/189849400-046fd25c-296d-492e-bfa0-577addb5453e.PNG)

**Comment by leaanthony** [comment] 2022-09-13 08:21
How can I test windows 10 ARM?

**Comment by leaanthony** [comment] 2022-09-13 08:22
One thing to do: build with `wails build -debug` and them right click the blank window and check the console logs

**Comment by stffabi** [comment] 2022-09-13 08:24
@divowu It seems like you are selecting one character from the console window, indicated by the "white rectangle" in your last screenshot. If you select in the console window, the whole app is getting blocked, this is a common behaviour on windows due to blocked message loop.
Please deselect by clicking again into the console window and pressing enter.

**Comment by stffabi** [comment] 2022-09-13 09:12
Have you tried use `wails dev`? What's the output there?

**Comment by divowu** [comment] 2022-09-13 09:52
FY. 
![image](https://user-images.githubusercontent.com/43426822/189871085-6ff7e0b7-f365-4e4e-b3ba-10dde151abe0.png)

**Comment by leaanthony** [comment] 2022-09-14 23:46
I'm not really sure this relates to the architecture of your OS. If you create a new project, using the release candidate, are you able to reproduce this error? This looks like bad imports to me.

**Comment by 107295472** [comment] 2022-09-15 02:28
Can't use dev, build, or tasks in vscode

**Comment by HeCorr** [comment] 2023-04-14 14:20
I'm also having issues on Windows.. on the rare occasions where the build succeeds (similar behavior as #2367), running the output .exe does literally nothing, not even launching it via CMD. That being said, `wails dev` launches just fine (when it decides to).

What makes this really frustrating to me is that I've been trying to create this program for a friend of mine for about a week, first with Fyne and then Gio but I was unable to get anywhere with either of them, so I tried with Wails and did succeed, but I am unable to build the program for my friend to use.

I'm on Windows 10 and already tried Wails versions `2.4.1`, `2.4.0` and `2.3.1` (`wails update -pre` did nothing) to no avail.

As far as I can tell, the WebView2 runtime **is** installed on my system (it said so when trying to install it manually).

**Comment by HeCorr** [comment] 2023-04-14 15:47
Update: I just learned that by not including the `-windowsconsole` flag during builds, it doesn't show any errors if you launch the .exe via CMD/Powershell (which I guess kinda makes sense), so it turned out that I had changed the code in a way that prevented it from properly functioning and it *was* producing an error, I just couldn't see it due to the lack of the flag.

I have now fixed the code and it now works as expected. It still doesn't explain why dev builds worked, but I digress.

Please disregard my previous comment.

**Comment by misitebao** [comment] 2023-04-14 16:36
Please switch to the latest version and try again, if the error persists, please provide the reproduction code.

**Comment by leaanthony** [comment] 2023-04-14 20:59
@HeCorr could you possibly explain what the core issue was and if we need to fix something? Thanks

**Comment by HeCorr** [comment] 2023-04-14 23:12
@leaanthony I had removed a piece of code that I thought wasn't essential (because dev builds kept working without it) but turned out to be, so as far as I can tell, `build` doesn't need fixing, but `dev` definitely does: #2367

**Comment by HeCorr** [comment] 2023-04-14 23:17
Actually, that issue seems to be a bit different than mine. My `wailsjs/runtime` and `wailsjs/go` folders do get deleted/recreated when starting up a dev instance and that often causes (what I believe to be) `tsc` errors saying that the module wasn't found.

If you want I can create a separate issue that addresses it with more details.

**Comment by leaanthony** [comment] 2023-04-15 08:15
That would be great, thanks!

**Closed** 2024-11-17 21:42 UTC
Labels: Bug, Unconfirmed, v3
