### ISSUE TITLE
MacOS HTMX polling fails

### ISSUE THREAD

**Issue by difof** [wailsapp/wails#3155] opened 2023-12-23 17:09 UTC
### Description

Whenever I use HTMX polling, only the first request is received by Go and the rest won't even show up in inspector's network. This works on all major browsers using wails exposed http interface though. Enabling HTMX logs via `htmx.logAll()` shows the XHR and other HTMX events caused by the polling, yet only one network request is made.

### To Reproduce

1. On MacOS, create a basic wails project `wails init -n htmx-test -t vanilla`
2. Import HTMX script in `frontend/index.html`

```html
<script src="https://unpkg.com/htmx.org@1.9.10"></script>
```

3. Add an HTMX element with polling:

```html
<div hx-get="/now" hx-trigger="load, every 1s"></div>
```

5. Use an HTTP middleware for wails asset server. I used echo:

```go
func main() {
	app := NewApp()
        e := echo.New()
	
	e.GET("/now", func(c echo.Context) error {
		return c.String(http.StatusOK, time.Now().Format(time.TimeOnly))
	})

	err := wails.Run(&options.App{
		Title:  "test",
		Width:  1024,
		Height: 768,
		AssetServer: &assetserver.Options{
			Assets: assets,
			Middleware: func(next http.Handler) http.Handler {
				return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
					for _, route := range e.Routes() {
						if route.Path == r.URL.Path {
							e.ServeHTTP(w, r)
							return
						}
					}

					next.ServeHTTP(w, r)
				})
			},
		},
	})

	if err != nil {
		println("Error:", err.Error())
	}
}
```

6. Run `wails dev` and you will get single request to `/now`

### Expected behaviour

HTMX polling to successfully send requests

### System Details

```shell
MBP M1 2020 16GB
MacOS 14 Sonoma
```

**Comment by stffabi** [comment] 2023-12-30 23:18
Thanks for using Wails and opening this issue.

I suspect the problem is that macOS WKWebView is going to cache your response and reuses that and therefore only executes the request once.

Please try adding a `Cache-Control` header to the response to prevent caching it.

```go
e.GET("/now", func(c echo.Context) error {
	c.Response().Header().Add("Cache-Control", "no-store")
	return c.String(http.StatusOK, time.Now().Format(time.TimeOnly))
})
```

**Comment by difof** [comment] 2023-12-31 13:15
@stffabi disabling cache solved it! Why is it caching the requests made via `wails://` scheme and doesn't cache HTTP scheme though?

**Comment by stffabi** [comment] 2023-12-31 14:07
No idea, that's probably something only apple can answer. I think we can close this issue, as the problem has been solved for you.

**Closed** 2023-12-31 15:38 UTC
Labels: Bug, awaiting feedback, v3, Not a Wails Issue
