### ISSUE TITLE
[v2] delay when dragging a window with `data-wails-drag` attribute

### ISSUE THREAD

**Issue by ghostiam** [wailsapp/wails#1703] opened 2022-08-06 05:50 UTC
### Description

After [fix](https://github.com/wailsapp/wails/issues/1313) ([commit](https://github.com/wailsapp/wails/commit/e994a6f8c4c170900e520e58b820ecee28035650)), when [dragging a window using 3 fingers](https://support.apple.com/en-gb/HT204609), the window is not dragged immediately, but after a delay.
When I paste the old code into the console (after 12 seconds in the video), there are no such problems.

### To Reproduce

Dragging a window using 3 fingers on MacOS trackpad.

### Expected behaviour

Move window immediately.

### Screenshots

https://user-images.githubusercontent.com/12181586/183136483-057d3fb2-767b-4515-921a-c2d505732e2d.mov

### Attempted Fixes

Use old code.

### System Details

```shell
$ wails doctor
Wails CLI v2.0.0-beta.42

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:		MacOS
Version: 	12.4
ID:		199506
Go Version:	go1.18.5
Platform:	darwin
Architecture:	arm64

Wails
------
Version: 	v2.0.0-beta.42

Dependency			Package Name	Status		Version
----------			------------	------		-------
xcode command line tools 	N/A		Installed	2395
npm 				N/A		Installed	8.12.1
*upx 				N/A		Available
*nsis 				N/A		Available

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : Available at https://nsis.sourceforge.io/Download
```

**Comment by leaanthony** [comment] 2022-08-06 06:35
Thanks for reporting this. It has been raised before and @stffabi and I have looked at it. I think I may even have a branch somewhere with a potential fix. The issue is, the doubleclick event is not fired in the old code. I think the use case for needing both drag and doubleclick is where you make your own titlebar and want to have doubleclick maximise the window. Any thoughts on how you'd tackle that problem?

**Comment by leaanthony** [comment] 2022-08-06 07:19
Please try the above PR to see if this fixes your problem. If you are unsure how to do this, please follow [this guide](https://wails.io/docs/guides/bleeding-edge#testing-a-pr). Let us know how you get on 👍

**Comment by ghostiam** [comment] 2022-08-06 07:29
I'll check in a few hours.  Thanks.

**Comment by leaanthony** [comment] 2022-08-06 07:30
@kiddov this might be the best fix for this if you want to check it out...

**Comment by ghostiam** [comment] 2022-08-06 08:25
@leaanthony On MacOS the fix works, checked click, double click, mouse up, mouse down, mousemove

```js
window.addEventListener("click", (e) => console.log("click"))
window.addEventListener("dblclick", (e) => console.log("dblclick"))
window.addEventListener("mouseup", (e) => console.log("mouseup"))
window.addEventListener("mousedown", (e) => console.log("mousedown"))
window.addEventListener("mousemove", (e) => console.log("mousemove"))
```

https://user-images.githubusercontent.com/12181586/183241133-5492ef7e-512f-4c6b-9086-2eacc6011d97.mov

**Closed** 2022-08-08 07:27 UTC
Labels: Bug, Ready For Testing, v2

**Comment by ghostiam** [comment] 2022-08-08 09:58
@leaanthony Thank you for the fix and for the project!
